from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path

from app_tool.registry import all_tool_specs
from app_tool.specs import ToolSpec

GENERATED_COMMENT = (
    "<!-- This file is generated by uv run app-docs generate-tools. Do not edit manually. -->"
)
TOOLS_DOCS_DIR = Path("docs/spec/tools")


def md_join(values: Iterable[str]) -> str:
    items = tuple(values)
    if not items:
        return "-"
    return "<br>".join(f"`{item}`" for item in items)


def md_escape(value: str) -> str:
    return value.replace("|", "\\|")


def tool_dir(spec: ToolSpec, output_dir: Path) -> Path:
    return output_dir / spec.name


def render_tools_list(specs: tuple[ToolSpec, ...]) -> str:
    lines = [
        GENERATED_COMMENT,
        "",
        "# Tools 一覧",
        "",
        "| Tool名 | 日本語の説明 |",
        "| :--- | :--- |",
    ]
    for spec in specs:
        lines.append(f"| `{spec.name}` | {md_escape(spec.summary)} |")
    return "\n".join(lines) + "\n"


def render_usage(specs: tuple[ToolSpec, ...]) -> str:
    lines = [
        GENERATED_COMMENT,
        "",
        "# Tools usage",
        "",
        "## 統一コマンド",
        "",
        "```bash",
        "uv run app-codegen all",
        "uv run app-docs generate",
        "uv run app-docs generate --check",
        "uv run app-archlint all",
        "```",
        "",
        "## 互換コマンド",
        "",
    ]
    for spec in specs:
        lines.extend(
            [
                f"### `{spec.name}`",
                "",
                spec.summary,
                "",
                "```bash",
                spec.command,
                "```",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def render_artifacts(specs: tuple[ToolSpec, ...]) -> str:
    lines = [
        GENERATED_COMMENT,
        "",
        "# Tools artifacts",
        "",
        "| Tool | Category | 入力 | 出力 | check | CI |",
        "| :--- | :--- | :--- | :--- | :--- | :--- |",
    ]
    for spec in specs:
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{spec.name}`",
                    spec.category,
                    md_join(spec.inputs),
                    md_join(spec.outputs),
                    "yes" if spec.check_supported else "no",
                    "yes" if spec.safe_to_run_in_ci else "no",
                ]
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def render_execution_flow(specs: tuple[ToolSpec, ...]) -> str:
    lines = [
        GENERATED_COMMENT,
        "",
        "# Tools execution flow",
        "",
        "```mermaid",
        "flowchart TD",
    ]
    for spec in specs:
        lines.append(f"  {spec.name}[{spec.name}]")
        for dependency in spec.depends_on:
            lines.append(f"  {dependency} --> {spec.name}")
    lines.extend(["```", ""])
    return "\n".join(lines)


def render_testcase_spec(specs: tuple[ToolSpec, ...]) -> str:
    lines = [
        GENERATED_COMMENT,
        "",
        "# Tools testcase spec",
        "",
        "| Case | 対象 | 期待 |",
        "| :--- | :--- | :--- |",
        "| T001 | `app-docs generate` | docs category の生成物が生成される。 |",
        "| T002 | `app-docs generate --check` | check 対応済み docs が最新なら exit 0 になる。 |",
        "| T003 | 古い `sequence_gen.md` | `generate_api_sequences --check` が exit 1 になる。 |",
        "| T004 | samples 不足 | `check_api_status_samples` が不足を検出する。 |",
        "| T005 | OpenAPI example 不一致 | samples と OpenAPI example の不一致を検出する。 |",
        "| T006 | router に直接 logger | archlint が拒否する。 |",
        "| T007 | SQL と generated queries 不一致 | app-codegen check 導入後に拒否する。 |",
        "| T008 | `*.sql` 以外の新規 SQL | archlint 導入後に拒否する。 |",
        "| T009 | generated pytest | `pytest --collect-only` に全 Case ID が出る。 |",
        "| T010 | Tool Registry | usage docs に全 ToolSpec が掲載される。 |",
        "",
        "## ToolSpec coverage",
        "",
        "| Tool | Golden | Check mode | Idempotency | Input validation |",
        "| :--- | :--- | :--- | :--- | :--- |",
    ]
    for spec in specs:
        check = "required" if spec.check_supported else "pending"
        lines.append(f"| `{spec.name}` | required | {check} | required | required |")
    return "\n".join(lines) + "\n"


def render_basic_design(spec: ToolSpec) -> str:
    lines = [
        GENERATED_COMMENT,
        "",
        f"# `{spec.name}` 基本設計",
        "",
        "## Tool名",
        "",
        f"`{spec.name}`",
        "",
        "## 日本語の説明",
        "",
        spec.summary,
        "",
        "## I/O",
        "",
        "| 種別 | 内容 |",
        "| :--- | :--- |",
        f"| 入力 | {md_join(spec.inputs)} |",
        f"| 出力 | {md_join(spec.outputs)} |",
        f"| check mode | {'対応' if spec.check_supported else '未対応'} |",
        f"| CI実行 | {'安全' if spec.safe_to_run_in_ci else '要個別判断'} |",
        "",
        "## 処理フロー",
        "",
        "1. 入力パス、設定、または repository state を読み取る。",
        "2. `ToolSpec` の責務に従って検査または生成対象を解析する。",
        "3. 出力ファイルまたは `stdout` に結果を反映する。",
        "4. `--check` 対応 tool は差分がある場合に non-zero exit を返す。",
        "",
        "## 依存関係",
        "",
        md_join(spec.depends_on),
        "",
        "## 使い方",
        "",
        "```bash",
        spec.command,
        "```",
        "",
    ]
    if spec.examples:
        lines.extend(["### 実行例", ""])
        for example in spec.examples:
            lines.extend(["```bash", example, "```", ""])
    return "\n".join(lines).rstrip() + "\n"


def render_unit_test_spec(spec: ToolSpec) -> str:
    check_expectation = (
        "`--check` 実行時に生成済み成果物との差分を検出する。"
        if spec.check_supported
        else "check mode 未対応であることを明示し、通常実行の成功を確認する。"
    )
    lines = [
        GENERATED_COMMENT,
        "",
        f"# `{spec.name}` unit-test仕様",
        "",
        "## 対象",
        "",
        f"`{spec.name}` の入力解析、生成/検査結果、check mode、冪等性を確認する。",
        "",
        "## テストケース",
        "",
        "| Case | 観点 | 期待結果 |",
        "| :--- | :--- | :--- |",
        (
            f"| UT001 | 正常系 | `{spec.command}` 相当の実行で期待する"
            "成果物または検査結果が得られる。 |"
        ),
        f"| UT002 | 入力 | 必須入力 {md_join(spec.inputs)} がテスト fixture から参照される。 |",
        f"| UT003 | 出力 | 期待出力 {md_join(spec.outputs)} の内容または通知を検証する。 |",
        f"| UT004 | check mode | {check_expectation} |",
        "| UT005 | 冪等性 | 同じ入力で再実行しても余分な差分を作らない。 |",
        "| UT006 | エラー | 不正または不足した入力を検出し、原因が分かる失敗を返す。 |",
        "",
        "## 推奨検証コマンド",
        "",
        "```bash",
        "uv run pytest tests/tools",
        "```",
        "",
    ]
    return "\n".join(lines)


def rendered_outputs(output_dir: Path = TOOLS_DOCS_DIR) -> dict[Path, str]:
    specs = all_tool_specs()
    outputs = {
        output_dir / "tools-list.gen.md": render_tools_list(specs),
        output_dir / "usage.gen.md": render_usage(specs),
        output_dir / "artifacts.gen.md": render_artifacts(specs),
        output_dir / "execution-flow.gen.md": render_execution_flow(specs),
        output_dir / "testcase-spec.gen.md": render_testcase_spec(specs),
    }
    for spec in specs:
        spec_dir = tool_dir(spec, output_dir)
        outputs[spec_dir / "basic-design_gen.md"] = render_basic_design(spec)
        outputs[spec_dir / "unit-test-spec_gen.md"] = render_unit_test_spec(spec)
    return outputs


def changed_outputs(rendered: dict[Path, str]) -> list[Path]:
    return [
        path
        for path, content in rendered.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]


def write_outputs(rendered: dict[Path, str]) -> None:
    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def generate(*, check: bool = False, output_dir: Path = TOOLS_DOCS_DIR) -> int:
    rendered = rendered_outputs(output_dir)
    changed = changed_outputs(rendered)
    if check:
        for path in changed:
            print(path.as_posix())
        return 1 if changed else 0
    write_outputs(rendered)
    return 0
