from __future__ import annotations

from pathlib import Path

from _pytest.capture import CaptureFixture
from _pytest.monkeypatch import MonkeyPatch

from tools.generate_api_list import (
    ApiListRow,
    build_arg_parser,
    collect_api_rows,
    generate,
    generate_from_openapi,
    main,
    render_api_list_markdown,
)

OPENAPI = {
    "paths": {
        "/projects": {
            "post": {
                "tags": ["projects"],
                "operationId": "createProject",
                "summary": "プロジェクトを作成する",
                "responses": {
                    "201": {"description": "Created"},
                    "403": {"description": "Forbidden"},
                    "500": {"description": "Internal Server Error"},
                },
            }
        },
        "/health": {
            "get": {
                "tags": ["system"],
                "operationId": "health_health_get",
                "summary": "Health",
                "responses": {"200": {"description": "OK"}},
            }
        },
    }
}


def test_collect_api_rows_outputs_compact_api_rows() -> None:
    rows = collect_api_rows(OPENAPI)

    assert rows == [
        ApiListRow(
            tag="system",
            method="GET",
            path="/health",
            summary="Health",
        ),
        ApiListRow(
            tag="projects",
            method="POST",
            path="/projects",
            summary="プロジェクトを作成する",
        ),
    ]


def test_render_api_list_markdown_outputs_table() -> None:
    rows = [
        ApiListRow(
            tag="projects",
            method="GET",
            path="/projects",
            summary="プロジェクト一覧を取得する",
        )
    ]

    rendered = render_api_list_markdown(rows)

    assert rendered == (
        "<!-- This file is generated by uv run python -m tools.generate_api_list. "
        "Do not edit manually. -->\n"
        "\n"
        "# API list\n"
        "\n"
        "| Tag | Method | Path | Summary |\n"
        "| --- | --- | --- | --- |\n"
        "| `projects` | `GET` | `/projects` | プロジェクト一覧を取得する |\n"
    )


def test_generate_from_openapi_writes_api_list(tmp_path: Path) -> None:
    output_path = tmp_path / "apis_list_gen.md"

    written = generate_from_openapi(OPENAPI, output_path)

    assert written == output_path
    assert output_path.read_text(encoding="utf-8").startswith(
        "<!-- This file is generated by uv run python -m tools.generate_api_list."
    )


def test_arg_parser_defaults_and_main_output(
    tmp_path: Path,
    monkeypatch: MonkeyPatch,
    capsys: CaptureFixture[str],
) -> None:
    default_args = build_arg_parser().parse_args([])

    assert default_args.output.as_posix() == "docs/spec/40.apis/apis_list_gen.md"

    output_path = tmp_path / "apis_list_gen.md"

    def generate_stub(output: Path) -> Path:
        output.write_text("generated\n", encoding="utf-8")
        return output

    monkeypatch.setattr("tools.generate_api_list.generate", generate_stub)

    main(["--output", str(output_path)])

    assert capsys.readouterr().out == f"Generated {output_path.as_posix()}.\n"
    assert output_path.read_text(encoding="utf-8") == "generated\n"


def test_generate_loads_openapi_and_implementation_paths(
    tmp_path: Path,
    monkeypatch: MonkeyPatch,
) -> None:
    output_path = tmp_path / "apis_list_gen.md"
    monkeypatch.setattr("tools.generate_api_list.load_fastapi_openapi", lambda: OPENAPI)

    written = generate(output_path)

    assert written == output_path
    rendered = output_path.read_text(encoding="utf-8")
    assert "| `projects` | `POST` | `/projects` | プロジェクトを作成する |" in rendered
