INSERT INTO project_cognito_clients (
    project_cognito_client_id,
    project_id,
    client_type,
    cognito_user_pool_id,
    app_client_id,
    app_client_name,
    generate_secret,
    client_secret_value_hash,
    client_secret_hash_key_version,
    client_secret_last4,
    allowed_oauth_flows,
    base_allowed_scopes,
    access_token_validity,
    access_token_unit,
    id_token_validity,
    id_token_unit,
    refresh_token_validity,
    refresh_token_unit,
    refresh_token_rotation_enabled,
    retry_grace_period_seconds,
    enable_token_revocation,
    last_synced_at,
    created_at,
    created_by,
    updated_at,
    updated_by,
    row_version
) VALUES (
    :project_cognito_client_id,
    :project_id,
    :client_type,
    :cognito_user_pool_id,
    :app_client_id,
    :app_client_name,
    :generate_secret,
    :client_secret_value_hash,
    :client_secret_hash_key_version,
    :client_secret_last4,
    CAST(:allowed_oauth_flows AS json),
    CAST(:base_allowed_scopes AS json),
    :access_token_validity,
    :access_token_unit,
    :id_token_validity,
    :id_token_unit,
    :refresh_token_validity,
    :refresh_token_unit,
    :refresh_token_rotation_enabled,
    :retry_grace_period_seconds,
    :enable_token_revocation,
    :now,
    :now,
    :actor_principal_id,
    :now,
    :actor_principal_id,
    1
)
RETURNING project_cognito_client_id;
