from __future__ import annotations

import argparse
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import sqlglot
from sqlglot import exp

from tools.generate_db_table_specs import Column, Table, parse_tables
from tools.generate_queries import (
    FieldSpec,
    QuerySpec,
    api_sql_dirs,
    parameter_name,
    parse_query_spec,
    placeholder_names,
    table_aliases,
)

GENERATED_COMMENT = (
    "<!-- This file is generated by uv run python -m tools.generate_query_specs. "
    "Do not edit manually. -->"
)


@dataclass(frozen=True)
class DocFieldSpec:
    field: FieldSpec
    source_table: str | None = None


@dataclass(frozen=True)
class SqlDocSpec:
    query: QuerySpec
    tables: tuple[str, ...]
    params: list[DocFieldSpec]
    rows: list[DocFieldSpec]
    conditions: tuple[str, ...]


@dataclass(frozen=True)
class ApiQueryDoc:
    domain: str
    api: str
    sql_specs: list[SqlDocSpec]


def parse_statements(sql: str) -> list[Any]:
    return [statement for statement in sqlglot.parse(sql, read="mysql") if statement is not None]


def sql_tables(statements: Iterable[Any]) -> tuple[str, ...]:
    tables: list[str] = []
    for statement in statements:
        for table in statement.find_all(exp.Table):
            if table.name and table.name not in tables:
                tables.append(table.name)
    return tuple(tables)


def ddl_column_index(tables: dict[str, Table]) -> dict[str, dict[str, Column]]:
    return {
        table_name: {column.name: column for column in table.columns}
        for table_name, table in tables.items()
    }


def unique_column_sources(tables: dict[str, Table]) -> dict[str, str]:
    sources: dict[str, list[str]] = {}
    for table in tables.values():
        for column in table.columns:
            sources.setdefault(column.name, []).append(table.name)
    return {name: matches[0] for name, matches in sources.items() if len(matches) == 1}


def resolve_column_table(
    column: exp.Column,
    aliases: dict[str, str],
    columns: dict[str, dict[str, Column]],
) -> str | None:
    if column.table:
        table = aliases.get(column.table, column.table)
        if column.name in columns.get(table, {}):
            return table
        return None

    alias_tables = set(aliases.values())
    if len(alias_tables) == 1:
        table = next(iter(alias_tables))
        if column.name in columns.get(table, {}):
            return table

    matches = [
        table_name
        for table_name, table_columns in columns.items()
        if column.name in table_columns
    ]
    return matches[0] if len(matches) == 1 else None


def expression_source_table(
    expression: Any,
    aliases: dict[str, str],
    columns: dict[str, dict[str, Column]],
) -> str | None:
    expression = expression.this if isinstance(expression, exp.Alias) else expression
    if isinstance(expression, exp.Column):
        return resolve_column_table(expression, aliases, columns)

    sources = {
        source
        for column in expression.find_all(exp.Column)
        if (source := resolve_column_table(column, aliases, columns)) is not None
    }
    return next(iter(sources)) if len(sources) == 1 else None


def row_source_tables(statements: Iterable[Any], tables: dict[str, Table]) -> list[str | None]:
    columns = ddl_column_index(tables)
    for statement in statements:
        aliases = table_aliases(statement)
        if isinstance(statement, exp.Select):
            return [
                expression_source_table(expression, aliases, columns)
                for expression in statement.expressions
            ]
        if isinstance(statement, (exp.Insert, exp.Update, exp.Delete)):
            returning = statement.args.get("returning")
            if returning is not None:
                return [
                    expression_source_table(expression, aliases, columns)
                    for expression in returning.expressions
                ]
    return []


def add_source(sources: dict[str, set[str]], parameter: str, source: str) -> None:
    sources.setdefault(parameter, set()).add(source)


def insert_param_sources(statement: exp.Insert) -> dict[str, set[str]]:
    if not isinstance(statement.this, exp.Schema):
        return {}

    target = statement.this.this
    if not isinstance(target, exp.Table):
        return {}

    values = statement.args.get("expression")
    if not isinstance(values, exp.Values) or not values.expressions:
        return {}

    first_tuple = values.expressions[0]
    if not isinstance(first_tuple, exp.Tuple):
        return {}

    sources: dict[str, set[str]] = {}
    for value in first_tuple.expressions:
        parameters = [
            name
            for placeholder in value.find_all(exp.Placeholder, exp.Parameter)
            if (name := parameter_name(placeholder)) is not None
        ]
        for parameter in parameters:
            add_source(sources, parameter, target.name)
    return sources


def update_param_sources(
    statement: exp.Update,
    columns: dict[str, dict[str, Column]],
) -> dict[str, set[str]]:
    aliases = table_aliases(statement)
    sources: dict[str, set[str]] = {}
    for assignment in statement.expressions:
        if not isinstance(assignment, exp.EQ) or not isinstance(assignment.this, exp.Column):
            continue
        source = resolve_column_table(assignment.this, aliases, columns)
        if source is None:
            continue
        for placeholder in assignment.expression.find_all(exp.Placeholder, exp.Parameter):
            if (name := parameter_name(placeholder)) is not None:
                add_source(sources, name, source)
    return sources


COMPARISON_EXPRESSIONS = (exp.EQ, exp.GT, exp.GTE, exp.LT, exp.LTE)


def expression_parameters(expression: Any) -> list[str]:
    return [
        name
        for placeholder in expression.find_all(exp.Placeholder, exp.Parameter)
        if (name := parameter_name(placeholder)) is not None
    ]


def comparison_param_sources(
    statement: Any,
    columns: dict[str, dict[str, Column]],
) -> dict[str, set[str]]:
    aliases = table_aliases(statement)
    sources: dict[str, set[str]] = {}
    for comparison in statement.find_all(*COMPARISON_EXPRESSIONS):
        left = comparison.this
        right = comparison.expression
        right_parameters = expression_parameters(right)
        left_parameters = expression_parameters(left)
        if isinstance(left, exp.Column) and right_parameters:
            if source := resolve_column_table(left, aliases, columns):
                for parameter in right_parameters:
                    add_source(sources, parameter, source)
        elif (
            isinstance(right, exp.Column)
            and left_parameters
            and (source := resolve_column_table(right, aliases, columns))
        ):
            for parameter in left_parameters:
                add_source(sources, parameter, source)
    return sources


def param_source_tables(
    sql: str,
    statements: Iterable[Any],
    tables: dict[str, Table],
) -> list[str | None]:
    columns = ddl_column_index(tables)
    unique_sources = unique_column_sources(tables)
    sources: dict[str, set[str]] = {}

    for statement in statements:
        if isinstance(statement, exp.Insert):
            sources.update(insert_param_sources(statement))
        elif isinstance(statement, exp.Update):
            sources.update(update_param_sources(statement, columns))
        sources.update(comparison_param_sources(statement, columns))

    resolved: list[str | None] = []
    for name in placeholder_names(sql):
        if name in sources:
            resolved.append(", ".join(sorted(sources[name])))
        else:
            resolved.append(unique_sources.get(name))
    return resolved


def doc_fields(fields: list[FieldSpec], sources: list[str | None]) -> list[DocFieldSpec]:
    return [
        DocFieldSpec(field=field, source_table=source)
        for field, source in zip(fields, sources, strict=False)
    ]


def expand_alias_node(node: Any, aliases: dict[str, str]) -> Any:
    if isinstance(node, exp.Column) and node.table in aliases:
        return exp.column(node.name, table=aliases[node.table])
    return node


def expanded_alias_expression(expression: Any, aliases: dict[str, str]) -> Any:
    def replace_alias(node: Any) -> Any:
        return expand_alias_node(node, aliases)

    return expression.copy().transform(replace_alias)


def expression_sql(expression: Any, aliases: dict[str, str] | None = None) -> str:
    if aliases:
        expression = expanded_alias_expression(expression, aliases)
    return " ".join(expression.sql(dialect="mysql").split())


def sql_conditions(statements: Iterable[Any]) -> tuple[str, ...]:
    conditions: list[str] = []
    for statement in statements:
        aliases = table_aliases(statement)
        for join in statement.find_all(exp.Join):
            on_expression = join.args.get("on")
            if on_expression is not None:
                conditions.append(f"JOIN ON {expression_sql(on_expression, aliases)}")

        where = statement.args.get("where")
        if isinstance(where, exp.Where):
            conditions.append(f"WHERE {expression_sql(where.this, aliases)}")

        having = statement.args.get("having")
        if isinstance(having, exp.Having):
            conditions.append(f"HAVING {expression_sql(having.this, aliases)}")
    return tuple(conditions)


def field_type(field: FieldSpec) -> str:
    if field.nullable and field.type_hint != "Any":
        return f"{field.type_hint} | None"
    return field.type_hint


def code_cell(value: str) -> str:
    return f"<code>{value.replace('|', '&#124;')}</code>"


def render_field_table(fields: list[DocFieldSpec], empty_label: str) -> list[str]:
    if not fields:
        return [empty_label]

    lines = [
        "| 取得元テーブル | 項目 | 型 | nullable |",
        "| --- | --- | --- | --- |",
    ]
    for doc_field in fields:
        field = doc_field.field
        source_table = doc_field.source_table or "-"
        nullable = "yes" if field.nullable else "no"
        lines.append(
            f"| {code_cell(source_table)} | {code_cell(field.name)} | "
            f"{code_cell(field_type(field))} | {nullable} |"
        )
    return lines


def render_list(values: tuple[str, ...], empty_label: str) -> list[str]:
    if not values:
        return [empty_label]
    return [f"- `{value}`" for value in values]


def render_sql_spec(spec: SqlDocSpec) -> list[str]:
    lines = [
        f"## {spec.query.sql_filename}",
        "",
        "### SQLの概要",
        "",
        spec.query.summary,
        "",
        "### 利用するテーブル",
        "",
        *render_list(spec.tables, "_なし_"),
        "",
        "### 引数",
        "",
        *render_field_table(spec.params, "_なし_"),
        "",
        "### 戻り値",
        "",
        *render_field_table(spec.rows, "_なし_"),
        "",
        "### 条件",
        "",
        *render_list(spec.conditions, "_なし_"),
    ]
    return lines


def render_query_markdown(doc: ApiQueryDoc) -> str:
    lines = [
        GENERATED_COMMENT,
        "",
        f"# {doc.api} query",
        "",
    ]
    for index, spec in enumerate(doc.sql_specs):
        if index > 0:
            lines.append("")
        lines.extend(render_sql_spec(spec))
        lines.append("")
    return "\n".join(lines)


def api_query_doc_from_sql_dir(
    sql_dir: Path,
    api_root: Path,
    tables: dict[str, Table],
) -> ApiQueryDoc:
    relative = sql_dir.parent.relative_to(api_root)
    domain, api = relative.parts
    sql_specs: list[SqlDocSpec] = []
    for sql_path in sorted(sql_dir.glob("*.sql")):
        sql = sql_path.read_text(encoding="utf-8")
        statements = parse_statements(sql)
        query = parse_query_spec(sql_path, tables)
        sql_specs.append(
            SqlDocSpec(
                query=query,
                tables=sql_tables(statements),
                params=doc_fields(query.params, param_source_tables(sql, statements, tables)),
                rows=doc_fields(query.rows, row_source_tables(statements, tables)),
                conditions=sql_conditions(statements),
            )
        )
    return ApiQueryDoc(domain=domain, api=api, sql_specs=sql_specs)


def output_path(doc: ApiQueryDoc, docs_root: Path) -> Path:
    return docs_root / doc.domain / doc.api / "query_gen.md"


def generate_query_specs(
    api_root: Path,
    docs_root: Path,
    ddl_path: Path,
) -> dict[Path, str]:
    tables = parse_tables(ddl_path.read_text(encoding="utf-8"))
    rendered: dict[Path, str] = {}
    for sql_dir in api_sql_dirs(api_root):
        doc = api_query_doc_from_sql_dir(sql_dir, api_root, tables)
        rendered[output_path(doc, docs_root)] = render_query_markdown(doc)
    return rendered


def changed_outputs(rendered: dict[Path, str]) -> list[Path]:
    changed: list[Path] = []
    for path, content in rendered.items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            changed.append(path)
    return changed


def write_outputs(rendered: dict[Path, str]) -> None:
    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def render_changed(paths: Iterable[Path]) -> str:
    return "\n".join(str(path) for path in paths)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate API SQL query Markdown specs.")
    parser.add_argument("--api-root", type=Path, default=Path("src/app/apis"))
    parser.add_argument("--docs-root", type=Path, default=Path("docs/spec/40.apis"))
    parser.add_argument("--ddl", type=Path, default=Path("src/db/ddl.sql"))
    parser.add_argument(
        "--check",
        action="store_true",
        help="Only check generated query specs are up to date.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    rendered = generate_query_specs(args.api_root, args.docs_root, args.ddl)
    changed = changed_outputs(rendered)
    if args.check:
        if changed:
            print(render_changed(changed))
            return 1
        return 0
    write_outputs(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
