from __future__ import annotations

import argparse
import csv
import io
from collections.abc import Mapping, Sequence
from pathlib import Path

from tools.e2e_models import (
    CASES,
    FACTORS,
    FLOW_ID,
    FLOW_STEPS,
    TARGET_CASES,
    E2eTargetCase,
    element_label,
    markdown_escape,
)
from tools.generation_io import check_outputs, write_outputs

GENERATED_COMMENT = (
    "<!-- This file is generated by uv run python -m tools.generate_e2e_case_list. "
    "Do not edit manually. -->"
)


def selected_elements_by_factor(case_id: str) -> dict[str, str]:
    for case in CASES:
        if case.case_id == case_id:
            return dict(case.selected)
    raise KeyError(case_id)


def target_case_projects(target_case: E2eTargetCase) -> str:
    projects = sorted({assertion.project_id for assertion in target_case.runtime_assertions})
    if projects:
        return "<br>".join(f"`{project}`" for project in projects)
    variants = " ".join(target_case.selected_variants)
    for project in ("project_A", "project_B", "project_C"):
        if project in variants:
            return f"`{project}`"
    return "-"


def target_case_apis(target_case: E2eTargetCase) -> str:
    apis = sorted(
        {
            assertion.api_id
            for assertion in target_case.runtime_assertions
            if assertion.expected == "allowed"
        }
    )
    if apis:
        return "<br>".join(f"`{api}`" for api in apis)
    variants = " ".join(target_case.selected_variants)
    matched_apis = [api for api in ("API_A", "API_B", "API_C") if api in variants]
    return "<br>".join(f"`{api}`" for api in matched_apis) if matched_apis else "-"


def render_target_case_rows() -> list[str]:
    lines = [
        "## 4. 対象別生成ケース一覧",
        "",
        "| ケースID | 目的 | Project | API | 選択Variant | Runtime期待 |",
        "|---|---|---|---|---|---|",
    ]
    for target_case in TARGET_CASES:
        variants = "<br>".join(f"`{variant}`" for variant in target_case.selected_variants)
        runtime_assertions = (
            "<br>".join(
                f"`{assertion.project_id}` / `{assertion.api_id}`: `{assertion.expected}`"
                for assertion in target_case.runtime_assertions
            )
            if target_case.runtime_assertions
            else "-"
        )
        lines.append(
            f"| `{target_case.case_id}` | {markdown_escape(target_case.title)} | "
            f"{target_case_projects(target_case)} | {target_case_apis(target_case)} | "
            f"{variants} | {runtime_assertions} |"
        )
    lines.append("")
    return lines


def render_case_list_markdown() -> str:
    lines = [
        GENERATED_COMMENT,
        "",
        f"# {FLOW_ID} e2e test factors",
        "",
        "## 0. 対象フロー",
        "",
        "| Step | Operation | Endpoint | Template |",
        "|---|---|---|---|",
    ]
    for step in FLOW_STEPS:
        endpoint = f"{step.method} {step.path}" if step.method != "GET" else f"GET {step.path}"
        lines.append(
            f"| `{step.step_id}` | `{step.operation}` | `{markdown_escape(endpoint)}` | "
            f"`{step.template}` |"
        )
    lines.extend(["", "## 1. 要因ごとの要素", ""])
    for factor in FACTORS:
        lines.extend(
            [
                f"### {factor.factor_id} {factor.title}",
                "",
                "| 要素ID | 既定要素 | 終端要素 | 期待観点 |",
                "|---|---:|---:|---|",
            ]
        )
        for element in factor.elements:
            lines.append(
                f"| `{element.element_id}` | {str(element.default).lower()} | "
                f"{str(element.terminal).lower()} | {markdown_escape(element.expected)} |"
            )
        lines.append("")
    lines.extend(
        [
            "## 2. 枝刈り規則",
            "",
            "| Rule ID | 条件 | 結果 | 理由 |",
            "|---|---|---|---|",
            "| `P001` | `terminal=true` | 後続要因をN/A化 | unit-testと同じprefix terminal方式 |",
            "| `P002` | `reject_api_access_request_result=success` | "
            "approve provisioningとRuntime成功を除外 | "
            "rejectはAWS変更しない |",
            "| `P003` | approve失敗 | Runtime API呼び出しを除外 | subscription/scopeが存在しない |",
            "| `P004` | terminal step/status/reasonが同一 | 等価ケースを統合 | "
            "E2Eの重複実行を避ける |",
            "",
            "## 3. 生成ケース一覧",
            "",
        ]
    )
    factor_columns = " | ".join(factor.factor_id for factor in FACTORS)
    factor_alignments = "|".join("---" for _ in FACTORS)
    lines.extend(
        [
            f"| ケースID | {factor_columns} | 種別 | Tier | 終了Step | シナリオ |",
            f"|---|{factor_alignments}|---|---|---|---|",
        ]
    )
    for case in CASES:
        selected = selected_elements_by_factor(case.case_id)
        selected_columns = " | ".join(
            markdown_escape(element_label(factor.factor_id, selected[factor.factor_id]))
            if factor.factor_id in selected
            else "-"
            for factor in FACTORS
        )
        lines.append(
            f"| `{case.case_id}` | {selected_columns} | `{case.kind}` | `{case.tier}` | "
            f"{markdown_escape(case.terminal_step)} | "
            f"[`cases/{case.filename}`](cases/{case.filename}) |"
        )
    lines.extend(["", *render_target_case_rows()])
    return "\n".join(lines)


def render_pruned_cases_csv() -> str:
    output = io.StringIO()
    writer = csv.writer(output, lineterminator="\n")
    writer.writerow(
        ["case_id", "kind", "tier", "terminal_step", "selected_factors", "scenario_path"]
    )
    for case in CASES:
        writer.writerow(
            [
                case.case_id,
                case.kind,
                case.tier,
                case.terminal_step,
                ";".join(f"{factor}.{element}" for factor, element in case.selected),
                f"cases/{case.filename}",
            ]
        )
    return output.getvalue()


def rendered_outputs(output_root: Path = Path("docs/spec/50.e2e")) -> Mapping[Path, str]:
    flow_root = output_root / FLOW_ID
    return {
        flow_root / "case-list_gen.md": render_case_list_markdown(),
        flow_root / "pruned-cases_gen.csv": render_pruned_cases_csv(),
    }


def generate(*, check: bool = False, output_root: Path = Path("docs/spec/50.e2e")) -> int:
    rendered = rendered_outputs(output_root)
    if check:
        return check_outputs(rendered)
    write_outputs(rendered)
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    return generate(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
