from __future__ import annotations

import argparse
import csv
import io
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import cast

import yaml

from tools.e2e_models import (
    COMPONENT_IDS,
    FLOW_ID,
    FLOW_STEPS,
    TARGET_CASES,
    E2eComponentVariant,
    E2eTargetCase,
    build_component_variants,
    markdown_escape,
)
from tools.generation_io import check_outputs, write_outputs

GENERATED_COMMENT = (
    "<!-- This file is generated by uv run python -m tools.generate_e2e_case_list. "
    "Do not edit manually. -->"
)

ELEMENT_KIND_LABELS = {
    "invariant": "不変条件",
    "action": "操作",
    "state": "状態",
    "data": "データ",
}

OPERATION_TYPE_LABELS = {
    "command": "コマンド",
    "query": "参照",
    "side_effect": "副作用",
    "evidence": "証跡確認",
}


def component_id(variant_id: str) -> str:
    return variant_id.split(".", maxsplit=1)[0]


def component_variants_by_id() -> dict[str, E2eComponentVariant]:
    return {variant.variant_id: variant for variant in build_component_variants()}


def target_case_projects(target_case: E2eTargetCase) -> str:
    projects = sorted({assertion.project_id for assertion in target_case.runtime_assertions})
    if projects:
        return "<br>".join(f"`{project}`" for project in projects)
    variants = " ".join(target_case.selected_variants)
    for project in ("project_A", "project_B", "project_C"):
        if project in variants:
            return f"`{project}`"
    return "-"


def target_case_apis(target_case: E2eTargetCase) -> str:
    apis = sorted(
        {
            assertion.api_id
            for assertion in target_case.runtime_assertions
            if assertion.expected == "allowed"
        }
    )
    if apis:
        return "<br>".join(f"`{api}`" for api in apis)
    for api in ("API_A", "API_B", "API_C"):
        if f".{api}." in target_case.goal_variant:
            return f"`{api}`"
    variants = " ".join(target_case.selected_variants)
    matched_apis = [api for api in ("API_A", "API_B", "API_C") if api in variants]
    return "<br>".join(f"`{api}`" for api in matched_apis) if matched_apis else "-"


def plain_target_case_projects(target_case: E2eTargetCase) -> str:
    projects = sorted({assertion.project_id for assertion in target_case.runtime_assertions})
    if projects:
        return " / ".join(target_label(project) for project in projects)
    variants = " ".join(target_case.selected_variants)
    matched_projects = [
        project for project in ("project_A", "project_B", "project_C") if project in variants
    ]
    if matched_projects:
        return " / ".join(target_label(project) for project in matched_projects)
    return "-"


def plain_target_case_apis(target_case: E2eTargetCase) -> str:
    apis = sorted(
        {
            assertion.api_id
            for assertion in target_case.runtime_assertions
            if assertion.expected == "allowed"
        }
    )
    if not apis:
        apis = [api for api in ("API_A", "API_B", "API_C") if api in target_case.goal_variant]
    if not apis:
        variants = " ".join(target_case.selected_variants)
        apis = [api for api in ("API_A", "API_B", "API_C") if api in variants]
    return " / ".join(target_label(api) for api in apis) if apis else "-"


def case_target_label(target_case: E2eTargetCase) -> str:
    project = plain_target_case_projects(target_case)
    api = plain_target_case_apis(target_case)
    if project != "-" and api != "-":
        return f"{project} x {api}"
    if project != "-":
        return project
    if api != "-":
        return api
    return "-"


def scenario_link(target_case: E2eTargetCase) -> str:
    return f"[詳細](cases/{target_case.filename})"


def flow_summary_for_variants(
    target_case: E2eTargetCase,
    *,
    variants: Mapping[str, E2eComponentVariant],
    titles: Mapping[str, Mapping[str, str]],
) -> str:
    actions: list[str] = []
    for variant_id in target_case.selected_variants:
        variant = parse_variant(variant_id, variants=variants)
        action_title = title_only(
            variant.action_id,
            titles[variant.component_id].get(f"action:{variant.action_id}"),
        )
        if not actions or actions[-1] != action_title:
            actions.append(action_title)
    return " -> ".join(markdown_escape(action) for action in actions) if actions else "-"


def connective_action(action: str) -> str:
    if action.endswith("する"):
        return f"{action[:-2]}し"
    if action.endswith("す"):
        return f"{action[:-1]}し"
    return action


def target_case_view(
    target_case: E2eTargetCase,
    *,
    variants: Mapping[str, E2eComponentVariant],
    titles: Mapping[str, Mapping[str, str]],
) -> tuple[str, str, str, str]:
    goal = parse_variant(target_case.goal_variant, variants=variants)
    component_titles = titles[goal.component_id]
    action = title_only(goal.action_id, component_titles.get(f"action:{goal.action_id}"))
    state = title_only(goal.state_id, component_titles.get(f"state:{goal.state_id}"))
    data = title_only(goal.data_id, component_titles.get(f"data:{goal.data_id}"))
    purpose = f"{case_target_label(target_case)}で{connective_action(action)}、{state}を確認する"
    evidence = state
    if target_case.runtime_assertions:
        evidence = "<br>".join(
            f"{target_label(assertion.api_id)} {assertion.expected}"
            for assertion in target_case.runtime_assertions
        )
    return (
        markdown_escape(purpose),
        markdown_escape(data),
        markdown_escape(state),
        evidence,
    )


def render_component_case_summary(
    *,
    variants: Mapping[str, E2eComponentVariant],
    titles: Mapping[str, Mapping[str, str]],
) -> list[str]:
    lines = [
        "## 5. Component coverage summary",
        "",
        "| Component | 件数 | 代表ケース | 主な観点 |",
        "|---|---:|---|---|",
    ]
    for component_id in COMPONENT_IDS:
        component_cases = [
            target_case
            for target_case in TARGET_CASES
            if target_case.goal_component == component_id
        ]
        states: list[str] = []
        for target_case in component_cases:
            variant = parse_variant(target_case.goal_variant, variants=variants)
            state = title_only(
                variant.state_id,
                titles[component_id].get(f"state:{variant.state_id}"),
            )
            if state not in states:
                states.append(state)
        representative = component_cases[0].case_id if component_cases else "-"
        lines.append(
            f"| `{component_id}` | {len(component_cases)} | `{representative}` | "
            f"{markdown_escape(', '.join(states) if states else '-')} |"
        )
    lines.append("")
    return lines


def render_project_api_matrices(
    *,
    variants: Mapping[str, E2eComponentVariant],
    titles: Mapping[str, Mapping[str, str]],
) -> list[str]:
    matrix_components = (
        "access_request_workflow",
        "review_decision",
        "runtime_authorization",
    )
    lines = [
        "## 6. Project x API matrix",
        "",
    ]
    for component_id in matrix_components:
        grouped: dict[str, dict[tuple[str, str], str]] = {}
        for target_case in TARGET_CASES:
            for variant_id in target_case.selected_variants:
                variant = parse_variant(variant_id, variants=variants)
                if variant.component_id != component_id:
                    continue
                if variant.project_id is None or variant.api_id is None:
                    continue
                state = title_only(
                    variant.state_id,
                    titles[component_id].get(f"state:{variant.state_id}"),
                )
                data = title_only(
                    variant.data_id,
                    titles[component_id].get(f"data:{variant.data_id}"),
                )
                key = f"{state} / {data}"
                grouped.setdefault(key, {}).setdefault(
                    (variant.project_id, variant.api_id),
                    target_case.case_id,
                )
        if not grouped:
            continue
        component_title = titles[component_id].get("component", component_id)
        lines.extend([f"### {component_id} {component_title}", ""])
        for key, case_ids in grouped.items():
            lines.extend(
                [
                    f"#### {markdown_escape(key)}",
                    "",
                    "| Project \\ API | API A | API B | API C |",
                    "|---|---|---|---|",
                ]
            )
            for project_id in ("project_A", "project_B", "project_C"):
                row = [target_label(project_id)]
                for api_id in ("API_A", "API_B", "API_C"):
                    case_id = case_ids.get((project_id, api_id))
                    row.append(f"`{case_id}`" if case_id else "-")
                lines.append(f"| {' | '.join(row)} |")
            lines.append("")
    return lines


def render_generated_case_rows(
    *,
    variants: Mapping[str, E2eComponentVariant],
    titles: Mapping[str, Mapping[str, str]],
) -> list[str]:
    lines = [
        "## 7. Cases by component",
        "",
    ]
    for component_id in COMPONENT_IDS:
        component_title = titles[component_id].get("component", component_id)
        lines.extend(
            [
                f"### {component_id} {component_title}",
                "",
                "| ID | 観点 | 対象 | データ | 処理概要 | 主なエビデンス | Link |",
                "|---|---|---|---|---|---|---|",
            ]
        )
        for target_case in TARGET_CASES:
            if target_case.goal_component != component_id:
                continue
            purpose, data, _state, evidence = target_case_view(
                target_case,
                variants=variants,
                titles=titles,
            )
            lines.append(
                f"| `{target_case.case_id}` | {purpose} | "
                f"{markdown_escape(case_target_label(target_case))} | {data} | "
                f"{flow_summary_for_variants(target_case, variants=variants, titles=titles)} | "
                f"{evidence} | {scenario_link(target_case)} |"
            )
        lines.append("")
    return lines


def render_variant_index_markdown(root: Path = Path("docs/spec/50.e2e")) -> str:
    source_root = source_flow_root(root)
    variants = component_variants_by_id()
    titles = component_element_titles(source_root)
    lines = [
        GENERATED_COMMENT,
        "",
        f"# {FLOW_ID} e2e variant index",
        "",
        "内部生成情報の確認用一覧。人間向けのケースレビューは "
        "[case-list_gen.md](case-list_gen.md) を参照する。",
        "",
        "| ケースID | Coverage Group | Goal Component | Goal Variant | "
        "Selected Variants | Runtime期待 | シナリオ |",
        "|---|---|---|---|---|---|---|",
    ]
    for target_case in TARGET_CASES:
        selected = "<br>".join(f"`{variant}`" for variant in target_case.selected_variants)
        runtime_assertions = (
            "<br>".join(
                f"`{assertion.project_id}` / `{assertion.api_id}`: `{assertion.expected}`"
                for assertion in target_case.runtime_assertions
            )
            if target_case.runtime_assertions
            else "-"
        )
        lines.append(
            f"| `{target_case.case_id}` | `{target_case.coverage_group}` | "
            f"`{target_case.goal_component}` | `{target_case.goal_variant}` | "
            f"{selected} | {runtime_assertions} | {scenario_link(target_case)} |"
        )
    lines.extend(["", "## 表示ラベル", ""])
    for component_id in COMPONENT_IDS:
        component_title = titles[component_id].get("component", component_id)
        lines.extend([f"### {component_id} {component_title}", ""])
        for variant in variants.values():
            if variant.component_id != component_id:
                continue
            data, action, state = variant_labels(variant, titles=titles)
            lines.append(f"- `{variant.variant_id}`: {data} / {action} / {state}")
        lines.append("")
    return "\n".join(lines)


def as_mapping(value: object) -> Mapping[str, object]:
    return cast(Mapping[str, object], value) if isinstance(value, dict) else {}


def as_sequence(value: object) -> Sequence[object]:
    return cast(Sequence[object], value) if isinstance(value, list | tuple) else ()


def scalar_text(value: object, default: str = "-") -> str:
    return value if isinstance(value, str) else default


def bool_text(value: object) -> str:
    if isinstance(value, bool):
        return "はい" if value else "いいえ"
    return "-"


def load_yaml(path: Path) -> Mapping[str, object]:
    loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
    return as_mapping(loaded)


def source_flow_root(root: Path) -> Path:
    flow_root = root / FLOW_ID
    if (flow_root / "components").exists():
        return flow_root
    return Path("docs/spec/50.e2e") / FLOW_ID


def label_with_title(element_id: str | None, title: str | None = None) -> str:
    if element_id is None:
        return "-"
    if title:
        return f"{element_id}: {title}"
    return element_id


def title_only(element_id: str | None, title: str | None = None) -> str:
    if element_id is None:
        return "-"
    return title or element_id


def target_label(target_id: str) -> str:
    if target_id.startswith("project_"):
        return target_id.replace("project_", "Project ")
    if target_id.startswith("API_"):
        return target_id.replace("API_", "API ")
    return target_id.replace("_", " ")


def yaml_titles(items: Sequence[object]) -> dict[str, str]:
    titles: dict[str, str] = {}
    for item in items:
        item_map = as_mapping(item)
        item_id = scalar_text(item_map.get("id"))
        if item_id != "-":
            titles[item_id] = scalar_text(item_map.get("title"))
    return titles


def component_element_titles(flow_root: Path) -> dict[str, dict[str, str]]:
    titles: dict[str, dict[str, str]] = {}
    for component_id in COMPONENT_IDS:
        component_root = flow_root / "components" / component_id
        component_doc = load_yaml(component_root / "component.manual.yaml")
        component = as_mapping(component_doc.get("component"))
        actions_doc = load_yaml(component_root / "actions.manual.yaml")
        states_doc = load_yaml(component_root / "states.manual.yaml")
        data_doc = load_yaml(component_root / "data.manual.yaml")
        titles[component_id] = {
            "component": scalar_text(component.get("title")),
            **{
                f"action:{item_id}": title
                for item_id, title in yaml_titles(as_sequence(actions_doc.get("actions"))).items()
            },
            **{
                f"state:{item_id}": title
                for item_id, title in yaml_titles(as_sequence(states_doc.get("states"))).items()
            },
            **{
                f"data:{item_id}": title
                for item_id, title in yaml_titles(
                    as_sequence(data_doc.get("data_profiles"))
                ).items()
            },
        }
    return titles


def variant_labels(
    variant: E2eComponentVariant,
    *,
    titles: Mapping[str, Mapping[str, str]],
) -> tuple[str, str, str]:
    component_titles = titles[variant.component_id]
    targets = [
        target_label(target)
        for target in (variant.project_id, variant.api_id)
        if target is not None
    ]
    data_title = title_only(variant.data_id, component_titles.get(f"data:{variant.data_id}"))
    data_label = " / ".join((*targets, data_title)) if targets else data_title
    return (
        data_label,
        title_only(
            variant.action_id,
            component_titles.get(f"action:{variant.action_id}"),
        ),
        title_only(variant.state_id, component_titles.get(f"state:{variant.state_id}")),
    )


def parse_variant(
    variant_id: str,
    *,
    variants: Mapping[str, E2eComponentVariant],
) -> E2eComponentVariant:
    if variant_id in variants:
        return variants[variant_id]
    prefix, data_id = variant_id.split("@", maxsplit=1)
    parts = prefix.split(".")
    component_id = parts[0]
    action_id = parts[1]
    target_ids = parts[2:-1]
    state_id = parts[-1]
    project_id = next(
        (target_id for target_id in target_ids if target_id.startswith("project_")),
        None,
    )
    api_id = next((target_id for target_id in target_ids if target_id.startswith("API_")), None)
    return E2eComponentVariant(
        component_id,
        action_id,
        project_id,
        api_id,
        state_id,
        data_id,
        True,
    )


def selected_variants_by_component(
    target_case: E2eTargetCase,
    *,
    variants: Mapping[str, E2eComponentVariant],
) -> dict[str, E2eComponentVariant]:
    selected: dict[str, E2eComponentVariant] = {}
    for variant_id in target_case.selected_variants:
        variant = parse_variant(variant_id, variants=variants)
        selected[variant.component_id] = variant
    return selected


def render_coverage_summary(variants: Sequence[E2eComponentVariant]) -> list[str]:
    lines = [
        "## 2. Coverage summary",
        "",
        "| Component | Variants | Covered variants | Goal cases | Coverage |",
        "|---|---:|---:|---:|---:|",
    ]
    covered_variants = {
        variant_id
        for target_case in TARGET_CASES
        for variant_id in target_case.selected_variants
    }
    for component in COMPONENT_IDS:
        component_variants = [
            variant.variant_id for variant in variants if variant.component_id == component
        ]
        covered = [variant for variant in component_variants if variant in covered_variants]
        component_cases = [
            target_case
            for target_case in TARGET_CASES
            if target_case.goal_component == component
        ]
        coverage = (
            f"{len(covered) / len(component_variants) * 100:.1f}%"
            if component_variants
            else "-"
        )
        lines.append(
            f"| `{component}` | {len(component_variants)} | {len(covered)} | "
            f"{len(component_cases)} | {coverage} |"
        )
    lines.append("")
    return lines


def render_component_sections(flow_root: Path) -> list[str]:
    lines = ["## 3. コンポーネントごとの要素", ""]
    for component_id in COMPONENT_IDS:
        component_root = flow_root / "components" / component_id
        component_doc = load_yaml(component_root / "component.manual.yaml")
        component = as_mapping(component_doc.get("component"))
        lines.extend(
            [
                f"### {component_id} {scalar_text(component.get('title'))}",
                "",
                "| 種別 | ID | タイトル | 補足 |",
                "|---|---|---|---|",
            ]
        )
        for invariant in as_sequence(component_doc.get("business_invariants")):
            invariant_map = as_mapping(invariant)
            lines.append(
                f"| {ELEMENT_KIND_LABELS['invariant']} | "
                f"`{scalar_text(invariant_map.get('id'))}` | - | "
                f"{markdown_escape(scalar_text(invariant_map.get('text')))} |"
            )
        actions_doc = load_yaml(component_root / "actions.manual.yaml")
        for action in as_sequence(actions_doc.get("actions")):
            action_map = as_mapping(action)
            operation_type = scalar_text(action_map.get("operation_type"))
            detail = (
                f"操作種別={OPERATION_TYPE_LABELS.get(operation_type, operation_type)}, "
                f"既定状態={scalar_text(action_map.get('default_result'))}"
            )
            lines.append(
                f"| {ELEMENT_KIND_LABELS['action']} | "
                f"`{scalar_text(action_map.get('id'))}` | "
                f"{markdown_escape(scalar_text(action_map.get('title')))} | "
                f"{markdown_escape(detail)} |"
            )
        states_doc = load_yaml(component_root / "states.manual.yaml")
        for state in as_sequence(states_doc.get("states")):
            state_map = as_mapping(state)
            continue_flow = state_map.get("continue_flow")
            detail = f"後続継続={bool_text(continue_flow)}"
            lines.append(
                f"| {ELEMENT_KIND_LABELS['state']} | "
                f"`{scalar_text(state_map.get('id'))}` | "
                f"{markdown_escape(scalar_text(state_map.get('title')))} | {detail} |"
            )
        data_doc = load_yaml(component_root / "data.manual.yaml")
        for data_profile in as_sequence(data_doc.get("data_profiles")):
            data_map = as_mapping(data_profile)
            tags = ", ".join(
                str(tag) for tag in as_sequence(data_map.get("tags")) if isinstance(tag, str)
            )
            lines.append(
                f"| {ELEMENT_KIND_LABELS['data']} | "
                f"`{scalar_text(data_map.get('id'))}` | "
                f"{markdown_escape(scalar_text(data_map.get('title')))} | "
                f"{markdown_escape(tags or '-')} |"
            )
        lines.append("")
    return lines


def render_case_list_markdown(root: Path = Path("docs/spec/50.e2e")) -> str:
    source_root = source_flow_root(root)
    variants = component_variants_by_id()
    titles = component_element_titles(source_root)
    lines = [
        GENERATED_COMMENT,
        "",
        f"# {FLOW_ID} e2e case list",
        "",
        "## 0. 読み方",
        "",
        "- Component coverage: 各論理コンポーネントのvariant coverage。",
        "- Matrix: Project x API の組み合わせ確認。",
        "- 内部variant一覧は [case-variant-index_gen.md](case-variant-index_gen.md) を参照。",
        "",
        "## 1. 対象フロー",
        "",
        "| Step | Operation | Endpoint | Template |",
        "|---|---|---|---|",
    ]
    for step in FLOW_STEPS:
        endpoint = f"{step.method} {step.path}" if step.method != "GET" else f"GET {step.path}"
        lines.append(
            f"| `{step.step_id}` | `{step.operation}` | `{markdown_escape(endpoint)}` | "
            f"`{step.template}` |"
        )
    lines.extend(
        [
            "",
            *render_coverage_summary(tuple(variants.values())),
            *render_component_sections(source_root),
        ]
    )
    lines.extend(
        [
            "## 4. 枝刈り規則",
            "",
            "| Rule ID | 条件 | 結果 | 理由 |",
            "|---|---|---|---|",
            "| `P001` | `continue_flow=false` の失敗系 | Project/APIを代表targetへ集約 | "
            "データ種別や対象差で期待結果が変わらない失敗系を重複実行しない |",
            "| `P002` | 後続ケースの前提variantとして検証される正常系 | "
            "単独goal caseを生成しない | "
            "API公開、Project作成、利用申請、承認成功はRuntime等の後続ケースに内包する |",
            "| `P003` | 前提component stateが成立しないgoal variant | ケース生成対象から除外 | "
            "到達不能な手順をE2Eケースに含めない |",
            "| `P004` | 同じcomponent stateを証明する同一evidence | ケース内で重複排除 | "
            "レビュー対象のエビデンス表を簡潔に保つ |",
            "",
        ]
    )
    lines.extend(
        [
            *render_component_case_summary(variants=variants, titles=titles),
            *render_project_api_matrices(variants=variants, titles=titles),
            *render_generated_case_rows(variants=variants, titles=titles),
            "## 8. Appendix",
            "",
            "- 内部variant一覧: [case-variant-index_gen.md](case-variant-index_gen.md)",
            "- CSV: [pruned-cases_gen.csv](pruned-cases_gen.csv)",
            "",
        ]
    )
    return "\n".join(lines)


def render_pruned_cases_csv(root: Path = Path("docs/spec/50.e2e")) -> str:
    output = io.StringIO()
    writer = csv.writer(output, lineterminator="\n")
    variants = component_variants_by_id()
    titles = component_element_titles(source_flow_root(root))
    writer.writerow(
        [
            "case_id",
            *[
                f"{component_id}[{kind}]"
                for component_id in COMPONENT_IDS
                for kind in ("データ", "操作", "状態")
            ],
        ]
    )
    for target_case in TARGET_CASES:
        selected = selected_variants_by_component(target_case, variants=variants)
        component_columns: list[str] = []
        for component_id in COMPONENT_IDS:
            variant = selected.get(component_id)
            if variant is None:
                component_columns.extend(("-", "-", "-"))
                continue
            component_columns.extend(variant_labels(variant, titles=titles))
        writer.writerow(
            [
                target_case.case_id,
                *component_columns,
            ]
        )
    return output.getvalue()


def rendered_outputs(output_root: Path = Path("docs/spec/50.e2e")) -> Mapping[Path, str]:
    flow_root = output_root / FLOW_ID
    return {
        flow_root / "case-list_gen.md": render_case_list_markdown(output_root),
        flow_root / "case-variant-index_gen.md": render_variant_index_markdown(output_root),
        flow_root / "pruned-cases_gen.csv": render_pruned_cases_csv(output_root),
    }


def generate(*, check: bool = False, output_root: Path = Path("docs/spec/50.e2e")) -> int:
    rendered = rendered_outputs(output_root)
    if check:
        return check_outputs(rendered)
    write_outputs(rendered)
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    return generate(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
