from __future__ import annotations

import argparse
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import sqlglot
from sqlglot import exp

from tools.generate_db_table_specs import Column, Table, parse_tables
from tools.generate_queries import (
    FieldSpec,
    QuerySpec,
    api_sql_dirs,
    parameter_name,
    parse_query_spec,
    placeholder_names,
    table_aliases,
)

GENERATED_COMMENT = (
    "<!-- This file is generated by uv run python -m tools.generate_query_specs. "
    "Do not edit manually. -->"
)


@dataclass(frozen=True)
class ColumnRef:
    table_name: str
    column: Column


@dataclass(frozen=True)
class DocFieldSpec:
    field: FieldSpec
    column_refs: tuple[ColumnRef, ...] = ()


@dataclass(frozen=True)
class SqlDocSpec:
    query: QuerySpec
    tables: tuple[str, ...]
    params: list[DocFieldSpec]
    rows: list[DocFieldSpec]
    conditions: tuple[str, ...]


@dataclass(frozen=True)
class ApiQueryDoc:
    domain: str
    api: str
    sql_specs: list[SqlDocSpec]


def parse_statements(sql: str) -> list[Any]:
    return [statement for statement in sqlglot.parse(sql, read="mysql") if statement is not None]


def sql_tables(statements: Iterable[Any]) -> tuple[str, ...]:
    tables: list[str] = []
    for statement in statements:
        for table in statement.find_all(exp.Table):
            if table.name and table.name not in tables:
                tables.append(table.name)
    return tuple(tables)


def ddl_column_index(tables: dict[str, Table]) -> dict[str, dict[str, Column]]:
    return {
        table_name: {column.name: column for column in table.columns}
        for table_name, table in tables.items()
    }


def unique_column_refs(tables: dict[str, Table]) -> dict[str, ColumnRef]:
    refs: dict[str, list[ColumnRef]] = {}
    for table in tables.values():
        for column in table.columns:
            refs.setdefault(column.name, []).append(ColumnRef(table.name, column))
    return {name: matches[0] for name, matches in refs.items() if len(matches) == 1}


def resolve_column_ref(
    column: exp.Column,
    aliases: dict[str, str],
    columns: dict[str, dict[str, Column]],
) -> ColumnRef | None:
    if column.table:
        table = aliases.get(column.table, column.table)
        if resolved_column := columns.get(table, {}).get(column.name):
            return ColumnRef(table, resolved_column)
        return None

    alias_tables = set(aliases.values())
    if len(alias_tables) == 1:
        table = next(iter(alias_tables))
        if resolved_column := columns.get(table, {}).get(column.name):
            return ColumnRef(table, resolved_column)

    matches = [
        ColumnRef(table_name, table_columns[column.name])
        for table_name, table_columns in columns.items()
        if column.name in table_columns
    ]
    return matches[0] if len(matches) == 1 else None


def expression_column_refs(
    expression: Any,
    aliases: dict[str, str],
    columns: dict[str, dict[str, Column]],
) -> tuple[ColumnRef, ...]:
    expression = expression.this if isinstance(expression, exp.Alias) else expression
    if isinstance(expression, exp.Column):
        ref = resolve_column_ref(expression, aliases, columns)
        return (ref,) if ref is not None else ()
    return ()


def row_column_refs(
    statements: Iterable[Any],
    tables: dict[str, Table],
) -> list[tuple[ColumnRef, ...]]:
    columns = ddl_column_index(tables)
    for statement in statements:
        aliases = table_aliases(statement)
        if isinstance(statement, exp.Select):
            return [
                expression_column_refs(expression, aliases, columns)
                for expression in statement.expressions
            ]
        if isinstance(statement, (exp.Insert, exp.Update, exp.Delete)):
            returning = statement.args.get("returning")
            if returning is not None:
                return [
                    expression_column_refs(expression, aliases, columns)
                    for expression in returning.expressions
                ]
    return []


def source_column_ref(
    table_name: str,
    column_name: str,
    columns: dict[str, dict[str, Column]],
) -> ColumnRef | None:
    if column := columns.get(table_name, {}).get(column_name):
        return ColumnRef(table_name, column)
    return None


def add_column_ref(
    refs: dict[str, list[ColumnRef]],
    parameter: str,
    ref: ColumnRef,
) -> None:
    parameter_refs = refs.setdefault(parameter, [])
    key = (ref.table_name, ref.column.name)
    if all((existing.table_name, existing.column.name) != key for existing in parameter_refs):
        parameter_refs.append(ref)


def insert_param_refs(
    statement: exp.Insert,
    columns: dict[str, dict[str, Column]],
) -> dict[str, list[ColumnRef]]:
    if not isinstance(statement.this, exp.Schema):
        return {}

    target = statement.this.this
    if not isinstance(target, exp.Table):
        return {}

    values = statement.args.get("expression")
    if not isinstance(values, exp.Values) or not values.expressions:
        return {}

    first_tuple = values.expressions[0]
    if not isinstance(first_tuple, exp.Tuple):
        return {}

    insert_columns = [column.name for column in statement.this.expressions]
    refs: dict[str, list[ColumnRef]] = {}
    for column_name, value in zip(insert_columns, first_tuple.expressions, strict=False):
        ref = source_column_ref(target.name, column_name, columns)
        if ref is None:
            continue
        parameters = [
            name
            for placeholder in value.find_all(exp.Placeholder, exp.Parameter)
            if (name := parameter_name(placeholder)) is not None
        ]
        for parameter in parameters:
            add_column_ref(refs, parameter, ref)
    return refs


def update_param_refs(
    statement: exp.Update,
    columns: dict[str, dict[str, Column]],
) -> dict[str, list[ColumnRef]]:
    aliases = table_aliases(statement)
    refs: dict[str, list[ColumnRef]] = {}
    for assignment in statement.expressions:
        if not isinstance(assignment, exp.EQ) or not isinstance(assignment.this, exp.Column):
            continue
        ref = resolve_column_ref(assignment.this, aliases, columns)
        if ref is None:
            continue
        for placeholder in assignment.expression.find_all(exp.Placeholder, exp.Parameter):
            if (name := parameter_name(placeholder)) is not None:
                add_column_ref(refs, name, ref)
    return refs


COMPARISON_EXPRESSIONS = (exp.EQ, exp.GT, exp.GTE, exp.LT, exp.LTE)


def expression_parameters(expression: Any) -> list[str]:
    return [
        name
        for placeholder in expression.find_all(exp.Placeholder, exp.Parameter)
        if (name := parameter_name(placeholder)) is not None
    ]


def comparison_param_refs(
    statement: Any,
    columns: dict[str, dict[str, Column]],
) -> dict[str, list[ColumnRef]]:
    aliases = table_aliases(statement)
    refs: dict[str, list[ColumnRef]] = {}
    for comparison in statement.find_all(*COMPARISON_EXPRESSIONS):
        left = comparison.this
        right = comparison.expression
        right_parameters = expression_parameters(right)
        left_parameters = expression_parameters(left)
        if isinstance(left, exp.Column) and right_parameters:
            if ref := resolve_column_ref(left, aliases, columns):
                for parameter in right_parameters:
                    add_column_ref(refs, parameter, ref)
        elif (
            isinstance(right, exp.Column)
            and left_parameters
            and (ref := resolve_column_ref(right, aliases, columns))
        ):
            for parameter in left_parameters:
                add_column_ref(refs, parameter, ref)
    return refs


def merge_param_refs(
    refs: dict[str, list[ColumnRef]],
    additional_refs: dict[str, list[ColumnRef]],
) -> None:
    for parameter, parameter_refs in additional_refs.items():
        for ref in parameter_refs:
            add_column_ref(refs, parameter, ref)


def param_column_refs(
    sql: str,
    statements: Iterable[Any],
    tables: dict[str, Table],
) -> list[tuple[ColumnRef, ...]]:
    columns = ddl_column_index(tables)
    unique_refs = unique_column_refs(tables)
    refs: dict[str, list[ColumnRef]] = {}

    for statement in statements:
        if isinstance(statement, exp.Insert):
            merge_param_refs(refs, insert_param_refs(statement, columns))
        elif isinstance(statement, exp.Update):
            merge_param_refs(refs, update_param_refs(statement, columns))
        merge_param_refs(refs, comparison_param_refs(statement, columns))

    resolved: list[tuple[ColumnRef, ...]] = []
    for name in placeholder_names(sql):
        if name in refs:
            resolved.append(tuple(refs[name]))
        elif name in unique_refs:
            resolved.append((unique_refs[name],))
        else:
            resolved.append(())
    return resolved


def doc_fields(
    fields: list[FieldSpec],
    column_refs: list[tuple[ColumnRef, ...]],
) -> list[DocFieldSpec]:
    return [
        DocFieldSpec(field=field, column_refs=refs)
        for field, refs in zip(fields, column_refs, strict=False)
    ]


def expand_alias_node(node: Any, aliases: dict[str, str]) -> Any:
    if isinstance(node, exp.Column) and node.table in aliases:
        return exp.column(node.name, table=aliases[node.table])
    return node


def expanded_alias_expression(expression: Any, aliases: dict[str, str]) -> Any:
    def replace_alias(node: Any) -> Any:
        return expand_alias_node(node, aliases)

    return expression.copy().transform(replace_alias)


def expression_sql(expression: Any, aliases: dict[str, str] | None = None) -> str:
    if aliases:
        expression = expanded_alias_expression(expression, aliases)
    return " ".join(expression.sql(dialect="mysql").split())


def sql_conditions(statements: Iterable[Any]) -> tuple[str, ...]:
    conditions: list[str] = []
    for statement in statements:
        aliases = table_aliases(statement)
        for join in statement.find_all(exp.Join):
            on_expression = join.args.get("on")
            if on_expression is not None:
                conditions.append(f"JOIN ON {expression_sql(on_expression, aliases)}")

        where = statement.args.get("where")
        if isinstance(where, exp.Where):
            conditions.append(f"WHERE {expression_sql(where.this, aliases)}")

        having = statement.args.get("having")
        if isinstance(having, exp.Having):
            conditions.append(f"HAVING {expression_sql(having.this, aliases)}")
    return tuple(conditions)


def field_type(field: FieldSpec) -> str:
    if field.nullable and field.type_hint != "Any":
        return f"{field.type_hint} | None"
    return field.type_hint


def ref_label(ref: ColumnRef) -> str:
    return f"{ref.table_name}.{ref.column.name}"


def joined_ref_values(refs: tuple[ColumnRef, ...], value: str) -> str:
    values: list[str] = []
    for ref in refs:
        if value == "label":
            values.append(ref_label(ref))
        elif value == "type":
            values.append(ref.column.data_type)
        elif value == "comment":
            values.append(ref.column.comment or "-")
        elif value == "nullable":
            values.append("yes" if ref.column.nullable else "no")
    if not values:
        return "-"
    return "<br>".join(values)


def display_type(field: FieldSpec, refs: tuple[ColumnRef, ...]) -> str:
    if refs:
        return joined_ref_values(refs, "type")
    return field_type(field)


def display_nullable(field: FieldSpec, refs: tuple[ColumnRef, ...]) -> str:
    if refs:
        return joined_ref_values(refs, "nullable")
    return "yes" if field.nullable else "no"


def code_cell(value: str) -> str:
    return f"<code>{value.replace('|', '&#124;')}</code>"


def text_cell(value: str) -> str:
    return value.replace("|", "&#124;").replace("\n", " ")


def render_code_lines(value: str) -> str:
    return "<br>".join(code_cell(part) for part in value.split("<br>"))


def render_field_table(fields: list[DocFieldSpec], empty_label: str) -> list[str]:
    if not fields:
        return [empty_label]

    lines = [
        "| DDLカラム | 項目 | 日本語名 | 型 | nullable |",
        "| --- | --- | --- | --- | --- |",
    ]
    for doc_field in fields:
        field = doc_field.field
        refs = doc_field.column_refs
        lines.append(
            f"| {render_code_lines(joined_ref_values(refs, 'label'))} | "
            f"{code_cell(field.name)} | "
            f"{text_cell(joined_ref_values(refs, 'comment'))} | "
            f"{render_code_lines(display_type(field, refs))} | "
            f"{display_nullable(field, refs)} |"
        )
    return lines


def render_list(values: tuple[str, ...], empty_label: str) -> list[str]:
    if not values:
        return [empty_label]
    return [f"- `{value}`" for value in values]


def operation_label(operation: str) -> str:
    labels = {
        "select": "SELECT",
        "insert": "INSERT",
        "update": "UPDATE",
        "delete": "DELETE",
    }
    return labels.get(operation, operation.upper())


def render_sql_spec(spec: SqlDocSpec) -> list[str]:
    lines = [
        f"## {spec.query.sql_filename}",
        "",
        "### SQL種別",
        "",
        f"`{operation_label(spec.query.operation)}`",
        "",
        "### SQLの概要",
        "",
        spec.query.summary,
        "",
        "### 利用するテーブル",
        "",
        *render_list(spec.tables, "_なし_"),
        "",
        "### 引数",
        "",
        *render_field_table(spec.params, "_なし_"),
        "",
        "### 戻り値",
        "",
        *render_field_table(spec.rows, "_なし_"),
        "",
        "### 条件",
        "",
        *render_list(spec.conditions, "_なし_"),
    ]
    return lines


def render_query_markdown(doc: ApiQueryDoc) -> str:
    lines = [
        GENERATED_COMMENT,
        "",
        f"# {doc.api} query",
        "",
    ]
    for index, spec in enumerate(doc.sql_specs):
        if index > 0:
            lines.append("")
        lines.extend(render_sql_spec(spec))
        lines.append("")
    return "\n".join(lines)


def api_query_doc_from_sql_dir(
    sql_dir: Path,
    api_root: Path,
    tables: dict[str, Table],
) -> ApiQueryDoc:
    relative = sql_dir.parent.relative_to(api_root)
    domain, api = relative.parts
    sql_specs: list[SqlDocSpec] = []
    for sql_path in sorted(sql_dir.glob("*.sql")):
        sql = sql_path.read_text(encoding="utf-8")
        statements = parse_statements(sql)
        query = parse_query_spec(sql_path, tables)
        sql_specs.append(
            SqlDocSpec(
                query=query,
                tables=sql_tables(statements),
                params=doc_fields(query.params, param_column_refs(sql, statements, tables)),
                rows=doc_fields(query.rows, row_column_refs(statements, tables)),
                conditions=sql_conditions(statements),
            )
        )
    return ApiQueryDoc(domain=domain, api=api, sql_specs=sql_specs)


def output_path(doc: ApiQueryDoc, docs_root: Path) -> Path:
    return docs_root / doc.domain / doc.api / "query_gen.md"


def generate_query_specs(
    api_root: Path,
    docs_root: Path,
    ddl_path: Path,
) -> dict[Path, str]:
    tables = parse_tables(ddl_path.read_text(encoding="utf-8"))
    rendered: dict[Path, str] = {}
    for sql_dir in api_sql_dirs(api_root):
        doc = api_query_doc_from_sql_dir(sql_dir, api_root, tables)
        rendered[output_path(doc, docs_root)] = render_query_markdown(doc)
    return rendered


def changed_outputs(rendered: dict[Path, str]) -> list[Path]:
    changed: list[Path] = []
    for path, content in rendered.items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            changed.append(path)
    return changed


def write_outputs(rendered: dict[Path, str]) -> None:
    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def render_changed(paths: Iterable[Path]) -> str:
    return "\n".join(str(path) for path in paths)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate API SQL query Markdown specs.")
    parser.add_argument("--api-root", type=Path, default=Path("src/app/apis"))
    parser.add_argument("--docs-root", type=Path, default=Path("docs/spec/40.apis"))
    parser.add_argument("--ddl", type=Path, default=Path("src/db/ddl.sql"))
    parser.add_argument(
        "--check",
        action="store_true",
        help="Only check generated query specs are up to date.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    rendered = generate_query_specs(args.api_root, args.docs_root, args.ddl)
    changed = changed_outputs(rendered)
    if args.check:
        if changed:
            print(render_changed(changed))
            return 1
        return 0
    write_outputs(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
