from __future__ import annotations

import argparse
import ast
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path

from tools.generate_api_sequences import (
    api_dirs,
    api_error_response_call,
    condition_label_from_description,
    endpoint_function,
    endpoint_operation_id,
    endpoint_route_method,
    endpoint_route_path,
    error_response_for_router_error_call,
    http_status_code,
    keyword_value,
    literal_string,
)

GENERATED_COMMENT = (
    "<!-- This file is generated by uv run python -m tools.generate_api_unit_test_factors. "
    "Do not edit manually. -->"
)


@dataclass(frozen=True)
class FactorElement:
    key: str
    name: str
    expected: str
    terminal: bool = False


@dataclass(frozen=True)
class TestFactor:
    factor_id: str
    kind: str
    title: str
    source: str
    elements: tuple[FactorElement, ...]


@dataclass(frozen=True)
class ApiUnitTestFactors:
    domain: str
    api: str
    operation_id: str
    method: str
    path: str
    success_status: int
    factors: tuple[TestFactor, ...]


type TestCase = tuple[FactorElement | None, ...]


def markdown_escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def expression_text(node: ast.AST) -> str:
    return ast.unparse(node)


def exception_type_text(node: ast.AST | None) -> str:
    if node is None:
        return "Exception"
    return ast.unparse(node)


def exception_type_texts(
    node: ast.AST | None,
    exception_aliases: dict[str, tuple[str, ...]],
) -> tuple[str, ...]:
    if node is None:
        return ("Exception",)
    if isinstance(node, ast.Tuple):
        return tuple(exception_type_text(element) for element in node.elts)
    if isinstance(node, ast.Name) and node.id in exception_aliases:
        return exception_aliases[node.id]
    return (exception_type_text(node),)


def exception_element_key(exception_type: str) -> str:
    normalized = "".join(
        character.lower() if character.isalnum() else "-" for character in exception_type
    ).strip("-")
    return f"raised-{normalized or 'exception'}"


def exception_aliases(api_root: Path) -> dict[str, tuple[str, ...]]:
    router_errors_path = api_root / "router_errors.py"
    if not router_errors_path.exists():
        return {}
    tree = ast.parse(
        router_errors_path.read_text(encoding="utf-8"),
        filename=str(router_errors_path),
    )
    aliases: dict[str, tuple[str, ...]] = {}
    for node in tree.body:
        target: ast.expr | None = None
        value: ast.expr | None = None
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            target = node.targets[0]
            value = node.value
        elif isinstance(node, ast.AnnAssign):
            target = node.target
            value = node.value
        if not isinstance(target, ast.Name) or not isinstance(value, ast.Tuple):
            continue
        aliases[target.id] = tuple(exception_type_text(element) for element in value.elts)
    return aliases


def router_error_response_expectation(
    *,
    operation_id: str,
    exception_type: str,
    base_summary: str | None,
) -> str | None:
    expectations = {
        "ApiFunctionError": (500, "forced router error", "router_api_function_error"),
        "ExternalApiError": (502, "external service request failed", "router_external_api_error"),
        "HTTPException": (400, "forced http exception", "router_http_exception"),
    }
    if exception_type not in expectations:
        return None
    status_code, detail, message_suffix = expectations[exception_type]
    expected = f"HTTP {status_code} error response: {detail}"
    if base_summary is None:
        return expected
    summary = base_summary.replace(
        "Routerで捕捉した例外により",
        f"Routerで捕捉した{exception_type}により",
    )
    return (
        f"{expected}<br>log message_id: {operation_id}.{message_suffix}<br>log summary: {summary}"
    )


def router_error_base_summary_from_body(nodes: Iterable[ast.stmt]) -> str | None:
    for node in nodes:
        for child in ast.walk(node):
            if not isinstance(child, ast.Call):
                continue
            function = child.func
            if not isinstance(function, ast.Name) or function.id != "router_error_summary":
                continue
            if not child.args:
                continue
            summary = literal_string(child.args[0])
            if summary:
                return summary
    return None


def clean_comment(value: str) -> str:
    return value.removeprefix("#").strip()


def comment_for_line(source_lines: list[str], lineno: int) -> str | None:
    if not 1 <= lineno <= len(source_lines):
        return None
    current_line = source_lines[lineno - 1]
    if "#" in current_line:
        inline_comment = current_line.split("#", 1)[1].strip()
        if inline_comment:
            return inline_comment

    comments: list[str] = []
    for line in reversed(source_lines[: lineno - 1]):
        stripped = line.strip()
        if not stripped:
            if comments:
                break
            continue
        if not stripped.startswith("#"):
            break
        comments.append(clean_comment(stripped))
    comments.reverse()
    if comments:
        return " ".join(comments)
    return None


def literal_summary_from_body(nodes: Iterable[ast.stmt]) -> str | None:
    for node in nodes:
        for child in ast.walk(node):
            if not isinstance(child, ast.Call):
                continue
            for keyword in child.keywords:
                if keyword.arg != "summary":
                    continue
                summary = literal_string(keyword.value)
                if summary:
                    return summary
    return None


def function_docstrings(functions_path: Path) -> dict[str, str]:
    if not functions_path.exists():
        return {}
    tree = ast.parse(functions_path.read_text(encoding="utf-8"), filename=str(functions_path))
    descriptions: dict[str, str] = {}
    for node in tree.body:
        if not isinstance(node, ast.AsyncFunctionDef | ast.FunctionDef):
            continue
        docstring = ast.get_docstring(node)
        if docstring:
            descriptions[node.name] = " ".join(docstring.strip().split())
    return descriptions


def api_function_names(node: ast.AST) -> list[str]:
    names: list[str] = []
    for child in ast.walk(node):
        call = child.value if isinstance(child, ast.Await) else child
        if not isinstance(call, ast.Call):
            continue
        function = call.func
        if not isinstance(function, ast.Attribute):
            continue
        if not isinstance(function.value, ast.Name) or function.value.id != "api_functions":
            continue
        if function.attr not in names:
            names.append(function.attr)
    return names


def condition_description_from_docstring(
    node: ast.AST,
    descriptions: dict[str, str],
) -> str | None:
    names = api_function_names(node)
    if not names:
        return None
    description = descriptions.get(names[0])
    if description is None:
        return None
    negated = isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.Not)
    return condition_label_from_description(description, negated=negated)


def factor_description(
    *,
    node: ast.stmt,
    condition_node: ast.AST | None = None,
    source_lines: list[str],
    body: Iterable[ast.stmt],
    fallback: str,
    function_descriptions: dict[str, str],
) -> str:
    return (
        comment_for_line(source_lines, node.lineno)
        or literal_summary_from_body(body)
        or condition_description_from_docstring(condition_node or node, function_descriptions)
        or fallback
    )


def response_summary_from_return(node: ast.stmt) -> str | None:
    if not isinstance(node, ast.Return):
        return None
    call = api_error_response_call(node)
    if call is not None:
        status = http_status_code(call.args[0]) if call.args else None
        detail = literal_string(call.args[1]) if len(call.args) > 1 else None
        if status is not None and detail:
            return f"HTTP {status} error response: {detail}"
        if status is not None:
            return f"HTTP {status} error response"
        return "error response"
    if error_response_for_router_error_call(node) is not None:
        return "router error response"
    return None


def log_expectation_from_body(nodes: Iterable[ast.stmt]) -> tuple[str, str] | None:
    for node in nodes:
        for child in ast.walk(node):
            if not isinstance(child, ast.Call):
                continue
            function = child.func
            if not isinstance(function, ast.Attribute):
                continue
            if function.attr not in {"warning", "error"}:
                continue
            if not isinstance(function.value, ast.Name) or function.value.id != "ops_logger":
                continue
            if not child.args:
                continue
            message_id = literal_string(child.args[0])
            summary = literal_string(keyword_value(child, "summary"))
            if message_id and summary:
                return message_id, summary
    return None


def append_log_expectation(summary: str, nodes: Iterable[ast.stmt]) -> str:
    log_expectation = log_expectation_from_body(nodes)
    if log_expectation is None:
        return summary
    message_id, log_summary = log_expectation
    return f"{summary}<br>log message_id: {message_id}<br>log summary: {log_summary}"


def first_response_summary(nodes: Iterable[ast.stmt]) -> str | None:
    for node in nodes:
        if summary := response_summary_from_return(node):
            return summary
        for child in ast.iter_child_nodes(node):
            if isinstance(child, ast.stmt) and (summary := response_summary_from_return(child)):
                return summary
    return None


def branch_expected(nodes: list[ast.stmt], fallback: str) -> str:
    response_summary = first_response_summary(nodes)
    if response_summary is None:
        return fallback
    return append_log_expectation(response_summary, nodes)


def branch_is_terminal(nodes: list[ast.stmt]) -> bool:
    return first_response_summary(nodes) is not None


def if_factor(
    node: ast.If,
    index: int,
    source_lines: list[str],
    function_descriptions: dict[str, str],
) -> TestFactor:
    expression = expression_text(node.test)
    description = factor_description(
        node=node,
        condition_node=node.test,
        source_lines=source_lines,
        body=node.body,
        fallback=expression,
        function_descriptions=function_descriptions,
    )
    return TestFactor(
        factor_id=f"F{index:02d}",
        kind="条件分岐",
        title=f"条件分岐 L{node.lineno}: {description}",
        source=expression,
        elements=(
            FactorElement(
                key="true",
                name="成立",
                expected=branch_expected(node.body, "条件成立側の処理を実行する。"),
                terminal=branch_is_terminal(node.body),
            ),
            FactorElement(
                key="false",
                name="不成立",
                expected=branch_expected(node.orelse, "条件不成立側または後続処理を継続する。"),
                terminal=branch_is_terminal(node.orelse),
            ),
        ),
    )


def except_factor(
    handler: ast.ExceptHandler,
    index: int,
    operation_id: str,
    source_lines: list[str],
    exception_aliases: dict[str, tuple[str, ...]],
) -> TestFactor:
    exception_type = exception_type_text(handler.type)
    exception_types = exception_type_texts(handler.type, exception_aliases)
    router_error_base_summary = router_error_base_summary_from_body(handler.body)
    description = (
        comment_for_line(source_lines, handler.lineno)
        or literal_summary_from_body(handler.body)
        or router_error_base_summary
        or exception_type
    )
    return TestFactor(
        factor_id=f"F{index:02d}",
        kind="例外処理",
        title=f"例外処理 L{handler.lineno}: {description}",
        source=exception_type,
        elements=(
            FactorElement(
                key="normal",
                name="発生しない",
                expected="try bodyを継続し、このexcept handlerへ遷移しない。",
            ),
            *(
                FactorElement(
                    key=exception_element_key(exception_type),
                    name=exception_type,
                    expected=(
                        router_error_response_expectation(
                            operation_id=operation_id,
                            exception_type=exception_type,
                            base_summary=router_error_base_summary,
                        )
                        or branch_expected(handler.body, "例外を捕捉してエラー処理を実行する。")
                    ),
                    terminal=branch_is_terminal(handler.body),
                )
                for exception_type in exception_types
            ),
        ),
    )


def endpoint_factors(
    function: ast.AsyncFunctionDef | ast.FunctionDef,
    source_lines: list[str],
    function_descriptions: dict[str, str],
    exception_aliases: dict[str, tuple[str, ...]],
) -> tuple[TestFactor, ...]:
    factors: list[TestFactor] = []

    class Visitor(ast.NodeVisitor):
        def visit_If(self, node: ast.If) -> None:
            factors.append(if_factor(node, len(factors) + 1, source_lines, function_descriptions))
            self.generic_visit(node)

        def visit_Try(self, node: ast.Try) -> None:
            for child in node.body:
                self.visit(child)
            for handler in node.handlers:
                factors.append(
                    except_factor(
                        handler,
                        len(factors) + 1,
                        endpoint_operation_id(function),
                        source_lines,
                        exception_aliases,
                    )
                )
                for child in handler.body:
                    self.visit(child)
            for child in [*node.orelse, *node.finalbody]:
                self.visit(child)

    for statement in function.body:
        Visitor().visit(statement)
    return tuple(factors)


def api_unit_test_factors_from_dir(api_dir: Path, api_root: Path) -> ApiUnitTestFactors:
    router_path = api_dir / "router.py"
    source = router_path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(router_path))
    function = endpoint_function(tree)
    descriptions = function_docstrings(api_dir / "functions.py")
    relative = api_dir.relative_to(api_root)
    domain, api = relative.parts
    return ApiUnitTestFactors(
        domain=domain,
        api=api,
        operation_id=endpoint_operation_id(function),
        method=endpoint_route_method(function),
        path=endpoint_route_path(function),
        success_status=endpoint_success_status(function),
        factors=endpoint_factors(
            function,
            source.splitlines(),
            descriptions,
            exception_aliases(api_root),
        ),
    )


def endpoint_success_status(function: ast.AsyncFunctionDef | ast.FunctionDef) -> int:
    for decorator in function.decorator_list:
        if not isinstance(decorator, ast.Call):
            continue
        if status_code := http_status_code(keyword_value(decorator, "status_code")):
            return status_code
    return 200


def product_cases(factors: tuple[TestFactor, ...]) -> list[TestCase]:
    if not factors:
        return []
    cases: list[TestCase] = []

    def append_cases(index: int, selected: list[FactorElement | None]) -> None:
        if index >= len(factors):
            cases.append(tuple(selected))
            return
        factor = factors[index]
        for element in factor.elements:
            next_selected = [*selected, element]
            if element.terminal:
                cases.append(tuple([*next_selected, *([None] * (len(factors) - index - 1))]))
                continue
            append_cases(index + 1, next_selected)

    append_cases(0, [])
    return cases


def render_factor_elements_section(factors: tuple[TestFactor, ...]) -> list[str]:
    lines = ["## 1. 要因ごとの要素", ""]
    if not factors:
        lines.extend(["_条件分岐または例外処理の要因はありません。_", ""])
        return lines
    for factor in factors:
        lines.extend(
            [
                f"### {factor.factor_id} {factor.kind}",
                "",
                f"- 対象: {factor.title}",
                f"- AST: `{markdown_escape(factor.source)}`",
                "",
                "| 要素ID | 要素 | 期待観点 |",
                "| --- | --- | --- |",
            ]
        )
        for element in factor.elements:
            lines.append(
                f"| `{factor.factor_id}-{element.key}` | "
                f"{markdown_escape(element.name)} | {markdown_escape(element.expected)} |"
            )
        lines.append("")
    return lines


def render_product_cases_section(factors: tuple[TestFactor, ...]) -> list[str]:
    lines = ["## 2. 直積したテストケース一覧", ""]
    cases = product_cases(factors)
    if not cases:
        lines.extend(["_直積対象の要因はありません。_", ""])
        return lines
    header = ["| Case ID |", *[f" {factor.factor_id} |" for factor in factors]]
    separator = ["| --- |", *[" --- |" for _factor in factors]]
    lines.append("".join(header))
    lines.append("".join(separator))
    for index, case in enumerate(cases, start=1):
        cells = [f"| `TC{index:03d}` |"]
        for element in case:
            cells.append(f" `{markdown_escape(element.name)}` |" if element else " - |")
        lines.append("".join(cells))
    lines.append("")
    return lines


def render_test_details_section(
    factors: tuple[TestFactor, ...],
    *,
    success_status: int,
) -> list[str]:
    lines = ["## 3. テスト詳細", ""]
    cases = product_cases(factors)
    if not cases:
        lines.extend(["_テスト詳細はありません。_", ""])
        return lines
    for index, case in enumerate(cases, start=1):
        lines.extend(
            [
                f"### TC{index:03d}",
                "",
                "| 要因 | 要素 | 期待観点 |",
                "| --- | --- | --- |",
            ]
        )
        for factor, element in zip(factors, case, strict=True):
            if element is None:
                continue
            lines.append(
                f"| `{factor.factor_id}` {markdown_escape(factor.title)} | "
                f"{markdown_escape(element.name)} | {markdown_escape(element.expected)} |"
            )
        if not any(element is not None and element.terminal for element in case):
            lines.append(f"| API正常応答 | 正常 | HTTP {success_status} success response |")
        lines.append("")
    return lines


def render_unit_test_markdown(doc: ApiUnitTestFactors) -> str:
    lines = [
        GENERATED_COMMENT,
        "",
        f"# {doc.api} unit test factors",
        "",
        f"- Operation: `{doc.operation_id}`",
        f"- Endpoint: `{doc.method} {doc.path}`",
        "",
        *render_factor_elements_section(doc.factors),
        *render_product_cases_section(doc.factors),
        *render_test_details_section(doc.factors, success_status=doc.success_status),
    ]
    return "\n".join(lines).rstrip() + "\n"


def output_path(doc: ApiUnitTestFactors, docs_root: Path) -> Path:
    return docs_root / doc.domain / doc.api / "unit-test_gen.md"


def generate_unit_test_factors(api_root: Path, docs_root: Path) -> dict[Path, str]:
    rendered: dict[Path, str] = {}
    for directory in api_dirs(api_root):
        doc = api_unit_test_factors_from_dir(directory, api_root)
        rendered[output_path(doc, docs_root)] = render_unit_test_markdown(doc)
    return rendered


def changed_outputs(rendered: dict[Path, str]) -> list[Path]:
    changed: list[Path] = []
    for path, content in rendered.items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            changed.append(path)
    return changed


def write_outputs(rendered: dict[Path, str]) -> None:
    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def render_changed(paths: Iterable[Path]) -> str:
    return "\n".join(str(path) for path in paths)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate API unit test factor specs from router AST."
    )
    parser.add_argument("--api-root", type=Path, default=Path("src/app/apis"))
    parser.add_argument("--docs-root", type=Path, default=Path("docs/spec/40.apis"))
    parser.add_argument(
        "--check",
        action="store_true",
        help="Only check generated unit test factor files are up to date.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    rendered = generate_unit_test_factors(args.api_root, args.docs_root)
    changed = changed_outputs(rendered)
    if args.check:
        if changed:
            print(render_changed(changed))
            return 1
        return 0
    write_outputs(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
