from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

from tools.generate_openapi_if_specs import (
    JsonObject,
    as_list,
    iter_operations,
    load_fastapi_openapi,
    markdown_escape,
)
from tools.generation_io import check_outputs, write_outputs

GENERATED_COMMENT = (
    "<!-- This file is generated by uv run python -m tools.generate_api_list. "
    "Do not edit manually. -->"
)


@dataclass(frozen=True)
class ApiListRow:
    tag: str
    method: str
    path: str
    summary: str


def operation_tag(operation: JsonObject) -> str:
    tags = as_list(operation.get("tags"))
    return str(tags[0]) if tags else "-"


def operation_summary(operation: JsonObject) -> str:
    return str(operation.get("summary") or operation.get("description") or "-")


def collect_api_rows(openapi: JsonObject) -> list[ApiListRow]:
    rows: list[ApiListRow] = []
    for path, method, operation in iter_operations(openapi):
        rows.append(
            ApiListRow(
                tag=operation_tag(operation),
                method=method.upper(),
                path=path,
                summary=operation_summary(operation),
            )
        )
    return rows


def render_api_list_markdown(rows: list[ApiListRow]) -> str:
    lines = [
        GENERATED_COMMENT,
        "",
        "# API list",
        "",
        "| Tag | Method | Path | Summary |",
        "| --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{markdown_escape(row.tag)}`",
                    f"`{markdown_escape(row.method)}`",
                    f"`{markdown_escape(row.path)}`",
                    markdown_escape(row.summary),
                ]
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def generate_from_openapi(openapi: JsonObject, output_path: Path) -> Path:
    rendered = render_output_from_openapi(openapi, output_path)
    write_outputs(rendered)
    return output_path


def render_output_from_openapi(openapi: JsonObject, output_path: Path) -> dict[Path, str]:
    rows = collect_api_rows(openapi)
    return {output_path: render_api_list_markdown(rows)}


def generate(output_path: Path) -> Path:
    rendered = render_output(output_path)
    write_outputs(rendered)
    return output_path


def render_output(output_path: Path) -> dict[Path, str]:
    return render_output_from_openapi(load_fastapi_openapi(), output_path)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate API list markdown from FastAPI OpenAPI.")
    parser.add_argument("--output", type=Path, default=Path("docs/spec/40.apis/apis_list_gen.md"))
    parser.add_argument("--check", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    rendered = render_output(args.output)
    if args.check:
        return check_outputs(rendered)
    write_outputs(rendered)
    print(f"Generated {args.output.as_posix()}.")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
