from __future__ import annotations

import argparse
from collections.abc import Mapping, Sequence
from pathlib import Path

from tools.e2e_models import (
    API_TARGETS,
    CASES,
    FACTORS,
    FLOW_ID,
    PROJECT_OPERATION_DATA,
    PROJECT_TARGETS,
    TARGET_CASES,
    E2eFactor,
    E2eTarget,
    binding_expectations,
    binding_steps,
    data_for_factor,
    selected_variant_id,
    target_variant_id,
    variant_id,
)
from tools.generation_io import check_outputs, write_outputs

GENERATED_COMMENT = (
    "# This file is generated by uv run python -m tools.generate_e2e_factor_yaml. "
    "Do not edit manually."
)


def yaml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_factor_yaml(factor: E2eFactor) -> str:
    lines: list[str] = [
        GENERATED_COMMENT,
        "schema_version: 1",
        "",
        "factor:",
        f"  id: {factor.factor_id}",
        f"  slug: {factor.slug}",
        f"  title: {yaml_quote(factor.title)}",
        f"  category: {factor.category}",
        f"  order: {factor.order}",
        f"  owner_step: {factor.owner_step}",
        "  generated_from:",
        "    - type: e2e_flow",
        f"      path: docs/spec/50.e2e/{FLOW_ID}/flow.manual.yaml",
        "",
        "elements:",
    ]
    for element in factor.elements:
        lines.extend(
            [
                f"  - id: {element.element_id}",
                f"    label: {yaml_quote(element.label)}",
                f"    default: {str(element.default).lower()}",
                f"    terminal: {str(element.terminal).lower()}",
                "    expected:",
                f"      summary: {yaml_quote(element.expected)}",
            ]
        )
    lines.append("")
    lines.append("constraints:")
    if factor.requires:
        lines.append("  requires:")
        lines.extend(f"    - {requirement}" for requirement in factor.requires)
    else:
        lines.append("  requires: []")
    lines.extend(
        [
            "",
            "pruning:",
            "  after_terminal: true",
            "  equivalent_if_same_terminal_step: true",
            "",
        ]
    )
    return "\n".join(lines)


def render_effective_factors_yaml(factors: Sequence[E2eFactor]) -> str:
    lines: list[str] = [
        GENERATED_COMMENT,
        "schema_version: 1",
        f"flow: {FLOW_ID}",
        "factors:",
    ]
    for factor in factors:
        lines.append(f"  - id: {factor.factor_id}")
        lines.append(f"    slug: {factor.slug}")
        lines.append(f"    title: {yaml_quote(factor.title)}")
        lines.append(f"    owner_step: {factor.owner_step}")
        lines.append("    elements:")
        for element in factor.elements:
            flags: list[str] = []
            if element.default:
                flags.append("default")
            if element.terminal:
                flags.append("terminal")
            suffix = f" # {', '.join(flags)}" if flags else ""
            lines.append(f"      - {element.element_id}{suffix}")
    lines.append("")
    return "\n".join(lines)


def render_effective_factor_matrix_yaml(factors: Sequence[E2eFactor]) -> str:
    lines: list[str] = [
        GENERATED_COMMENT,
        "schema_version: 1",
        f"flow: {FLOW_ID}",
        "factors:",
    ]
    for factor in factors:
        lines.append(f"  {factor.slug}:")
        lines.append("    variants:")
        for element in factor.elements:
            for data in data_for_factor(factor.factor_id):
                lines.extend(
                    [
                        f"      - id: {variant_id(factor, element, data)}",
                        f"        factor: {factor.slug}",
                        f"        factor_id: {factor.factor_id}",
                        f"        element: {element.element_id}",
                        f"        data: {data.data_id}",
                        f"        continue_flow: {str(not element.terminal).lower()}",
                    ]
                )
                if data.tags:
                    lines.append("        data_tags:")
                    lines.extend(f"          - {tag}" for tag in data.tags)
                lines.append("        steps:")
                lines.extend(f"          - {step}" for step in binding_steps(factor, element))
                lines.append("        expectations:")
                lines.extend(
                    f"          - {expectation}"
                    for expectation in binding_expectations(factor, element)
                )
    lines.append("")
    return "\n".join(lines)


def render_effective_step_bindings_yaml(factors: Sequence[E2eFactor]) -> str:
    lines: list[str] = [
        GENERATED_COMMENT,
        "schema_version: 1",
        f"flow: {FLOW_ID}",
        "bindings:",
    ]
    for factor in factors:
        for element in factor.elements:
            for data in data_for_factor(factor.factor_id):
                binding_id = f"{factor.slug}.{element.element_id}@{data.data_id}"
                lines.extend(
                    [
                        f"  - id: {binding_id}",
                        "    when:",
                        f"      factor: {factor.slug}",
                        f"      element: {element.element_id}",
                        f"      data: {data.data_id}",
                        "    steps:",
                    ]
                )
                lines.extend(
                    f"      - id: {step}"
                    for step in binding_steps(factor, element)
                )
                lines.append("    expectations:")
                lines.extend(
                    f"      - id: {expectation}"
                    for expectation in binding_expectations(factor, element)
                )
    lines.append("")
    return "\n".join(lines)


def render_tags(tags: Sequence[str], *, indent: str) -> list[str]:
    if not tags:
        return []
    return [f"{indent}tags:", *(f"{indent}  - {tag}" for tag in tags)]


def render_target_yaml(targets: Sequence[E2eTarget], *, indent: str) -> list[str]:
    lines: list[str] = []
    for target in targets:
        lines.extend(
            [
                f"{indent}- id: {target.target_id}",
                f"{indent}  title: {yaml_quote(target.title)}",
            ]
        )
        lines.extend(render_tags(target.tags, indent=f"{indent}  "))
    return lines


def render_effective_target_variants_yaml() -> str:
    lines: list[str] = [
        GENERATED_COMMENT,
        "schema_version: 1",
        f"flow: {FLOW_ID}",
        "targets:",
        "  projects:",
        *render_target_yaml(PROJECT_TARGETS, indent="    "),
        "  apis:",
        *render_target_yaml(API_TARGETS, indent="    "),
        "variant_groups:",
        "  project:",
        "    variants:",
    ]
    project_create_data = PROJECT_OPERATION_DATA[0]
    project_update_data = PROJECT_OPERATION_DATA[1]
    project_failure_data = PROJECT_OPERATION_DATA[2]
    for project in PROJECT_TARGETS:
        create_success_id = target_variant_id(
            "project", project, None, "create", "success", project_create_data
        )
        update_success_id = target_variant_id(
            "project", project, None, "update", "success", project_update_data
        )
        create_failure_id = target_variant_id(
            "project",
            project,
            None,
            "create",
            "duplicate_project_code",
            project_failure_data,
        )
        lines.extend(
            [
                f"      - id: {create_success_id}",
                f"        project: {project.target_id}",
                "        operation: create",
                "        result: success",
                "        data: create_default",
                "        source_factor: F020",
                "        source_element: success",
                "        continue_flow: true",
                "        steps:",
                "          - post_projects",
                "        expectations:",
                "          - project.project_search_hit",
                f"      - id: {update_success_id}",
                f"        project: {project.target_id}",
                "        operation: update",
                "        result: success",
                "        data: update_redirect_url",
                "        source_factor: F023",
                "        source_element: success",
                "        continue_flow: true",
                "        steps:",
                "          - patch_project_public_client",
                "        expectations:",
                "          - project.redirect_url_updated",
                f"      - id: {create_failure_id}",
                f"        project: {project.target_id}",
                "        operation: create",
                "        result: failure",
                "        data: invalid_project_code",
                "        source_factor: F020",
                "        source_element: duplicate_project_code",
                "        continue_flow: false",
                "        steps:",
                "          - post_projects",
                "        expectations:",
                "          - project.operation_failed",
                "          - common.no_later_steps",
            ]
        )
    lines.extend(["  access_request:", "    variants:"])
    for project in PROJECT_TARGETS:
        for api in API_TARGETS:
            for data in data_for_factor("F030"):
                for element in ("success", "duplicate_pending", "already_subscribed"):
                    access_request_id = target_variant_id(
                        "access_request", project, api, "apply", element, data
                    )
                    lines.extend(
                        [
                            f"      - id: {access_request_id}",
                            f"        project: {project.target_id}",
                            f"        api: {api.target_id}",
                            "        operation: apply",
                            f"        result: {'success' if element == 'success' else 'failure'}",
                            f"        data: {data.data_id}",
                            "        source_factor: F030",
                            f"        source_element: {element}",
                            f"        continue_flow: {str(element == 'success').lower()}",
                            "        steps:",
                        ]
                    )
                    steps = ("post_api_access_requests",)
                    if element == "duplicate_pending":
                        steps = ("setup_pending_access_request", "post_api_access_requests")
                    elif element == "already_subscribed":
                        steps = ("setup_active_subscription", "post_api_access_requests")
                    lines.extend(f"          - {step}" for step in steps)
                    lines.extend(
                        [
                            "        expectations:",
                            f"          - access_request.{element}",
                        ]
                    )
                    if element != "success":
                        lines.append("          - common.no_later_steps")
    lines.extend(["  review:", "    variants:"])
    for project in PROJECT_TARGETS:
        for api in API_TARGETS:
            for data in data_for_factor("F040"):
                for element in ("success", "non_reviewer", "not_pending"):
                    approve_id = target_variant_id(
                        "review", project, api, "approve", element, data
                    )
                    lines.extend(
                        [
                            f"      - id: {approve_id}",
                            f"        project: {project.target_id}",
                            f"        api: {api.target_id}",
                            "        operation: approve",
                            f"        result: {'success' if element == 'success' else 'failure'}",
                            f"        data: {data.data_id}",
                            "        source_factor: F040",
                            f"        source_element: {element}",
                            f"        continue_flow: {str(element == 'success').lower()}",
                            "        steps:",
                        ]
                    )
                    steps = ("approve_api_access_request",)
                    if element == "not_pending":
                        steps = ("setup_reviewed_access_request", "approve_api_access_request")
                    lines.extend(f"          - {step}" for step in steps)
                    lines.extend(
                        [
                            "        expectations:",
                            f"          - review.approve_{element}",
                        ]
                    )
                    if element == "success":
                        lines.extend(
                            [
                                "          - runtime.current_api_callable",
                                "          - runtime.other_apis_not_callable",
                            ]
                        )
                    else:
                        lines.append("          - runtime.all_apis_not_callable")
            for data in data_for_factor("F041"):
                for element in ("success", "non_reviewer"):
                    reject_id = target_variant_id(
                        "review", project, api, "reject", element, data
                    )
                    lines.extend(
                        [
                            f"      - id: {reject_id}",
                            f"        project: {project.target_id}",
                            f"        api: {api.target_id}",
                            "        operation: reject",
                            f"        result: {'success' if element == 'success' else 'failure'}",
                            f"        data: {data.data_id}",
                            "        source_factor: F041",
                            f"        source_element: {element}",
                            f"        continue_flow: {str(element == 'success').lower()}",
                            "        steps:",
                            "          - reject_api_access_request",
                            "        expectations:",
                            f"          - review.reject_{element}",
                            "          - runtime.all_apis_not_callable",
                        ]
                    )
                    if element != "success":
                        lines.append("          - common.no_later_steps")
    lines.append("")
    return "\n".join(lines)


def render_effective_cases_yaml() -> str:
    lines: list[str] = [
        GENERATED_COMMENT,
        "schema_version: 1",
        f"flow: {FLOW_ID}",
        "cases:",
    ]
    for case in CASES:
        lines.extend(
            [
                f"  - id: {case.case_id}",
                f"    slug: {case.slug}",
                f"    kind: {case.kind}",
                f"    tier: {case.tier}",
                f"    terminal_step: {case.terminal_step}",
                f"    scenario: cases/{case.filename}",
                "    selected_variants:",
            ]
        )
        lines.extend(
            f"      - {selected_variant_id(factor_id, element_id)}"
            for factor_id, element_id in case.selected
        )
    lines.append("target_cases:")
    for target_case in TARGET_CASES:
        lines.extend(
            [
                f"  - id: {target_case.case_id}",
                f"    title: {target_case.title}",
                "    selected_variants:",
            ]
        )
        lines.extend(f"      - {variant}" for variant in target_case.selected_variants)
        if target_case.runtime_assertions:
            lines.append("    runtime_assertions:")
            for assertion in target_case.runtime_assertions:
                lines.extend(
                    [
                        f"      - project: {assertion.project_id}",
                        f"        api: {assertion.api_id}",
                        f"        expected: {assertion.expected}",
                    ]
                )
    lines.append("")
    return "\n".join(lines)


def rendered_outputs(output_root: Path = Path("docs/spec/50.e2e")) -> Mapping[Path, str]:
    flow_root = output_root / FLOW_ID
    rendered: dict[Path, str] = {}
    for factor in FACTORS:
        rendered[
            flow_root / "factors" / f"{factor.factor_id}_{factor.slug}.gen.yaml"
        ] = render_factor_yaml(factor)
    rendered[flow_root / "factors" / "effective_factors.gen.yaml"] = (
        render_effective_factors_yaml(FACTORS)
    )
    rendered[flow_root / "generated" / "effective_factor_matrix.gen.yaml"] = (
        render_effective_factor_matrix_yaml(FACTORS)
    )
    rendered[flow_root / "generated" / "effective_variants.gen.yaml"] = (
        render_effective_target_variants_yaml()
    )
    rendered[flow_root / "generated" / "effective_step_bindings.gen.yaml"] = (
        render_effective_step_bindings_yaml(FACTORS)
    )
    rendered[flow_root / "generated" / "effective_cases.gen.yaml"] = (
        render_effective_cases_yaml()
    )
    return rendered


def generate(*, check: bool = False, output_root: Path = Path("docs/spec/50.e2e")) -> int:
    rendered = rendered_outputs(output_root)
    if check:
        return check_outputs(rendered)
    write_outputs(rendered)
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    return generate(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
