from __future__ import annotations

import argparse
import csv
import io
from collections.abc import Mapping, Sequence
from pathlib import Path

import yaml

from tools.e2e_models import (
    CASES,
    FACTORS,
    FLOW_ID,
    FLOW_STEPS,
    TARGET_CASES,
    E2eTargetCase,
    element_label,
    markdown_escape,
)
from tools.generation_io import check_outputs, write_outputs

GENERATED_COMMENT = (
    "<!-- This file is generated by uv run python -m tools.generate_e2e_case_list. "
    "Do not edit manually. -->"
)

COMPONENT_ORDER = (
    "api_catalog",
    "project_workspace",
    "access_request_workflow",
    "review_decision",
    "entitlement_provisioning",
    "runtime_authorization",
    "audit_recovery",
)


def selected_elements_by_factor(case_id: str) -> dict[str, str]:
    for case in CASES:
        if case.case_id == case_id:
            return dict(case.selected)
    raise KeyError(case_id)


def target_case_projects(target_case: E2eTargetCase) -> str:
    projects = sorted({assertion.project_id for assertion in target_case.runtime_assertions})
    if projects:
        return "<br>".join(f"`{project}`" for project in projects)
    variants = " ".join(target_case.selected_variants)
    for project in ("project_A", "project_B", "project_C"):
        if project in variants:
            return f"`{project}`"
    return "-"


def target_case_apis(target_case: E2eTargetCase) -> str:
    apis = sorted(
        {
            assertion.api_id
            for assertion in target_case.runtime_assertions
            if assertion.expected == "allowed"
        }
    )
    if apis:
        return "<br>".join(f"`{api}`" for api in apis)
    for api in ("API_A", "API_B", "API_C"):
        if f".{api}." in target_case.goal_variant:
            return f"`{api}`"
    variants = " ".join(target_case.selected_variants)
    matched_apis = [api for api in ("API_A", "API_B", "API_C") if api in variants]
    return "<br>".join(f"`{api}`" for api in matched_apis) if matched_apis else "-"


def render_target_case_rows() -> list[str]:
    lines = [
        "## 5. 対象別生成ケース一覧",
        "",
        "| ケースID | 目的 | Project | API | Goal Variant | Component Variant | Runtime期待 |",
        "|---|---|---|---|---|---|---|",
    ]
    for target_case in TARGET_CASES:
        variants = "<br>".join(f"`{variant}`" for variant in target_case.selected_variants)
        runtime_assertions = (
            "<br>".join(
                f"`{assertion.project_id}` / `{assertion.api_id}`: `{assertion.expected}`"
                for assertion in target_case.runtime_assertions
            )
            if target_case.runtime_assertions
            else "-"
        )
        lines.append(
            f"| `{target_case.case_id}` | {markdown_escape(target_case.title)} | "
            f"{target_case_projects(target_case)} | {target_case_apis(target_case)} | "
            f"`{target_case.goal_variant}` | {variants} | {runtime_assertions} |"
        )
    lines.append("")
    return lines


def as_mapping(value: object) -> Mapping[str, object]:
    return value if isinstance(value, dict) else {}


def as_sequence(value: object) -> Sequence[object]:
    return value if isinstance(value, list | tuple) else ()


def scalar_text(value: object, default: str = "-") -> str:
    return value if isinstance(value, str) else default


def load_yaml(path: Path) -> Mapping[str, object]:
    loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
    return as_mapping(loaded)


def render_component_sections(flow_root: Path) -> list[str]:
    lines = ["## 1. コンポーネントごとの要素", ""]
    for component_id in COMPONENT_ORDER:
        component_root = flow_root / "components" / component_id
        component_doc = load_yaml(component_root / "component.manual.yaml")
        component = as_mapping(component_doc.get("component"))
        lines.extend(
            [
                f"### {component_id} {scalar_text(component.get('title'))}",
                "",
                "| 種別 | ID | タイトル | 補足 |",
                "|---|---|---|---|",
            ]
        )
        for invariant in as_sequence(component_doc.get("business_invariants")):
            invariant_map = as_mapping(invariant)
            lines.append(
                f"| invariant | `{scalar_text(invariant_map.get('id'))}` | - | "
                f"{markdown_escape(scalar_text(invariant_map.get('text')))} |"
            )
        actions_doc = load_yaml(component_root / "actions.manual.yaml")
        for action in as_sequence(actions_doc.get("actions")):
            action_map = as_mapping(action)
            detail = (
                f"type={scalar_text(action_map.get('operation_type'))}, "
                f"default={scalar_text(action_map.get('default_result'))}"
            )
            lines.append(
                f"| action | `{scalar_text(action_map.get('id'))}` | "
                f"{markdown_escape(scalar_text(action_map.get('title')))} | "
                f"{markdown_escape(detail)} |"
            )
        states_doc = load_yaml(component_root / "states.manual.yaml")
        for state in as_sequence(states_doc.get("states")):
            state_map = as_mapping(state)
            continue_flow = state_map.get("continue_flow")
            detail = f"continue_flow={str(continue_flow).lower()}"
            lines.append(
                f"| state | `{scalar_text(state_map.get('id'))}` | "
                f"{markdown_escape(scalar_text(state_map.get('title')))} | {detail} |"
            )
        data_doc = load_yaml(component_root / "data.manual.yaml")
        for data_profile in as_sequence(data_doc.get("data_profiles")):
            data_map = as_mapping(data_profile)
            tags = ", ".join(
                str(tag) for tag in as_sequence(data_map.get("tags")) if isinstance(tag, str)
            )
            lines.append(
                f"| data | `{scalar_text(data_map.get('id'))}` | "
                f"{markdown_escape(scalar_text(data_map.get('title')))} | "
                f"{markdown_escape(tags or '-')} |"
            )
        lines.append("")
    return lines


def render_legacy_factor_sections() -> list[str]:
    lines = [
        "## 2. 旧factor互換表",
        "",
    ]
    for factor in FACTORS:
        lines.extend(
            [
                f"### {factor.factor_id} {factor.title}",
                "",
                "| 要素ID | 既定要素 | 終端要素 | 期待観点 |",
                "|---|---:|---:|---|",
            ]
        )
        for element in factor.elements:
            lines.append(
                f"| `{element.element_id}` | {str(element.default).lower()} | "
                f"{str(element.terminal).lower()} | {markdown_escape(element.expected)} |"
            )
        lines.append("")
    return lines


def render_case_list_markdown(root: Path = Path("docs/spec/50.e2e")) -> str:
    flow_root = root / FLOW_ID
    source_flow_root = (
        flow_root
        if (flow_root / "components").exists()
        else Path("docs/spec/50.e2e") / FLOW_ID
    )
    lines = [
        GENERATED_COMMENT,
        "",
        f"# {FLOW_ID} e2e component variants",
        "",
        "## 0. 対象フロー",
        "",
        "| Step | Operation | Endpoint | Template |",
        "|---|---|---|---|",
    ]
    for step in FLOW_STEPS:
        endpoint = f"{step.method} {step.path}" if step.method != "GET" else f"GET {step.path}"
        lines.append(
            f"| `{step.step_id}` | `{step.operation}` | `{markdown_escape(endpoint)}` | "
            f"`{step.template}` |"
        )
    lines.extend(
        [
            "",
            *render_component_sections(source_flow_root),
            *render_legacy_factor_sections(),
        ]
    )
    lines.extend(
        [
            "## 3. 枝刈り規則",
            "",
            "| Rule ID | 条件 | 結果 | 理由 |",
            "|---|---|---|---|",
            "| `P001` | `terminal=true` | 後続要因をN/A化 | unit-testと同じprefix terminal方式 |",
            "| `P002` | `reject_api_access_request_result=success` | "
            "approve provisioningとRuntime成功を除外 | "
            "rejectはAWS変更しない |",
            "| `P003` | approve失敗 | Runtime API呼び出しを除外 | subscription/scopeが存在しない |",
            "| `P004` | terminal step/status/reasonが同一 | 等価ケースを統合 | "
            "E2Eの重複実行を避ける |",
            "",
            "## 4. 生成ケース一覧",
            "",
        ]
    )
    factor_columns = " | ".join(factor.factor_id for factor in FACTORS)
    factor_alignments = "|".join("---" for _ in FACTORS)
    lines.extend(
        [
            f"| ケースID | {factor_columns} | 種別 | Tier | 終了Step | シナリオ |",
            f"|---|{factor_alignments}|---|---|---|---|",
        ]
    )
    for case in CASES:
        selected = selected_elements_by_factor(case.case_id)
        selected_columns = " | ".join(
            markdown_escape(element_label(factor.factor_id, selected[factor.factor_id]))
            if factor.factor_id in selected
            else "-"
            for factor in FACTORS
        )
        lines.append(
            f"| `{case.case_id}` | {selected_columns} | `{case.kind}` | `{case.tier}` | "
            f"{markdown_escape(case.terminal_step)} | "
            f"[`cases/{case.filename}`](cases/{case.filename}) |"
        )
    lines.extend(["", *render_target_case_rows()])
    return "\n".join(lines)


def render_pruned_cases_csv() -> str:
    output = io.StringIO()
    writer = csv.writer(output, lineterminator="\n")
    writer.writerow(
        ["case_id", "kind", "tier", "terminal_step", "selected_factors", "scenario_path"]
    )
    for case in CASES:
        writer.writerow(
            [
                case.case_id,
                case.kind,
                case.tier,
                case.terminal_step,
                ";".join(f"{factor}.{element}" for factor, element in case.selected),
                f"cases/{case.filename}",
            ]
        )
    return output.getvalue()


def rendered_outputs(output_root: Path = Path("docs/spec/50.e2e")) -> Mapping[Path, str]:
    flow_root = output_root / FLOW_ID
    return {
        flow_root / "case-list_gen.md": render_case_list_markdown(output_root),
        flow_root / "pruned-cases_gen.csv": render_pruned_cases_csv(),
    }


def generate(*, check: bool = False, output_root: Path = Path("docs/spec/50.e2e")) -> int:
    rendered = rendered_outputs(output_root)
    if check:
        return check_outputs(rendered)
    write_outputs(rendered)
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    return generate(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
