import argparse
import ast
import importlib
import json
import re
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any, cast

from app.main import create_app
from tools.check_api_descriptions import (
    enum_member_comment,
    enum_member_line_numbers,
    enum_members,
    is_str_enum_class,
)

HTTP_METHODS = {"get", "post", "put", "patch", "delete", "options", "head"}
type JsonObject = dict[str, Any]
GENERATED_COMMENT = (
    "<!-- This file is generated by uv run python -m tools.generate_openapi_if_specs. "
    "Do not edit manually. -->"
)
PARAMETER_DESCRIPTION_OVERRIDES = {
    ("header", "Idempotency-Key"): (
        "同じ更新系リクエストの重複処理を防ぐためにクライアントが指定する一意なキーです。"
        "同じキーで再送された場合、サーバーは同一リクエストとして扱います。"
    ),
}
DEFAULT_API_COMMON_PATH = Path(__file__).resolve().parents[1] / "app/apis"
DEFAULT_API_ROOT = Path("src/app/apis")


@dataclass(frozen=True)
class FieldRow:
    name: str
    type_name: str
    required: bool
    description: str
    constraints: str


@dataclass(frozen=True)
class OperationSamples:
    request: JsonObject | None
    response: JsonObject | None
    status_samples: dict[int, JsonObject] | None = None


def snake_case(value: str) -> str:
    value = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", value)
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", value)
    value = re.sub(r"[^a-zA-Z0-9]+", "_", value)
    return value.strip("_").lower() or "api"


def markdown_escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def as_object(value: Any) -> JsonObject:
    return cast(JsonObject, value) if isinstance(value, dict) else {}


def as_list(value: Any) -> list[Any]:
    return cast(list[Any], value) if isinstance(value, list) else []  # type: ignore[redundant-cast]


def json_sample(value: Any) -> JsonObject | None:
    if value is None:
        return None
    if hasattr(value, "model_dump"):
        dumped = value.model_dump(mode="json", by_alias=True)
        return as_object(dumped)
    return as_object(value)


def render_json(value: JsonObject) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


def schema_components(openapi: JsonObject) -> JsonObject:
    components = openapi.get("components", {})
    schemas = as_object(components).get("schemas", {})
    return as_object(schemas)


def ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def resolve_schema(schema: JsonObject, components: JsonObject) -> JsonObject:
    if "$ref" in schema:
        resolved = components.get(ref_name(str(schema["$ref"])), {})
        return as_object(resolved)
    return schema


def unwrap_nullable(schema: JsonObject, components: JsonObject) -> tuple[JsonObject, bool]:
    schema = resolve_schema(schema, components)
    for key in ("anyOf", "oneOf"):
        variants = as_list(schema.get(key))
        if not variants:
            continue
        non_null = [
            resolve_schema(as_object(variant), components)
            for variant in variants
            if as_object(variant).get("type") != "null"
        ]
        if len(non_null) == 1 and len(non_null) != len(variants):
            return non_null[0], True
    return schema, False


def enum_values(schema: JsonObject) -> list[str]:
    return [str(value) for value in as_list(schema.get("enum"))]


def enum_type(schema: JsonObject) -> str:
    values = enum_values(schema)
    base_type = str(schema.get("type") or "string")
    return f"{base_type}({', '.join(values)})"


def enum_common_files(path: Path) -> list[Path]:
    if not path.exists():
        return []
    if path.is_file():
        return [path]
    return sorted(
        common_path
        for common_path in path.rglob("common.py")
        if "__pycache__" not in common_path.parts
    )


@lru_cache
def enum_comment_descriptions(
    path: Path = DEFAULT_API_COMMON_PATH,
) -> dict[str, dict[str, str]]:
    descriptions: dict[str, dict[str, str]] = {}
    for common_path in enum_common_files(path):
        source = common_path.read_text(encoding="utf-8")
        source_lines = source.splitlines()
        tree = ast.parse(source, filename=str(common_path))
        for node in ast.walk(tree):
            if not isinstance(node, ast.ClassDef) or not is_str_enum_class(node):
                continue
            members = enum_members(node)
            member_lines = enum_member_line_numbers(node)
            value_descriptions: dict[str, str] = {}
            for member_name, member_value in members.items():
                description = enum_member_comment(source_lines, member_lines[member_name])
                if description:
                    value_descriptions[member_value] = description
            descriptions[node.name] = value_descriptions
    return descriptions


def enum_value_description(schema: JsonObject, value: str) -> str:
    schema_name = str(schema.get("title") or "")
    return (
        enum_comment_descriptions().get(schema_name, {}).get(value)
        or "列挙値として指定可能な値です。"
    )


def schema_type(schema: JsonObject, components: JsonObject) -> str:
    if "$ref" in schema:
        resolved = resolve_schema(schema, components)
        if enum_values(resolved):
            return enum_type(resolved)
        return ref_name(str(schema["$ref"]))
    schema, nullable = unwrap_nullable(schema, components)
    if enum_values(schema):
        type_name = enum_type(schema)
    elif schema.get("type") == "array":
        items = as_object(schema.get("items", {}))
        item_type = schema_type(items, components)
        type_name = f"array<{item_type}>"
    elif schema.get("type") == "object" and "additionalProperties" in schema:
        additional = schema["additionalProperties"]
        if isinstance(additional, dict):
            type_name = f"object<string, {schema_type(as_object(additional), components)}>"
        else:
            type_name = "object"
    else:
        type_name = str(schema.get("type") or schema.get("title") or "object")
    return f"{type_name} | null" if nullable else type_name


def schema_constraints(schema: JsonObject, components: JsonObject) -> str:
    schema, _nullable = unwrap_nullable(schema, components)
    constraints: list[str] = []
    for key in (
        "minimum",
        "maximum",
        "exclusiveMinimum",
        "exclusiveMaximum",
        "minLength",
        "maxLength",
        "pattern",
        "minItems",
        "maxItems",
    ):
        if key in schema:
            constraints.append(f"{key}={schema[key]}")
    values = enum_values(schema)
    if values:
        constraints.append(
            "<br>".join(f"{value}={enum_value_description(schema, value)}" for value in values)
        )
    return ", ".join(constraints) if constraints else "-"


def schema_description(schema: JsonObject, fallback: str = "") -> str:
    description = schema.get("description")
    return str(description or fallback or "-")


def nested_object_schema(schema: JsonObject, components: JsonObject) -> JsonObject:
    schema = resolve_schema(schema, components)
    if schema.get("type") == "object" and as_object(schema.get("properties")):
        return schema
    if schema.get("type") == "array":
        return nested_object_schema(as_object(schema.get("items")), components)
    return {}


def object_field_rows(
    schema: JsonObject,
    components: JsonObject,
    *,
    prefix: str = "",
    seen_refs: frozenset[str] = frozenset(),
) -> list[FieldRow]:
    schema = resolve_schema(schema, components)
    required = set(str(item) for item in as_list(schema.get("required", [])))
    properties = as_object(schema.get("properties", {}))
    if not properties:
        return []

    rows: list[FieldRow] = []
    for name, property_schema in properties.items():
        if not isinstance(property_schema, dict):
            continue
        property_schema_object = cast(JsonObject, property_schema)
        resolved = resolve_schema(property_schema_object, components)
        name = str(name)
        field_name = f"{prefix}.{name}" if prefix else name
        rows.append(
            FieldRow(
                name=field_name,
                type_name=schema_type(property_schema_object, components),
                required=name in required,
                description=schema_description(resolved, f"`{name}` の値。"),
                constraints=schema_constraints(property_schema_object, components),
            )
        )
        child_schema = nested_object_schema(property_schema_object, components)
        ref = str(
            property_schema_object.get("$ref")
            or as_object(property_schema_object.get("items")).get("$ref")
        )
        if child_schema and ref not in seen_refs:
            child_prefix = (
                f"{field_name}[]" if property_schema_object.get("type") == "array" else field_name
            )
            rows.extend(
                object_field_rows(
                    child_schema,
                    components,
                    prefix=child_prefix,
                    seen_refs=seen_refs | frozenset([ref]) if ref else seen_refs,
                )
            )
    return rows


def parameter_rows(operation: JsonObject, location: str, components: JsonObject) -> list[FieldRow]:
    rows: list[FieldRow] = []
    for parameter in as_list(operation.get("parameters", [])):
        parameter_object = as_object(parameter)
        if not parameter_object or parameter_object.get("in") != location:
            continue
        schema = as_object(parameter_object.get("schema", {}))
        name = str(parameter_object.get("name", ""))
        rows.append(
            FieldRow(
                name=name,
                type_name=schema_type(schema, components),
                required=bool(parameter_object.get("required")),
                description=str(
                    parameter_object.get("description")
                    or PARAMETER_DESCRIPTION_OVERRIDES.get((location, name))
                    or schema_description(schema)
                ),
                constraints=schema_constraints(schema, components),
            )
        )
    return rows


def request_body_rows(operation: JsonObject, components: JsonObject) -> list[FieldRow]:
    request_body = operation.get("requestBody")
    if not isinstance(request_body, dict):
        return []
    request_body_object = cast(JsonObject, request_body)
    content = as_object(request_body_object.get("content", {}))
    if not content:
        return []
    media: Any = content.get("application/json") or next(
        iter(content.values()), cast(JsonObject, {})
    )
    if not isinstance(media, dict):
        return []
    media_object = cast(JsonObject, media)
    schema = as_object(media_object.get("schema", {}))
    return object_field_rows(schema, components)


def response_media(response: JsonObject) -> tuple[str, JsonObject]:
    content = as_object(response.get("content", {}))
    if not content:
        return "-", {}
    media_type, media = next(iter(content.items()))
    if not isinstance(media, dict):
        return str(media_type), {}
    media_object = cast(JsonObject, media)
    schema = as_object(media_object.get("schema", {}))
    return str(media_type), schema


def status_sample_description(status_code: str, samples: OperationSamples | None) -> str | None:
    if samples is None or samples.status_samples is None:
        return None
    try:
        status = int(status_code)
    except ValueError:
        return None
    status_sample = samples.status_samples.get(status)
    if not status_sample:
        return None
    response = as_object(status_sample.get("response"))
    error = as_object(response.get("error"))
    details = as_list(error.get("details"))
    for detail in details:
        detail_object = as_object(detail)
        reason = detail_object.get("reason")
        if isinstance(reason, str) and reason.strip():
            return reason
    message = error.get("message")
    if isinstance(message, str) and message.strip():
        return message
    return None


def response_description(
    status_code: str,
    response: JsonObject,
    samples: OperationSamples | None,
) -> str:
    return status_sample_description(status_code, samples) or str(response.get("description") or "-")


def response_summary_rows(
    operation: JsonObject,
    components: JsonObject,
    samples: OperationSamples | None = None,
) -> list[list[str]]:
    rows: list[list[str]] = []
    responses = as_object(operation.get("responses", {}))
    if not responses:
        return rows
    for status_code, response in responses.items():
        if not isinstance(response, dict):
            continue
        response_object = cast(JsonObject, response)
        media_type, schema = response_media(response_object)
        body_rows = object_field_rows(schema, components)
        body = f"{len(body_rows)} field(s)" if body_rows else "-"
        rows.append(
            [
                str(status_code),
                response_description(str(status_code), response_object, samples),
                media_type,
                body,
            ]
        )
    return rows


def render_field_table(rows: list[FieldRow]) -> list[str]:
    if not rows:
        return ["_なし_"]
    lines = [
        "| 項目 | 型 | 必須 | 説明 | 制約 |",
        "| --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{markdown_escape(row.name)}`",
                    f"`{markdown_escape(row.type_name)}`",
                    "yes" if row.required else "no",
                    markdown_escape(row.description),
                    markdown_escape(row.constraints),
                ]
            )
            + " |"
        )
    return lines


def render_response_summary(rows: list[list[str]]) -> list[str]:
    if not rows:
        return ["_なし_"]
    lines = [
        "| Status | 説明 | Media type | Body |",
        "| --- | --- | --- | --- |",
    ]
    for status_code, description, media_type, body in rows:
        lines.append(
            f"| `{markdown_escape(status_code)}` | {markdown_escape(description)} | "
            f"`{markdown_escape(media_type)}` | {markdown_escape(body)} |"
        )
    return lines


def render_response_details(
    operation: JsonObject,
    components: JsonObject,
    samples: OperationSamples | None = None,
) -> list[str]:
    lines: list[str] = []
    responses = as_object(operation.get("responses", {}))
    if not responses:
        return lines
    for status_code, response in responses.items():
        if not isinstance(response, dict):
            continue
        response_object = cast(JsonObject, response)
        media_type, schema = response_media(response_object)
        body_rows = object_field_rows(schema, components)
        if not body_rows:
            continue
        description = response_description(str(status_code), response_object, samples)
        lines.extend(
            [
                "",
                f"##### `{status_code}` {description}",
                "",
                f"Media type: `{media_type}`",
                "",
                *render_field_table(body_rows),
            ]
        )
    return lines


def sample_url(path: str, operation: JsonObject) -> str:
    url = f"https://api.example.com{path}"
    for row in parameter_rows(operation, "path", {}):
        placeholder = "{" + row.name + "}"
        default = parameter_default(operation, "path", row.name)
        url = url.replace(placeholder, default or f"<{row.name}>")
    query_parts: list[str] = []
    for row in parameter_rows(operation, "query", {}):
        query_parts.append(f"{row.name}=<{row.name}>")
    if query_parts:
        return f"{url}?{'&'.join(query_parts)}"
    return url


def parameter_default(operation: JsonObject, location: str, name: str) -> str | None:
    for parameter in as_list(operation.get("parameters", [])):
        parameter_object = as_object(parameter)
        if parameter_object.get("in") != location or parameter_object.get("name") != name:
            continue
        schema = as_object(parameter_object.get("schema", {}))
        default = schema.get("default")
        if default is not None:
            return str(default)
    return None


def render_curl_sample(
    path: str,
    method: str,
    operation: JsonObject,
    sample: JsonObject | None,
) -> str:
    lines = [f"curl -X {method.upper()} '{sample_url(path, operation)}'"]
    for row in parameter_rows(operation, "header", {}):
        lines.append(f"  -H '{row.name}: <{row.name}>'")
    if sample is not None:
        lines.append("  -H 'Content-Type: application/json'")
        lines.append(f"  -d '{render_json(sample)}'")
    return " \\\n".join(lines)


def render_samples_section(
    path: str,
    method: str,
    operation: JsonObject,
    samples: OperationSamples | None,
) -> list[str]:
    if samples is not None and samples.status_samples:
        lines = ["## Samples", ""]
        for status_code, status_sample in sorted(samples.status_samples.items()):
            request_sample = as_object(status_sample.get("request"))
            response_sample = as_object(status_sample.get("response"))
            lines.extend(
                [
                    f"### HTTP {status_code}",
                    "",
                    "#### Request",
                    "",
                    "```json",
                    render_json(request_sample),
                    "```",
                    "",
                    "#### Response",
                    "",
                    "```json",
                    render_json(response_sample),
                    "```",
                    "",
                ]
            )
        return lines

    body_request_sample = samples.request if samples is not None else None
    body_response_sample = samples.response if samples is not None else None
    lines = [
        "## Samples",
        "",
        "### In",
        "",
        "```bash",
        render_curl_sample(path, method, operation, body_request_sample),
        "```",
        "",
        "### Out",
        "",
    ]
    if body_response_sample is None:
        lines.extend(["_なし_", ""])
        return lines
    lines.extend(["```json", render_json(body_response_sample), "```", ""])
    return lines


def render_operation_markdown(
    path: str,
    method: str,
    operation: JsonObject,
    components: JsonObject,
    samples: OperationSamples | None = None,
) -> str:
    summary = str(operation.get("summary") or "")
    description = str(operation.get("description") or "")
    lines = [
        f"# {method.upper()} {path}",
        "",
        GENERATED_COMMENT,
        "",
        f"Summary: {summary or '-'}",
        "",
    ]
    if description:
        lines.extend([description, ""])
    lines.extend(
        ["## Headers", "", *render_field_table(parameter_rows(operation, "header", components)), ""]
    )
    lines.extend(
        [
            "## Path Parameters",
            "",
            *render_field_table(parameter_rows(operation, "path", components)),
            "",
        ]
    )
    lines.extend(
        [
            "## Query Parameters",
            "",
            *render_field_table(parameter_rows(operation, "query", components)),
            "",
        ]
    )
    lines.extend(["## Data", "", *render_field_table(request_body_rows(operation, components)), ""])
    lines.extend(
        [
            "## Responses",
            "",
            *render_response_summary(response_summary_rows(operation, components, samples)),
        ]
    )
    lines.extend(render_response_details(operation, components, samples))
    lines.extend(["", *render_samples_section(path, method, operation, samples)])
    content = "\n".join(lines).rstrip()
    return f"{content}\n"


def literal_string(node: ast.AST | None) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return None


def keyword_value(call: ast.Call, name: str) -> ast.AST | None:
    for keyword in call.keywords:
        if keyword.arg == name:
            return keyword.value
    return None


def router_operation_id(source: str, router_path: Path) -> str | None:
    tree = ast.parse(source, filename=str(router_path))
    for node in ast.walk(tree):
        if not isinstance(node, ast.AsyncFunctionDef | ast.FunctionDef):
            continue
        for decorator in node.decorator_list:
            if not isinstance(decorator, ast.Call):
                continue
            operation_id = literal_string(keyword_value(decorator, "operation_id"))
            if operation_id:
                return operation_id
    return None


def implementation_operation_paths(api_root: Path) -> dict[str, Path]:
    paths: dict[str, Path] = {}
    for router_path in sorted(api_root.glob("*/*/router.py")):
        if "__pycache__" in router_path.parts:
            continue
        operation_id = router_operation_id(
            router_path.read_text(encoding="utf-8"),
            router_path,
        )
        if operation_id is None:
            continue
        paths[operation_id] = router_path.parent.relative_to(api_root)
    return paths


def sample_module_name(api_path: Path) -> str:
    return ".".join(("app", "apis", *api_path.parts, "samples"))


def module_sample(module: Any, suffix: str) -> JsonObject | None:
    for name in sorted(dir(module)):
        if name.endswith(suffix):
            return json_sample(getattr(module, name))
    return None


def module_status_samples(module: Any) -> dict[int, JsonObject] | None:
    for name in sorted(dir(module)):
        if not name.endswith("_STATUS_SAMPLES"):
            continue
        value = getattr(module, name)
        if not isinstance(value, dict):
            continue
        status_samples = cast(dict[object, object], value)
        return {
            int(status_code): as_object(status_sample)
            for status_code, status_sample in status_samples.items()
            if isinstance(status_code, int) and isinstance(status_sample, dict)
        }
    return None


def load_operation_sample(api_path: Path) -> OperationSamples | None:
    try:
        module = importlib.import_module(sample_module_name(api_path))
    except ModuleNotFoundError:
        return None
    return OperationSamples(
        request=module_sample(module, "_REQUEST_SAMPLE"),
        response=module_sample(module, "_RESPONSE_SAMPLE"),
        status_samples=module_status_samples(module),
    )


def implementation_operation_samples(
    operation_paths: dict[str, Path],
) -> dict[str, OperationSamples]:
    samples: dict[str, OperationSamples] = {}
    for operation_id, api_path in operation_paths.items():
        sample = load_operation_sample(api_path)
        if sample is not None:
            samples[operation_id] = sample
    return samples


def operation_output_path(
    output_dir: Path,
    operation: JsonObject,
    operation_paths: dict[str, Path] | None = None,
) -> Path:
    operation_id = str(operation.get("operationId") or operation.get("summary") or "api")
    if operation_paths is not None and operation_id in operation_paths:
        return output_dir / operation_paths[operation_id] / "if_gen.md"
    tags = as_list(operation.get("tags"))
    tag = str(tags[0]) if tags else "default"
    return output_dir / snake_case(tag) / snake_case(operation_id) / "if_gen.md"


def iter_operations(openapi: JsonObject) -> list[tuple[str, str, JsonObject]]:
    operations: list[tuple[str, str, JsonObject]] = []
    paths = as_object(openapi.get("paths", {}))
    if not paths:
        return operations
    for path, path_item in sorted(paths.items()):
        if not isinstance(path_item, dict):
            continue
        path_item_object = cast(JsonObject, path_item)
        for method, operation in sorted(path_item_object.items()):
            if method not in HTTP_METHODS or not isinstance(operation, dict):
                continue
            operations.append((str(path), method, cast(JsonObject, operation)))
    return operations


def generate_from_openapi(
    openapi: JsonObject,
    output_dir: Path,
    operation_paths: dict[str, Path] | None = None,
    operation_samples: dict[str, OperationSamples] | None = None,
) -> list[Path]:
    components = schema_components(openapi)
    written: list[Path] = []
    for path, method, operation in iter_operations(openapi):
        operation_id = str(operation.get("operationId") or operation.get("summary") or "api")
        output_path = operation_output_path(output_dir, operation, operation_paths)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(
            render_operation_markdown(
                path,
                method,
                operation,
                components,
                (operation_samples or {}).get(operation_id),
            ),
            encoding="utf-8",
        )
        written.append(output_path)
    return written


def load_fastapi_openapi() -> JsonObject:
    return create_app().openapi()


def generate(output_dir: Path, api_root: Path = DEFAULT_API_ROOT) -> list[Path]:
    operation_paths = implementation_operation_paths(api_root)
    return generate_from_openapi(
        load_fastapi_openapi(),
        output_dir,
        operation_paths,
        implementation_operation_samples(operation_paths),
    )


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate IF specs from FastAPI OpenAPI.")
    parser.add_argument("--output-dir", type=Path, default=Path("docs/spec/40.apis"))
    parser.add_argument("--api-root", type=Path, default=DEFAULT_API_ROOT)
    return parser


def main() -> None:
    args = build_arg_parser().parse_args()
    written = generate(args.output_dir, args.api_root)
    print(f"Generated {len(written)} IF spec files.")


if __name__ == "__main__":  # pragma: no cover
    main()
