from __future__ import annotations

import argparse
from collections.abc import Mapping, Sequence
from pathlib import Path

from tools.e2e_models import CASES, FLOW_ID, E2eCase, element_label, markdown_escape
from tools.generation_io import check_outputs, write_outputs

GENERATED_COMMENT = (
    "<!-- This file is generated by uv run python -m tools.generate_e2e_scenarios. "
    "Do not edit manually. -->"
)


STEP_LABELS = {
    "post_apis": ("POST /apis", "`${apiId}` と `${apiStageId}` を後続stepへ渡す。"),
    "post_projects": (
        "POST /projects",
        "`${projectId}` と `${project_api_key}` を後続stepへ渡す。",
    ),
    "post_api_access_requests": (
        "POST /projects/${projectId}/api-access-requests",
        "`${accessRequestId}` を審査stepへ渡す。",
    ),
    "approve_api_access_request": (
        "POST /api-access-requests/${accessRequestId}/approve",
        "subscription、Usage Plan stage、Cognito scopeの反映結果を確認する。",
    ),
    "reject_api_access_request": (
        "POST /api-access-requests/${accessRequestId}/reject",
        "reviewがREJECTEDとなり外部provisioningが発生しないことを確認する。",
    ),
    "get_project_subscriptions": (
        "GET /projects/${projectId}/subscriptions",
        "期待するsubscription有無とderivedStateを確認する。",
    ),
    "invoke_runtime_api": (
        "Runtime API call",
        "`${runtime_access_token}` と `${project_api_key}` の組み合わせで認可結果を確認する。",
    ),
}


def render_selected_factors(case: E2eCase) -> list[str]:
    lines = ["| Factor | Element |", "|---|---|"]
    for factor_id, element_id in case.selected:
        lines.append(f"| `{factor_id}` | {markdown_escape(element_label(factor_id, element_id))} |")
    return lines


def render_steps(case: E2eCase) -> list[str]:
    lines: list[str] = []
    for index, step_id in enumerate(case.scenario_steps, start=1):
        endpoint, ok_condition = STEP_LABELS[step_id]
        lines.extend(
            [
                f"### Step {index}: {endpoint}",
                "",
                "Request:",
                "",
                "```http",
                f"{endpoint}",
                "Authorization: Bearer ${management_or_runtime_token}",
                f"Idempotency-Key: ${{case_id}}-{step_id}",
                "Content-Type: application/json",
                "```",
                "",
                "OK条件:",
                "",
                f"- {ok_condition}",
                "- secret値、API key値、client secret値の実値をMarkdownやログに出さない。",
                "",
            ]
        )
    return lines


def render_scenario_markdown(case: E2eCase) -> str:
    lines = [
        GENERATED_COMMENT,
        "",
        f"# {case.case_id} {case.slug.replace('_', ' ')}",
        "",
        "## 1. ケース概要",
        "",
        "| 項目 | 内容 |",
        "|---|---|",
        f"| Flow | `{FLOW_ID}` |",
        f"| Tier | `{case.tier}` |",
        f"| 目的 | {markdown_escape(case.purpose)} |",
        f"| 終了条件 | {markdown_escape(case.terminal_step)} |",
        "",
        "## 2. 選択要因",
        "",
        *render_selected_factors(case),
        "",
        "## 3. 事前条件",
        "",
        "- Cognito管理API用tokenを取得できる。",
        "- Runtime対象のAPI Gateway REST APIがsandbox環境に存在する。",
        "- テストデータの `apiCode` と `projectCode` はケースIDを含めて一意にする。",
        "- `${project_api_key}`、`${confidential_client_secret}`、"
        "`${runtime_access_token}` はplaceholderとして扱う。",
        "",
        "## 4. API呼び出し手順",
        "",
        *render_steps(case),
        "## 5. 後続確認",
        "",
    ]
    lines.extend(f"- {expected}" for expected in case.expected)
    lines.extend(
        [
            "",
            "## 6. クリーンアップ",
            "",
            "- sandboxで作成したAPI catalog、project、Cognito client、Usage Plan、API keyは"
            "cleanup手順に従って削除または隔離する。",
            "",
        ]
    )
    return "\n".join(lines)


def rendered_outputs(output_root: Path = Path("docs/spec/50.e2e")) -> Mapping[Path, str]:
    cases_root = output_root / FLOW_ID / "cases"
    return {cases_root / case.filename: render_scenario_markdown(case) for case in CASES}


def generate(*, check: bool = False, output_root: Path = Path("docs/spec/50.e2e")) -> int:
    rendered = rendered_outputs(output_root)
    if check:
        return check_outputs(rendered)
    write_outputs(rendered)
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    return generate(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
