from __future__ import annotations

import argparse
import ast
import re
from collections.abc import Iterable, Sequence
from dataclasses import dataclass, field
from pathlib import Path

GENERATED_COMMENT = (
    "<!-- This file is generated by uv run python -m tools.generate_api_sequences. "
    "Do not edit manually. -->"
)
SQL_TABLE_PATTERN = re.compile(
    r"\b(?:FROM|JOIN|INTO|UPDATE)\s+([A-Za-z_][A-Za-z0-9_]*)",
    re.IGNORECASE,
)
HTTP_STATUS_CODE_PATTERN = re.compile(r"HTTP_(?P<code>[0-9]{3})_(?P<reason>[A-Z0-9_]+)")
SQL_ACTIONS = {
    "select": "参照",
    "insert": "追加",
    "update": "更新",
    "delete": "削除",
}
SQL_RECORD_ACTIONS = {
    "参照": "レコードを参照する",
    "追加": "レコードを追加する",
    "更新": "レコードを更新する",
    "削除": "レコードを削除する",
}
ROUTER_METHODS = {"delete", "get", "patch", "post", "put"}
COMMON_ERROR_STATUS_CODES = (401, 422, 429, 500)
HTTP_500_INTERNAL_SERVER_ERROR = 500
HTTP_STATUS_REASON_PHRASES = {
    200: "OK",
    201: "Created",
    400: "Bad Request",
    401: "Unauthorized",
    403: "Forbidden",
    404: "Not Found",
    409: "Conflict",
    422: "Unprocessable Content",
    429: "Too Many Requests",
    500: "Internal Server Error",
    502: "Bad Gateway",
    503: "Service Unavailable",
}
PREDICATES = {"has", "is"}
ROUTER_ERROR_CONDITION = "Router で捕捉した例外を error response に変換する場合。"
ROUTER_ERROR_DETAIL = "internal server error"


@dataclass(frozen=True)
class SequenceStep:
    function_name: str
    target: str
    description: str
    arguments: tuple[str, ...] = ()
    return_type: str | None = None
    integration_resources: tuple[str, ...] = ()
    query_functions: tuple[str, ...] = ()
    condition_label: str | None = None


@dataclass(frozen=True)
class SqlStep:
    filename: str
    action: str
    tables: tuple[str, ...]
    summary: str


@dataclass(frozen=True)
class ErrorReturnStep:
    status_code: int
    condition: str
    detail: str


@dataclass(frozen=True)
class SuccessReturnStep:
    status_code: int


type SequenceItem = SequenceStep | ErrorReturnStep | SuccessReturnStep


def empty_sequence_items() -> list[SequenceItem]:
    return []


def empty_success_returns() -> list[SuccessReturnStep]:
    return []


@dataclass(frozen=True)
class FunctionErrorMetadata:
    status_code: int
    detail: str
    summary: str


@dataclass(frozen=True)
class FunctionMetadata:
    description: str
    arguments: tuple[str, ...]
    return_type: str | None
    integration_resources: tuple[str, ...] = ()
    query_functions: tuple[str, ...] = ()
    errors: tuple[FunctionErrorMetadata, ...] = ()


@dataclass(frozen=True)
class ApiSequence:
    domain: str
    api: str
    endpoint_name: str
    operation_id: str
    steps: list[SequenceStep]
    error_returns: list[ErrorReturnStep]
    sql_steps: list[SqlStep]
    success_returns: list[SuccessReturnStep] = field(default_factory=empty_success_returns)
    items: list[SequenceItem] = field(default_factory=empty_sequence_items)
    integration_resources: frozenset[str] = field(default_factory=lambda: frozenset[str]())
    method: str = "GET"
    path: str = "/"
    status_codes: tuple[int, ...] = (200,)


def snake_to_title(value: str) -> str:
    return value.replace("_", " ")


def participant_id(prefix: str, value: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9_]", "_", value)
    return f"{prefix}_{normalized}"


def literal_string(node: ast.AST | None) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return None


def keyword_value(call: ast.Call, name: str) -> ast.AST | None:
    for keyword in call.keywords:
        if keyword.arg == name:
            return keyword.value
    return None


def is_router_decorator(node: ast.AST) -> bool:
    return (
        isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr in ROUTER_METHODS
        and isinstance(node.func.value, ast.Name)
        and node.func.value.id == "router"
    )


def endpoint_function(tree: ast.AST) -> ast.AsyncFunctionDef | ast.FunctionDef:
    for node in ast.walk(tree):
        if not isinstance(node, ast.AsyncFunctionDef | ast.FunctionDef):
            continue
        if any(is_router_decorator(decorator) for decorator in node.decorator_list):
            return node
    raise ValueError("router endpoint function is not found")


def endpoint_operation_id(function: ast.AsyncFunctionDef | ast.FunctionDef) -> str:
    for decorator in function.decorator_list:
        if not is_router_decorator(decorator):
            continue
        if isinstance(decorator, ast.Call):
            operation_id = literal_string(keyword_value(decorator, "operation_id"))
            if operation_id:
                return operation_id
    return function.name


def endpoint_route_method(function: ast.AsyncFunctionDef | ast.FunctionDef) -> str:
    for decorator in function.decorator_list:
        if is_router_decorator(decorator) and isinstance(decorator, ast.Call):
            function_ref = decorator.func
            if isinstance(function_ref, ast.Attribute):
                return function_ref.attr.upper()
    return "GET"


def endpoint_route_path(function: ast.AsyncFunctionDef | ast.FunctionDef) -> str:
    for decorator in function.decorator_list:
        if not is_router_decorator(decorator) or not isinstance(decorator, ast.Call):
            continue
        if decorator.args:
            path = literal_string(decorator.args[0])
            if path is not None:
                return path
        path = literal_string(keyword_value(decorator, "path"))
        if path is not None:
            return path
    return "/"


def http_status_code(node: ast.AST | None) -> int | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, int):
        return node.value
    if isinstance(node, ast.Attribute):
        match = HTTP_STATUS_CODE_PATTERN.fullmatch(node.attr)
        if match is not None:
            return int(match.group("code"))
    return None


def response_status_codes(node: ast.AST | None) -> tuple[int, ...]:
    if node is None:
        return ()
    codes: list[int] = []
    if isinstance(node, ast.Dict):
        for key, value in zip(node.keys, node.values, strict=True):
            if key is None:
                codes.extend(response_status_codes(value))
                continue
            if code := http_status_code(key):
                codes.append(code)
    if isinstance(node, ast.Call):
        callee = node.func
        callee_name: str | None = None
        if isinstance(callee, ast.Name):
            callee_name = callee.id
        if isinstance(callee, ast.Attribute):
            callee_name = callee.attr
        if callee_name == "error_responses":
            codes.extend(COMMON_ERROR_STATUS_CODES)
            for argument in node.args:
                if code := http_status_code(argument):
                    codes.append(code)
    return tuple(dict.fromkeys(codes))


def endpoint_status_codes(function: ast.AsyncFunctionDef | ast.FunctionDef) -> tuple[int, ...]:
    codes: list[int] = []
    for decorator in function.decorator_list:
        if not is_router_decorator(decorator) or not isinstance(decorator, ast.Call):
            continue
        if code := http_status_code(keyword_value(decorator, "status_code")):
            codes.append(code)
        codes.extend(response_status_codes(keyword_value(decorator, "responses")))
    return tuple(dict.fromkeys(codes or [200]))


def http_status_code_label(status_code: int) -> str:
    reason_phrase = HTTP_STATUS_REASON_PHRASES.get(status_code)
    if reason_phrase is None:
        return f"HTTP {status_code}"
    return f"HTTP {status_code} {reason_phrase}"


def awaited_api_function_name(node: ast.AST) -> str | None:
    if not isinstance(node, ast.Await):
        return None
    call = node.value
    if not isinstance(call, ast.Call):
        return None
    function = call.func
    if not isinstance(function, ast.Attribute):
        return None
    if not isinstance(function.value, ast.Name):
        return None
    if function.value.id != "api_functions":
        return None
    return function.attr


def annotation_text(node: ast.AST | None) -> str | None:
    if node is None:
        return None
    return ast.unparse(node)


def imported_integration_ports(tree: ast.AST) -> dict[str, str]:
    ports: dict[str, str] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.ImportFrom):
            continue
        module = node.module or ""
        match = re.fullmatch(r"app\.integrations\.([A-Za-z_][A-Za-z0-9_]*)\.port", module)
        if match is None:
            continue
        resource = match.group(1)
        for alias in node.names:
            local_name = alias.asname or alias.name
            ports[local_name] = resource
    return ports


def annotation_name(node: ast.AST | None) -> str | None:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    if isinstance(node, ast.Subscript):
        return annotation_name(node.value)
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.BitOr):
        return annotation_name(node.left) or annotation_name(node.right)
    return None


def function_integration_arguments(
    function: ast.AsyncFunctionDef | ast.FunctionDef,
    ports: dict[str, str],
) -> dict[str, str]:
    resources: dict[str, str] = {}
    for arg in [
        *function.args.posonlyargs,
        *function.args.args,
        *function.args.kwonlyargs,
    ]:
        name = annotation_name(arg.annotation)
        if name is not None and name in ports:
            resources[arg.arg] = ports[name]
    return resources


def called_integration_resources(
    function: ast.AsyncFunctionDef | ast.FunctionDef,
    ports: dict[str, str],
) -> tuple[str, ...]:
    integration_arguments = function_integration_arguments(function, ports)
    resources: list[str] = []
    for node in ast.walk(function):
        if not isinstance(node, ast.Call):
            continue
        callee = node.func
        if not isinstance(callee, ast.Attribute):
            continue
        if not isinstance(callee.value, ast.Name):
            continue
        resource = integration_arguments.get(callee.value.id)
        if resource is not None and resource not in resources:
            resources.append(resource)
    return tuple(resources)


def called_query_functions(function: ast.AsyncFunctionDef | ast.FunctionDef) -> tuple[str, ...]:
    names: list[str] = []
    for node in ast.walk(function):
        if not isinstance(node, ast.Call):
            continue
        callee = node.func
        if not isinstance(callee, ast.Attribute):
            continue
        if not isinstance(callee.value, ast.Name) or callee.value.id != "queries":
            continue
        if callee.attr not in names:
            names.append(callee.attr)
    return tuple(names)


def called_local_functions(function: ast.AsyncFunctionDef | ast.FunctionDef) -> tuple[str, ...]:
    names: list[str] = []
    for node in ast.walk(function):
        if not isinstance(node, ast.Call):
            continue
        if not isinstance(node.func, ast.Name):
            continue
        if node.func.id not in names:
            names.append(node.func.id)
    return tuple(names)


def direct_function_errors(
    function: ast.AsyncFunctionDef | ast.FunctionDef,
) -> tuple[FunctionErrorMetadata, ...]:
    errors: list[FunctionErrorMetadata] = []
    for node in ast.walk(function):
        if not isinstance(node, ast.Raise):
            continue
        call = node.exc
        if not isinstance(call, ast.Call):
            continue
        if not isinstance(call.func, ast.Name) or call.func.id != "ApiFunctionError":
            continue
        if len(call.args) < 2:
            continue
        status_code = http_status_code(call.args[0])
        detail = literal_string(call.args[1])
        summary = literal_string(keyword_value(call, "summary"))
        if status_code is None or detail is None or summary is None:
            continue
        errors.append(FunctionErrorMetadata(status_code, detail, summary))
    return tuple(dict.fromkeys(errors))


def imported_project_common_errors(
    functions_path: Path,
) -> dict[str, tuple[FunctionErrorMetadata, ...]]:
    common_path = functions_path.parents[1] / "common.py"
    if not common_path.exists() or common_path == functions_path:
        return {}
    tree = ast.parse(common_path.read_text(encoding="utf-8"), filename=str(common_path))
    return {
        node.name: direct_function_errors(node)
        for node in tree.body
        if isinstance(node, ast.AsyncFunctionDef | ast.FunctionDef)
    }


def function_arguments(function: ast.AsyncFunctionDef | ast.FunctionDef) -> tuple[str, ...]:
    arguments: list[str] = []
    for arg in [
        *function.args.posonlyargs,
        *function.args.args,
        *function.args.kwonlyargs,
    ]:
        annotation = annotation_text(arg.annotation)
        arguments.append(f"{arg.arg} {annotation}" if annotation else arg.arg)
    if function.args.vararg is not None:
        annotation = annotation_text(function.args.vararg.annotation)
        arguments.append(
            f"*{function.args.vararg.arg} {annotation}"
            if annotation
            else f"*{function.args.vararg.arg}"
        )
    if function.args.kwarg is not None:
        annotation = annotation_text(function.args.kwarg.annotation)
        arguments.append(
            f"**{function.args.kwarg.arg} {annotation}"
            if annotation
            else f"**{function.args.kwarg.arg}"
        )
    return tuple(arguments)


def docstring_summary(function: ast.AsyncFunctionDef | ast.FunctionDef) -> str:
    docstring = ast.get_docstring(function)
    if not docstring:
        raise ValueError(f"{function.name} docstring is not found")
    return " ".join(docstring.strip().split())


def function_metadata(functions_path: Path) -> dict[str, FunctionMetadata]:
    tree = ast.parse(functions_path.read_text(encoding="utf-8"), filename=str(functions_path))
    ports = imported_integration_ports(tree)
    metadata: dict[str, FunctionMetadata] = {}
    local_calls: dict[str, tuple[str, ...]] = {}
    direct_errors: dict[str, tuple[FunctionErrorMetadata, ...]] = {}
    for node in tree.body:
        if not isinstance(node, ast.AsyncFunctionDef | ast.FunctionDef):
            continue
        if node.name.startswith("_"):
            continue
        local_calls[node.name] = called_local_functions(node)
        direct_errors[node.name] = direct_function_errors(node)
        metadata[node.name] = FunctionMetadata(
            description=docstring_summary(node),
            arguments=function_arguments(node),
            return_type=annotation_text(node.returns),
            integration_resources=called_integration_resources(node, ports),
            query_functions=called_query_functions(node),
        )
    external_errors = imported_project_common_errors(functions_path)
    resolved_errors = {
        name: list(errors) for name, errors in {**external_errors, **direct_errors}.items()
    }
    changed = True
    while changed:
        changed = False
        for name, calls in local_calls.items():
            errors = resolved_errors.setdefault(name, [])
            for called_name in calls:
                for error in resolved_errors.get(called_name, ()):
                    if error in errors:
                        continue
                    errors.append(error)
                    changed = True
    metadata = {
        name: FunctionMetadata(
            value.description,
            value.arguments,
            value.return_type,
            value.integration_resources,
            value.query_functions,
            tuple(resolved_errors.get(name, ())),
        )
        for name, value in metadata.items()
    }
    return metadata


def sequence_label(step: SequenceStep) -> str:
    return step.description


def predicate_condition_label(step: SequenceStep) -> str:
    if step.condition_label is not None:
        return step.condition_label
    return condition_label_from_description(step.description, negated=False)


def condition_label_from_description(description: str, *, negated: bool) -> str:
    suffix = "かを判定する。"
    if not description.endswith(suffix):
        validation_suffix = "を検証する。"
        if description.endswith(validation_suffix):
            condition = description.removesuffix("する。")
            if negated:
                return f"{condition}できない場合。"
            return f"{condition}できる場合。"
        return description
    condition = description.removesuffix(suffix)
    if negated:
        if condition.endswith("可能"):
            return f"{condition}でない場合。"
        if condition.endswith("である"):
            return f"{condition.removesuffix('である')}でない場合。"
        if condition.endswith("存在する"):
            return f"{condition.removesuffix('存在する')}存在しない場合。"
        if condition.endswith("できる"):
            return f"{condition.removesuffix('できる')}できない場合。"
        if condition.endswith("済み"):
            return f"{condition}でない場合。"
        return f"{condition}が成立しない場合。"
    if condition.endswith("可能"):
        return f"{condition}な場合。"
    if condition.endswith("済み"):
        return f"{condition}である場合。"
    return f"{condition}場合。"


def function_target(function_name: str) -> str:
    head, _separator, tail = function_name.partition("_")
    if head in PREDICATES:
        return tail
    return tail


def is_predicate_function(function_name: str) -> bool:
    head, _separator, _tail = function_name.partition("_")
    return head in PREDICATES


def integration_resources(integrations_root: Path) -> frozenset[str]:
    if not integrations_root.exists():
        return frozenset()
    return frozenset(
        path.name
        for path in sorted(integrations_root.iterdir())
        if path.is_dir() and (path / "port.py").exists()
    )


def integration_resource_for_target(
    target: str,
    resources: frozenset[str],
) -> str | None:
    for resource in sorted(resources, key=len, reverse=True):
        if target == resource or target.startswith(f"{resource}_"):
            return resource
    return None


def endpoint_sequence_steps(
    function: ast.AsyncFunctionDef | ast.FunctionDef,
    metadata: dict[str, FunctionMetadata],
) -> list[SequenceStep]:
    return [
        item
        for item in endpoint_sequence_items(
            function, metadata, endpoint_success_status_code(function)
        )
        if isinstance(item, SequenceStep)
    ]


def endpoint_success_status_code(function: ast.AsyncFunctionDef | ast.FunctionDef) -> int:
    for decorator in function.decorator_list:
        if not is_router_decorator(decorator) or not isinstance(decorator, ast.Call):
            continue
        if code := http_status_code(keyword_value(decorator, "status_code")):
            return code
    return 200


def endpoint_sequence_items(
    function: ast.AsyncFunctionDef | ast.FunctionDef,
    metadata: dict[str, FunctionMetadata],
    success_status_code: int,
) -> list[SequenceItem]:
    items: list[SequenceItem] = []

    class Visitor(ast.NodeVisitor):
        def visit_If(self, node: ast.If) -> None:
            guarded_function_name = guarded_api_function_name(node)
            if guarded_function_name is not None:
                for error_return in error_returns_from_if_body(node, metadata):
                    items.append(error_return)
                append_sequence_step(
                    guarded_function_name,
                    success_condition_label_for_guard(node.test, guarded_function_name, metadata),
                )
                for child in node.orelse:
                    self.visit(child)
                return
            error_returns = error_returns_from_if_body(node, metadata)
            if error_returns:
                self.visit(node.test)
                items.extend(error_returns)
                for child in node.orelse:
                    self.visit(child)
                return
            self.generic_visit(node)

        def visit_Await(self, node: ast.Await) -> None:
            function_name = awaited_api_function_name(node)
            if function_name is None:
                self.generic_visit(node)
                return
            append_sequence_step(function_name)

        def visit_Return(self, node: ast.Return) -> None:
            if api_error_response_call(node) is not None:
                return
            if error_response_for_router_error_call(node) is not None:
                return
            if node.value is not None:
                function_name = awaited_api_function_name(node.value)
                if function_name is not None:
                    append_sequence_step(function_name)
            items.append(SuccessReturnStep(success_status_code))

        def visit_Try(self, node: ast.Try) -> None:
            for child in node.body:
                self.visit(child)
            for handler in node.handlers:
                if excepts_router_handled_exceptions(handler) and any(
                    returns_error_response_for_router_error(statement) for statement in handler.body
                ):
                    items.append(
                        ErrorReturnStep(
                            HTTP_500_INTERNAL_SERVER_ERROR,
                            ROUTER_ERROR_CONDITION,
                            ROUTER_ERROR_DETAIL,
                        )
                    )
                else:
                    for child in handler.body:
                        self.visit(child)
            for child in [*node.orelse, *node.finalbody]:
                self.visit(child)

    def append_sequence_step(function_name: str, condition_label: str | None = None) -> None:
        if function_name not in metadata:
            raise ValueError(f"{function_name} metadata is not found")
        function_metadata = metadata[function_name]
        items.append(sequence_step_from_metadata(function_name, function_metadata, condition_label))
        for error in function_metadata.errors:
            items.append(ErrorReturnStep(error.status_code, error.summary, error.detail))

    Visitor().visit(function)
    return dedupe_sequence_items(items)


def sequence_step_from_metadata(
    function_name: str,
    function_metadata: FunctionMetadata,
    condition_label: str | None = None,
) -> SequenceStep:
    return SequenceStep(
        function_name=function_name,
        target=function_target(function_name),
        description=function_metadata.description,
        arguments=function_metadata.arguments,
        return_type=function_metadata.return_type,
        integration_resources=function_metadata.integration_resources,
        query_functions=function_metadata.query_functions,
        condition_label=condition_label,
    )


def dedupe_sequence_items(items: list[SequenceItem]) -> list[SequenceItem]:
    deduped: list[SequenceItem] = []
    seen_errors: set[ErrorReturnStep] = set()
    seen_successes: set[SuccessReturnStep] = set()
    for item in items:
        if isinstance(item, ErrorReturnStep):
            if item in seen_errors:
                continue
            seen_errors.add(item)
        if isinstance(item, SuccessReturnStep):
            if item in seen_successes:
                continue
            seen_successes.add(item)
        deduped.append(item)
    return deduped


def has_api_error_response_return(nodes: list[ast.stmt]) -> bool:
    return any(
        isinstance(node, ast.Return) and api_error_response_call(node) is not None for node in nodes
    )


def guarded_api_function_name(node: ast.If) -> str | None:
    if not has_api_error_response_return(node.body):
        return None
    test = (
        node.test.operand
        if isinstance(node.test, ast.UnaryOp) and isinstance(node.test.op, ast.Not)
        else node.test
    )
    function_name = api_function_call_name(test)
    if function_name is None or not is_predicate_function(function_name):
        return None
    return function_name


def success_condition_label_for_guard(
    test: ast.AST,
    function_name: str,
    metadata: dict[str, FunctionMetadata],
) -> str | None:
    function_metadata = metadata.get(function_name)
    if function_metadata is None:
        return None
    error_condition_is_negated = isinstance(test, ast.UnaryOp) and isinstance(test.op, ast.Not)
    return condition_label_from_description(
        function_metadata.description,
        negated=not error_condition_is_negated,
    )


def api_function_call_name(node: ast.AST) -> str | None:
    call = node
    if isinstance(call, ast.Await):
        call = call.value
    if not isinstance(call, ast.Call):
        return None
    function = call.func
    if not isinstance(function, ast.Attribute):
        return None
    if not isinstance(function.value, ast.Name):
        return None
    if function.value.id != "api_functions":
        return None
    return function.attr


def condition_label_from_test(
    node: ast.AST,
    metadata: dict[str, FunctionMetadata],
) -> str | None:
    if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.Not):
        return condition_label_from_negated_test(node.operand, metadata)
    return condition_label_from_positive_test(node, metadata)


def condition_label_from_positive_test(
    node: ast.AST,
    metadata: dict[str, FunctionMetadata],
) -> str | None:
    function_name = api_function_call_name(node)
    if function_name is None:
        return None
    function_metadata = metadata.get(function_name)
    if function_metadata is None:
        return None
    return condition_label_from_description(function_metadata.description, negated=False)


def condition_label_from_negated_test(
    node: ast.AST,
    metadata: dict[str, FunctionMetadata],
) -> str | None:
    function_name = api_function_call_name(node)
    if function_name is None:
        return None
    function_metadata = metadata.get(function_name)
    if function_metadata is None:
        return None
    return condition_label_from_description(function_metadata.description, negated=True)


def api_error_response_call(node: ast.AST) -> ast.Call | None:
    if not isinstance(node, ast.Return):
        return None
    call = node.value
    if not isinstance(call, ast.Call):
        return None
    if not isinstance(call.func, ast.Name) or call.func.id != "api_error_response":
        return None
    return call


def error_response_for_router_error_call(node: ast.AST) -> ast.Call | None:
    if not isinstance(node, ast.Return):
        return None
    call = node.value
    if not isinstance(call, ast.Call):
        return None
    if not isinstance(call.func, ast.Name) or call.func.id != "error_response_for_router_error":
        return None
    return call


def excepts_router_handled_exceptions(node: ast.ExceptHandler) -> bool:
    exception_type = node.type
    if isinstance(exception_type, ast.Name):
        return exception_type.id == "ROUTER_HANDLED_EXCEPTIONS"
    if isinstance(exception_type, ast.Tuple):
        return any(
            isinstance(element, ast.Name) and element.id == "ROUTER_HANDLED_EXCEPTIONS"
            for element in exception_type.elts
        )
    return False


def returns_error_response_for_router_error(node: ast.stmt) -> bool:
    return isinstance(node, ast.Return) and error_response_for_router_error_call(node) is not None


def fallback_error_return_condition(detail: str | None) -> str:
    if detail:
        return f"router が {detail} と判定した場合。"
    return "router がエラー条件に該当すると判定した場合。"


def endpoint_error_returns(
    function: ast.AsyncFunctionDef | ast.FunctionDef,
    metadata: dict[str, FunctionMetadata],
) -> list[ErrorReturnStep]:
    error_returns: list[ErrorReturnStep] = []

    class Visitor(ast.NodeVisitor):
        def __init__(self) -> None:
            self.conditions: list[str] = []

        def visit_If(self, node: ast.If) -> None:
            condition = condition_label_from_test(node.test, metadata)
            if condition is None:
                for child in node.body:
                    self.visit(child)
            else:
                self.conditions.append(condition)
                for child in node.body:
                    self.visit(child)
                self.conditions.pop()
            for child in node.orelse:
                self.visit(child)

        def visit_Return(self, node: ast.Return) -> None:
            call = api_error_response_call(node)
            if call is None or len(call.args) < 2:
                return
            status_code = http_status_code(call.args[0])
            if status_code is None:
                return
            detail = literal_string(call.args[1]) or ""
            condition = (
                self.conditions[-1] if self.conditions else fallback_error_return_condition(detail)
            )
            error_returns.append(ErrorReturnStep(status_code, condition, detail))

    for statement in function.body:
        Visitor().visit(statement)
    return error_returns


def error_returns_from_if_body(
    node: ast.If,
    metadata: dict[str, FunctionMetadata],
) -> list[ErrorReturnStep]:
    condition = condition_label_from_test(node.test, metadata)
    error_returns: list[ErrorReturnStep] = []
    for statement in node.body:
        if not isinstance(statement, ast.Return):
            continue
        call = api_error_response_call(statement)
        if call is None or len(call.args) < 2:
            continue
        status_code = http_status_code(call.args[0])
        if status_code is None:
            continue
        detail = literal_string(call.args[1]) or ""
        error_returns.append(
            ErrorReturnStep(
                status_code,
                condition or fallback_error_return_condition(detail),
                detail,
            )
        )
    return error_returns


def endpoint_exception_error_returns(
    steps: list[SequenceStep], metadata: dict[str, FunctionMetadata]
) -> list[ErrorReturnStep]:
    error_returns: list[ErrorReturnStep] = []
    seen: set[tuple[int, str, str]] = set()
    for step in steps:
        function_metadata = metadata.get(step.function_name)
        if function_metadata is None:
            continue
        for error in function_metadata.errors:
            key = (error.status_code, error.summary, error.detail)
            if key in seen:
                continue
            seen.add(key)
            error_returns.append(ErrorReturnStep(error.status_code, error.summary, error.detail))
    return error_returns


def sql_action(filename: str) -> str:
    lowered = filename.lower()
    for action, label in SQL_ACTIONS.items():
        if action in lowered:
            return label
    return "参照"


def sql_tables(source: str) -> list[str]:
    tables: list[str] = []
    for match in SQL_TABLE_PATTERN.finditer(source):
        table = match.group(1)
        if table not in tables:
            tables.append(table)
    return tables


def query_sql_filename(node: ast.AsyncFunctionDef | ast.FunctionDef) -> str | None:
    for call in ast.walk(node):
        if not isinstance(call, ast.BinOp):
            continue
        if not isinstance(call.op, ast.Div):
            continue
        if not isinstance(call.left, ast.Name) or call.left.id != "SQL_DIR":
            continue
        filename = literal_string(call.right)
        if filename is not None:
            return filename
    return None


def query_sql_summaries(queries_path: Path) -> dict[str, str]:
    if not queries_path.exists():
        return {}
    tree = ast.parse(queries_path.read_text(encoding="utf-8"), filename=str(queries_path))
    summaries: dict[str, str] = {}
    for node in tree.body:
        if not isinstance(node, ast.AsyncFunctionDef | ast.FunctionDef):
            continue
        filename = query_sql_filename(node)
        summary = ast.get_docstring(node)
        if filename is not None and summary:
            summaries[filename] = " ".join(summary.strip().split())
    return summaries


def query_sql_filenames(queries_path: Path) -> dict[str, str]:
    if not queries_path.exists():
        return {}
    tree = ast.parse(queries_path.read_text(encoding="utf-8"), filename=str(queries_path))
    filenames: dict[str, str] = {}
    for node in tree.body:
        if not isinstance(node, ast.AsyncFunctionDef | ast.FunctionDef):
            continue
        filename = query_sql_filename(node)
        if filename is not None:
            filenames[node.name] = filename
    return filenames


def sql_sequence_steps(
    sql_dir: Path,
    summaries: dict[str, str] | None = None,
    filenames: set[str] | None = None,
) -> list[SqlStep]:
    if not sql_dir.exists():
        return []
    steps: list[SqlStep] = []
    summaries = summaries or {}
    for path in sorted(sql_dir.glob("*.sql")):
        if filenames is not None and path.name not in filenames:
            continue
        tables = sql_tables(path.read_text(encoding="utf-8"))
        if tables:
            steps.append(
                SqlStep(
                    filename=path.name,
                    action=sql_action(path.name),
                    tables=tuple(tables),
                    summary=summaries.get(path.name, SQL_RECORD_ACTIONS[sql_action(path.name)]),
                )
            )
    return steps


def api_sequence_from_dir(
    api_dir: Path,
    api_root: Path,
    integrations_root: Path | None = None,
) -> ApiSequence:
    router_path = api_dir / "router.py"
    functions_path = api_dir / "functions.py"
    tree = ast.parse(router_path.read_text(encoding="utf-8"), filename=str(router_path))
    function = endpoint_function(tree)
    metadata = function_metadata(functions_path)
    items = endpoint_sequence_items(function, metadata, endpoint_success_status_code(function))
    steps = [item for item in items if isinstance(item, SequenceStep)]
    error_returns = [item for item in items if isinstance(item, ErrorReturnStep)]
    success_returns = [item for item in items if isinstance(item, SuccessReturnStep)]
    query_filenames = query_sql_filenames(api_dir / "queries.py")
    called_query_filenames = {
        query_filenames[query_function]
        for step in steps
        for query_function in step.query_functions
        if query_function in query_filenames
    }
    relative = api_dir.relative_to(api_root)
    domain, api = relative.parts
    return ApiSequence(
        domain=domain,
        api=api,
        endpoint_name=function.name,
        operation_id=endpoint_operation_id(function),
        steps=steps,
        error_returns=error_returns,
        success_returns=success_returns,
        sql_steps=sql_sequence_steps(
            api_dir / "sql",
            query_sql_summaries(api_dir / "queries.py"),
            called_query_filenames or None,
        ),
        integration_resources=(
            integration_resources(integrations_root)
            if integrations_root is not None
            else frozenset()
        ),
        items=items,
        method=endpoint_route_method(function),
        path=endpoint_route_path(function),
        status_codes=endpoint_status_codes(function),
    )


def api_dirs(api_root: Path) -> list[Path]:
    return sorted(
        path.parent for path in api_root.glob("*/*/router.py") if "__pycache__" not in path.parts
    )


def render_sequence_markdown(sequence: ApiSequence) -> str:
    resource_targets: list[str] = []
    for step in sequence.steps:
        if is_predicate_function(step.function_name):
            continue
        for resource in step.integration_resources:
            if resource not in resource_targets:
                resource_targets.append(resource)

    def step_resource(step: SequenceStep) -> str | None:
        if step.integration_resources:
            return step.integration_resources[0]
        return None

    sql_steps_by_filename = {step.filename: step for step in sequence.sql_steps}

    def sql_steps_for_step(step: SequenceStep) -> list[SqlStep]:
        query_filenames = query_sql_filenames_for_step(step, sequence.sql_steps)
        return [
            sql_steps_by_filename[filename]
            for filename in query_filenames
            if filename in sql_steps_by_filename
        ]

    def append_sql_steps(step: SequenceStep) -> None:
        step_sql_steps = sql_steps_for_step(step)
        for sql_step in step_sql_steps:
            tables = ", ".join(sql_step.tables)
            indent = "  " + ("  " * alt_depth)
            label = step.description if len(step_sql_steps) == 1 else sql_step.summary
            lines.append(
                f"{indent}API->>DB: {label}"
                f"<br/>SQL {sql_step.filename}<br/>テーブル {tables}"
            )

    lines = [
        GENERATED_COMMENT,
        "",
        f"# {sequence.api} sequence",
        "",
        "```mermaid",
        "sequenceDiagram",
        "  autonumber",
        "  participant User as User",
        "  participant API as API",
    ]
    for target in resource_targets:
        lines.append(
            f"  participant {participant_id('R', target)} as Resource: {snake_to_title(target)}"
        )
    if sequence.sql_steps:
        lines.append("  participant DB as DB")

    lines.append(f"  User->>API: {sequence.method} {sequence.path}")

    rendered_items = sequence.items or [*sequence.steps, *sequence.error_returns]
    alt_depth = 0
    success_return: SuccessReturnStep | None = None
    for item in rendered_items:
        if isinstance(item, SuccessReturnStep):
            success_return = item
            continue

        if isinstance(item, ErrorReturnStep):
            indent = "  " + ("  " * alt_depth)
            lines.append(f"{indent}alt {item.condition}")
            lines.append(
                f"{indent}  API-->>User: {http_status_code_label(item.status_code)}"
                f"<br/>{item.detail}"
            )
            lines.append(f"{indent}end")
            continue

        step = item
        label = sequence_label(step)
        if is_predicate_function(step.function_name):
            indent = "  " + ("  " * alt_depth)
            append_sql_steps(step)
            lines.append(f"{indent}alt {predicate_condition_label(step)}")
            alt_depth += 1
            continue
        selected_resource = step_resource(step)
        indent = "  " + ("  " * alt_depth)
        if selected_resource is None and sql_steps_for_step(step):
            append_sql_steps(step)
            continue
        if selected_resource is None:
            lines.append(f"{indent}API->>API: {label}")
        else:
            resource_id = participant_id("R", selected_resource)
            lines.append(f"{indent}API->>{resource_id}: {label}")
            append_sql_steps(step)

    if success_return is not None:
        indent = "  " + ("  " * alt_depth)
        lines.append(f"{indent}API-->>User: {http_status_code_label(success_return.status_code)}")

    for depth in range(alt_depth - 1, -1, -1):
        indent = "  " + ("  " * depth)
        lines.append(f"{indent}end")

    lines.extend(["```", ""])
    return "\n".join(lines)


def query_sql_filenames_for_step(step: SequenceStep, sql_steps: list[SqlStep]) -> list[str]:
    filenames: list[str] = []
    for query_function in step.query_functions:
        suffix = f"_{query_function}.sql"
        for sql_step in sql_steps:
            if sql_step.filename == f"{query_function}.sql" or sql_step.filename.endswith(suffix):
                filenames.append(sql_step.filename)
                break
    return filenames


def output_path(sequence: ApiSequence, docs_root: Path) -> Path:
    return docs_root / sequence.domain / sequence.api / "sequence_gen.md"


def generate_sequences(
    api_root: Path,
    docs_root: Path,
    integrations_root: Path = Path("src/app/integrations"),
) -> dict[Path, str]:
    rendered: dict[Path, str] = {}
    for directory in api_dirs(api_root):
        sequence = api_sequence_from_dir(directory, api_root, integrations_root)
        rendered[output_path(sequence, docs_root)] = render_sequence_markdown(sequence)
    return rendered


def changed_outputs(rendered: dict[Path, str]) -> list[Path]:
    changed: list[Path] = []
    for path, content in rendered.items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            changed.append(path)
    return changed


def write_outputs(rendered: dict[Path, str]) -> None:
    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def render_changed(paths: Iterable[Path]) -> str:
    return "\n".join(str(path) for path in paths)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate API sequence Mermaid specs.")
    parser.add_argument("--api-root", type=Path, default=Path("src/app/apis"))
    parser.add_argument("--docs-root", type=Path, default=Path("docs/spec/40.apis"))
    parser.add_argument(
        "--integrations-root",
        type=Path,
        default=Path("src/app/integrations"),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Only check generated sequence files are up to date.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    rendered = generate_sequences(args.api_root, args.docs_root, args.integrations_root)
    changed = changed_outputs(rendered)
    if args.check:
        if changed:
            print(render_changed(changed))
            return 1
        return 0
    write_outputs(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
