#!/usr/bin/env python3
# ruff: noqa: E501
"""Generate and verify API-level operational message catalogs for Lazunex.

This tool is intentionally static: it does not import application modules.  It
parses API directories with ``ast`` and performs three checks before generating
Markdown:

1. Application code does not call the stdlib logger directly.
2. API code emits logs only through the Lazunex wrapper in ``app.core.logging``.
3. Each wrapper call uses a message_id that is documented in the API message
   catalog when strict CI mode is enabled.

Default usage from the repository root::

    python src/tools/generate_api_message_catalog.py
    python src/tools/generate_api_message_catalog.py --check
    python src/tools/generate_api_message_catalog.py --strict --enforce-logger-wrapper

Expected API layout::

    src/app/apis/{domain}/{api}/
      router.py
      functions.py
      message_catalog.py   # recommended primary source

Generated outputs::

    docs/spec/40.apis/{domain}/{api}/messages_gen.md
    docs/spec/40.apis/messages_index_gen.md
"""

from __future__ import annotations

import argparse
import ast
import difflib
import json
import re
import sys
from collections import Counter
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import Any, cast

if __package__ in {None, ""}:
    sys.path.append(str(Path(__file__).resolve().parents[1]))

from tools.generate_api_sequences import (
    HTTP_STATUS_REASON_PHRASES,
    ErrorReturnStep,
    api_sequence_from_dir,
    endpoint_error_returns,
    endpoint_function,
    function_metadata,
)

DEFAULT_API_ROOT = Path("src/app/apis")
DEFAULT_SCAN_ROOT = Path("src/app")
DEFAULT_DOCS_ROOT = Path("docs/spec/40.apis")
DEFAULT_OUTPUT_NAME = "messages_gen.md"
GENERATED_COMMENT = "<!-- generated by src/tools/generate_api_message_catalog.py; do not edit. -->"

LEVEL_ORDER: dict[str, int] = {
    "DEBUG": 10,
    "INFO": 20,
    "WARNING": 30,
    "ERROR": 40,
    "CRITICAL": 50,
}

REQUIRED_FIELDS_BY_LEVEL: dict[str, tuple[str, ...]] = {
    "DEBUG": (),
    "INFO": ("summary",),
    "WARNING": ("why_production",),
    "ERROR": ("check_procedure", "context_model", "runbook"),
    "CRITICAL": ("remediation_procedure", "context_model", "runbook", "escalation"),
}

ROUTE_METHODS = {"get", "post", "put", "patch", "delete", "options", "head"}
CATALOG_FILENAMES = (
    "message_catalog.py",
    "messages.py",
    "operational_messages.py",
    "ops.py",
)
CATALOG_VARIABLE_NAMES = {
    "MESSAGE_CATALOG",
    "MESSAGES",
    "LOG_MESSAGES",
    "OPERATIONAL_MESSAGES",
    "MESSAGE_DEFINITIONS",
}
LOG_CONTEXT_SCHEMA_VARIABLE_NAMES = {
    "OPERATIONAL_LOG_CONTEXT_SCHEMA",
    "LOG_CONTEXT_SCHEMA",
}
LOG_CONTEXT_MODEL_CALL_NAMES = {
    "operational_log_context_model",
}
CATALOG_CALL_NAMES = {
    "MessageDefinition",
    "MessageCatalogEntry",
    "LogMessage",
    "OperationalMessage",
    "OperationalEventDefinition",
    "define_message",
    "message_definition",
    "catalog_message",
}
MESSAGE_ID_KW_NAMES = (
    "message_id",
    "messageId",
    "code",
    "event_id",
    "eventId",
)
CATALOG_ID_FIELD_NAMES = (
    "catalog_id",
    "catalogId",
    "message_catalog_id",
    "messageCatalogId",
    "message_number",
    "messageNumber",
)
LEVEL_KW_NAMES = ("level", "severity")

FIELD_ALIASES: dict[str, str] = {
    "messageId": "message_id",
    "code": "message_id",
    "event_id": "message_id",
    "eventId": "message_id",
    "id": "catalog_id",
    "catalogId": "catalog_id",
    "message_catalog_id": "catalog_id",
    "messageCatalogId": "catalog_id",
    "message_number": "catalog_id",
    "messageNumber": "catalog_id",
    "severity": "level",
    "description": "summary",
    "title": "summary",
    "condition": "when",
    "trigger": "when",
    "how_to_check": "check_procedure",
    "check": "check_procedure",
    "remediation": "remediation_procedure",
    "remedy": "remediation_procedure",
    "action": "operator_action",
    "response": "operator_action",
    "context": "context_model",
    "contexts": "context_model",
    "runbook_url": "runbook",
    "status": "status_code",
    "statusCode": "status_code",
}

CONTEXT_BY_LEVEL: dict[str, str] = {
    "DEBUG": "traceId, requestId",
    "INFO": "traceId, requestId, actorPrincipalId, api.method, api.route, api.statusCode, metrics.durationMs",
    "WARNING": "traceId, requestId, actorPrincipalId, api.method, api.route, api.statusCode, resource.*, error.code",
    "ERROR": "traceId, requestId, actorPrincipalId, api.method, api.route, resource.*, aws.service, aws.action, error.code, error.message, metrics.durationMs",
    "CRITICAL": "traceId, requestId, actorPrincipalId, api.method, api.route, resource.*, aws.service, aws.action, operationId, error.*",
}

# Direct logger policy -----------------------------------------------------

LOGGER_METHODS = {"debug", "info", "warning", "warn", "error", "exception", "critical", "log"}
LOGGER_FACTORY_METHODS = {"getLogger", "get_logger"}
LOGGER_VARIABLE_NAMES = {"logger", "log", "LOGGER", "LOG", "_logger", "_log"}
FORBIDDEN_LOG_MODULES = {"logging", "structlog", "loguru"}
DEFAULT_ALLOWED_DIRECT_LOGGER_FILES = ("src/app/core/logging.py",)

# Lazunex wrapper detection ------------------------------------------------

WRAPPER_MODULES = {
    "app.core.logging",
    "src.app.core.logging",
}
WRAPPER_FACTORY_NAMES = {
    "get_operation_logger",
    "get_operational_logger",
}
WRAPPER_HELPER_NAMES = {
    "emit_message",
    "emit_api_message",
    "log_message",
    "record_message",
    "record_operational_event",
    "emit_operational_event",
}
WRAPPER_METHOD_LEVELS: dict[str, str | None] = {
    "emit": None,
    "debug": "DEBUG",
    "info": "INFO",
    "warning": "WARNING",
    "warn": "WARNING",
    "error": "ERROR",
    "exception": "ERROR",
    "critical": "CRITICAL",
    "log_message": None,
    "record_message": None,
    "record_operational_event": None,
    "emit_operational_event": None,
}
WRAPPER_VARIABLE_HINTS = {
    "ops_logger",
    "op_logger",
    "operational_logger",
    "message_logger",
    "catalog_logger",
}


@dataclass(frozen=True)
class ApiMeta:
    domain: str
    api: str
    operation_id: str
    method: str
    path: str
    router_source: str


@dataclass(frozen=True)
class WrapperCall:
    """One call to app.core.logging's operational wrapper."""

    catalog_id: str | None
    message_id: str | None
    level_hint: str | None
    source: str
    function_name: str | None
    wrapper: str
    context_keys: tuple[str, ...] = field(default_factory=tuple)
    catalog_fields: Mapping[str, Any] = field(default_factory=lambda: {})


@dataclass(frozen=True)
class DirectLoggerViolation:
    path: Path
    line: int
    kind: str
    detail: str

    def display(self, root: Path) -> str:
        return f"{repo_relative(self.path, root)}:{self.line}: {self.kind}: {self.detail}"


@dataclass(frozen=True)
class MessageDefinition:
    catalog_id: str
    message_id: str
    level: str
    status_code: int | None = None
    detail: str = ""
    summary: str = ""
    when: str = ""
    why_production: str = ""
    check_procedure: str = ""
    remediation_procedure: str = ""
    context_model: str = ""
    runbook: str = ""
    escalation: str = ""
    operator_action: str = ""
    source: str = ""
    tags: tuple[str, ...] = field(default_factory=tuple)
    emitted_from: tuple[str, ...] = field(default_factory=tuple)
    inferred: bool = False

    @property
    def sort_key(self) -> tuple[int, str, str]:
        if self.catalog_id:
            return (0, self.catalog_id, self.message_id)
        return (1, f"{LEVEL_ORDER.get(self.level, 999):03d}", self.message_id)

    @property
    def description(self) -> str:
        if self.when:
            return self.when
        if self.why_production:
            return self.why_production
        return self.summary

    def with_emitted_from(self, locations: Iterable[str]) -> MessageDefinition:
        current = set(self.emitted_from)
        current.update(locations)
        return replace(self, emitted_from=tuple(sorted(current)))

    def missing_required_fields(self) -> tuple[str, ...]:
        missing: list[str] = []
        for field_name in REQUIRED_FIELDS_BY_LEVEL.get(
            self.level, ()
        ):  # unknown level handled separately
            value = getattr(self, field_name)
            if not str(value).strip():
                missing.append(field_name)
        return tuple(missing)


@dataclass(frozen=True)
class ApiCatalog:
    meta: ApiMeta
    messages: tuple[MessageDefinition, ...]
    wrapper_calls: tuple[WrapperCall, ...]
    explicit_message_ids: frozenset[str]
    router_error_returns: tuple[ErrorReturnStep, ...] = ()
    has_router_error_handler_return: bool = False


@dataclass(frozen=True)
class WriteResult:
    path: Path
    changed: bool


def repo_relative(path: Path, root: Path) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def escape_markdown(value: Any) -> str:
    text = "" if value is None else str(value)
    text = text.replace("\n", "<br>")
    return text.replace("|", "\\|")


def normalize_level(value: Any, fallback: str = "INFO") -> str:
    if value is None:
        return fallback
    text = str(value).strip()
    if not text:
        return fallback
    text = text.split(".")[-1].upper()
    if text == "WARN":
        return "WARNING"
    if text not in LEVEL_ORDER:
        return fallback
    return text


def normalize_message_id(value: Any) -> str:
    text = str(value).strip()
    text = text.replace(" ", "_")
    return text


def normalize_catalog_id(value: Any) -> str:
    text = str(value).strip()
    return text


def normalize_status_code(value: Any) -> int | None:
    if isinstance(value, int):
        return value
    text = str(value).strip()
    if not text:
        return None
    if text.isdecimal():
        return int(text)
    match = re.search(r"HTTP_(?P<code>[0-9]{3})_", text)
    if match is not None:
        return int(match.group("code"))
    return None


def get_keyword(call: ast.Call, names: Sequence[str]) -> ast.AST | None:
    wanted = set(names)
    for keyword in call.keywords:
        if keyword.arg in wanted:
            return keyword.value
    return None


def call_name(node: ast.Call) -> str:
    func = node.func
    if isinstance(func, ast.Name):
        return func.id
    if isinstance(func, ast.Attribute):
        return func.attr
    return ""


def dotted_name(node: ast.AST) -> str | None:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        base = dotted_name(node.value)
        if base:
            return f"{base}.{node.attr}"
        return node.attr
    return None


def literal_value(node: ast.AST | None) -> Any:
    """Best-effort conversion of AST expressions into stable display values."""
    if node is None:
        return None
    if isinstance(node, ast.Constant):
        return node.value
    if isinstance(node, (ast.List, ast.Tuple, ast.Set)):
        return [literal_value(element) for element in node.elts]
    if isinstance(node, ast.Dict):
        converted: dict[str, Any] = {}
        for key, value in zip(node.keys, node.values, strict=False):
            if key is None:
                continue
            key_value = literal_value(key)
            if key_value is None:
                continue
            converted[str(key_value)] = literal_value(value)
        return converted
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return dotted_name(node)
    if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id == "dict":
        return {
            keyword.arg: literal_value(keyword.value) for keyword in node.keywords if keyword.arg
        }
    if isinstance(node, ast.Call) and call_name(node) in LOG_CONTEXT_MODEL_CALL_NAMES:
        arg_aliases = [
            log_context_alias_from_field_name(str(literal_value(arg)))
            for arg in node.args
            if isinstance(literal_value(arg), str)
        ]
        keyword_aliases = [
            log_context_alias_from_field_name(keyword.arg)
            for keyword in node.keywords
            if keyword.arg
        ]
        return ", ".join([*arg_aliases, *keyword_aliases])
    try:
        return ast.unparse(node)
    except Exception:  # pragma: no cover - defensive for malformed ASTs
        return "<expr>"


def as_display(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    if isinstance(value, (list, tuple, set)):
        items = cast("Iterable[Any]", value)
        return ", ".join(as_display(item) for item in items)
    if isinstance(value, Mapping):
        return json.dumps(
            dict(cast("Mapping[str, Any]", value)), ensure_ascii=False, sort_keys=True
        )
    return str(value)


def log_context_alias_from_field_name(field_name: str) -> str:
    dotted_prefixes = {"api", "resource", "aws", "metrics", "error"}
    prefix, separator, rest = field_name.partition("_")
    if separator and prefix in dotted_prefixes:
        return f"{prefix}.{snake_to_lower_camel(rest)}"
    return snake_to_lower_camel(field_name)


def snake_to_lower_camel(value: str) -> str:
    parts = value.split("_")
    if not parts:
        return value
    return parts[0] + "".join(part[:1].upper() + part[1:] for part in parts[1:])


def log_context_schema_path(root: Path) -> Path:
    return root / "src/app/core/logging.py"


def default_log_context_schema() -> dict[str, str]:
    return {
        "traceId": "リクエストとログを横断して追跡する相関IDです。",
        "requestId": "実行基盤またはアプリケーションが付与するリクエストIDです。",
        "actorPrincipalId": "APIを呼び出した認証主体IDです。",
        "request.sourceIp": "呼び出し元IPアドレスです。",
        "request.userAgent": "呼び出し元User-Agentです。",
        "request.actorType": "リクエスト実行主体の種別です。",
        "api.method": "呼び出されたAPIのHTTP methodです。",
        "api.route": "呼び出されたAPI routeです。",
        "api.statusCode": "API responseとして返したHTTP status codeです。",
        "resource.*": "操作対象リソースを識別するIDや属性です。",
        "resource.projectId": "操作対象Projectを一意に識別するIDです。",
        "resource.apiId": "操作対象APIを一意に識別するIDです。",
        "resource.accessRequestId": "操作対象API利用申請を一意に識別するIDです。",
        "aws.service": "連携先AWS service名です。",
        "aws.action": "連携先AWS API action名です。",
        "metrics.durationMs": "処理に要した時間をミリ秒で表した値です。",
        "operationId": "非同期provisioningや補償処理を追跡するoperation IDです。",
        "error.*": "エラーの分類、詳細、例外種別などをまとめた情報です。",
        "error.code": "エラー分類を表す機械処理向けコードです。",
        "error.message": "エラー内容を運用者が理解するための説明です。",
        "error.exceptionType": "捕捉された例外の型名です。",
    }


def normalize_log_context_schema(value: Any) -> dict[str, str]:
    if not isinstance(value, Mapping):
        return {}
    context_schema = cast("Mapping[Any, Any]", value)
    schema: dict[str, str] = {}
    for raw_name, raw_definition in context_schema.items():
        name = str(raw_name).strip()
        if not name:
            continue
        if isinstance(raw_definition, Mapping):
            definition = cast("Mapping[str, Any]", raw_definition)
            description = as_display(definition.get("description"))
        else:
            description = as_display(raw_definition)
        if description.strip():
            schema[name] = description
    return schema


def field_description_from_call(call: ast.Call) -> str:
    if call_name(call) != "Field":
        return ""
    for keyword in call.keywords:
        if keyword.arg != "description":
            continue
        return as_display(literal_value(keyword.value))
    return ""


def pydantic_log_context_schema(module: ast.Module) -> dict[str, str]:
    model_names: set[str] = set()
    for node in ast.walk(module):
        if not isinstance(node, (ast.Assign, ast.AnnAssign)):
            continue
        value_node = node.value
        if not isinstance(value_node, ast.Name):
            continue
        target_names: set[str] = set()
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    target_names.add(target.id)
        elif isinstance(node.target, ast.Name):
            target_names.add(node.target.id)
        if target_names.intersection(LOG_CONTEXT_SCHEMA_VARIABLE_NAMES):
            model_names.add(value_node.id)

    schema: dict[str, str] = {}
    for node in module.body:
        if not isinstance(node, ast.ClassDef) or node.name not in model_names:
            continue
        for statement in node.body:
            if not isinstance(statement, ast.AnnAssign):
                continue
            if not isinstance(statement.target, ast.Name):
                continue
            if not isinstance(statement.value, ast.Call):
                continue
            description = field_description_from_call(statement.value)
            if description:
                schema[log_context_alias_from_field_name(statement.target.id)] = description
    return schema


def api_error_resource_schema(api_dir: Path) -> dict[str, str]:
    module = read_python_ast(api_dir / "schemas.py")
    if module is None:
        return {}
    schema: dict[str, str] = {}
    for node in module.body:
        if not isinstance(node, ast.ClassDef) or node.name != "ErrorResource":
            continue
        for statement in node.body:
            if not isinstance(statement, ast.AnnAssign):
                continue
            if not isinstance(statement.target, ast.Name):
                continue
            if not isinstance(statement.value, ast.Call):
                continue
            description = field_description_from_call(statement.value)
            if description:
                schema[f"resource.{snake_to_lower_camel(statement.target.id)}"] = description
    return schema


def load_log_context_schema(root: Path) -> dict[str, str]:
    path = log_context_schema_path(root)
    module = read_python_ast(path)
    schema: dict[str, str] = {}
    if module is not None:
        schema.update(pydantic_log_context_schema(module))
        for node in ast.walk(module):
            value_node: ast.AST | None = None
            target_names: set[str] = set()
            if isinstance(node, ast.Assign):
                value_node = node.value
                for target in node.targets:
                    if isinstance(target, ast.Name):
                        target_names.add(target.id)
            elif isinstance(node, ast.AnnAssign):
                value_node = node.value
                if isinstance(node.target, ast.Name):
                    target_names.add(node.target.id)
            if value_node is not None and target_names.intersection(
                LOG_CONTEXT_SCHEMA_VARIABLE_NAMES
            ):
                schema.update(normalize_log_context_schema(literal_value(value_node)))
    return {**default_log_context_schema(), **schema}


def context_model_items(context_model: str) -> tuple[str, ...]:
    return tuple(item.strip() for item in context_model.split(",") if item.strip())


def context_field_description(name: str, schema: Mapping[str, str]) -> str:
    if name in schema:
        return schema[name]
    parts = name.split(".")
    for index in range(len(parts) - 1, 0, -1):
        wildcard = ".".join([*parts[:index], "*"])
        if wildcard in schema:
            return schema[wildcard]
    return f"`{name}` に出力されるログコンテキストです。"


def render_context_model_table(context_model: str, schema: Mapping[str, str]) -> list[str]:
    items = context_model_items(context_model)
    if not items:
        return [
            "#### 出力項目",
            "",
            "出力項目は定義されていません。",
            "",
        ]
    lines = [
        "#### 出力項目",
        "",
        "| 出力項目 | 説明 |",
        "| :--- | :--- |",
    ]
    for item in items:
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{escape_markdown(item)}`",
                    escape_markdown(context_field_description(item, schema)),
                ]
            )
            + " |"
        )
    lines.append("")
    return lines


def read_python_ast(path: Path) -> ast.Module | None:
    try:
        source = path.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"[WARN] cannot read {path}: {exc}", file=sys.stderr)
        return None
    try:
        return ast.parse(source, filename=str(path))
    except SyntaxError as exc:
        print(f"[WARN] skip syntax-error file {path}: {exc}", file=sys.stderr)
        return None


def extract_mapping_from_call(call: ast.Call) -> dict[str, Any]:
    data: dict[str, Any] = {}
    if call.args:
        data["message_id"] = literal_value(call.args[0])
    if len(call.args) > 1:
        data["level"] = literal_value(call.args[1])
    for keyword in call.keywords:
        if keyword.arg is None:
            continue
        key = FIELD_ALIASES.get(keyword.arg, keyword.arg)
        data[key] = literal_value(keyword.value)
    return data


def normalize_definition(
    data: Mapping[str, Any], source: str, *, inferred: bool = False
) -> MessageDefinition | None:
    normalized: dict[str, Any] = {}
    for raw_key, raw_value in data.items():
        key = FIELD_ALIASES.get(str(raw_key), str(raw_key))
        normalized[key] = raw_value

    message_id = normalize_message_id(
        normalized.get("message_id") or normalized.get("message") or normalized.get("name") or ""
    )
    if not message_id:
        return None

    tags_value = normalized.get("tags") or ()
    tags: tuple[str, ...]
    if isinstance(tags_value, str):
        tags = (tags_value,)
    elif isinstance(tags_value, Iterable):
        tag_items = cast("Iterable[Any]", tags_value)  # type: ignore[redundant-cast]
        tags = tuple(str(item) for item in tag_items)
    else:
        tags = ()

    level = normalize_level(normalized.get("level"), fallback="INFO")
    return MessageDefinition(
        catalog_id=normalize_catalog_id(normalized.get("catalog_id") or ""),
        message_id=message_id,
        level=level,
        status_code=normalize_status_code(normalized.get("status_code")),
        detail=as_display(normalized.get("detail")),
        summary=as_display(normalized.get("summary")),
        when=as_display(normalized.get("when")),
        why_production=as_display(normalized.get("why_production")),
        check_procedure=as_display(normalized.get("check_procedure")),
        remediation_procedure=as_display(normalized.get("remediation_procedure")),
        context_model=as_display(normalized.get("context_model")),
        runbook=as_display(normalized.get("runbook")),
        escalation=as_display(normalized.get("escalation")),
        operator_action=as_display(normalized.get("operator_action")),
        source=source,
        tags=tags,
        inferred=inferred,
    )


def definitions_from_literal(value: Any, source: str) -> list[MessageDefinition]:
    definitions: list[MessageDefinition] = []
    if isinstance(value, list):
        list_items = cast("list[Any]", value)  # type: ignore[redundant-cast]
        for item in list_items:
            if isinstance(item, Mapping):
                definition = normalize_definition(cast("Mapping[str, Any]", item), source)
                if definition:
                    definitions.append(definition)
    elif isinstance(value, Mapping):
        mapping_items = cast("Mapping[Any, Any]", value)  # type: ignore[redundant-cast]
        for key, item in mapping_items.items():
            if isinstance(item, Mapping):
                data: dict[str, Any] = dict(cast("Mapping[str, Any]", item))
                data.setdefault("message_id", key)
                definition = normalize_definition(data, source)
                if definition:
                    definitions.append(definition)
            elif isinstance(item, str):
                definition = normalize_definition({"message_id": key, "summary": item}, source)
                if definition:
                    definitions.append(definition)
    return definitions


def parse_catalog_file(path: Path, root: Path) -> list[MessageDefinition]:
    module = read_python_ast(path)
    if module is None:
        return []
    definitions: list[MessageDefinition] = []
    source = repo_relative(path, root)
    for node in ast.walk(module):
        value_node: ast.AST | None = None
        target_names: set[str] = set()
        if isinstance(node, ast.Assign):
            value_node = node.value
            for target in node.targets:
                if isinstance(target, ast.Name):
                    target_names.add(target.id)
        elif isinstance(node, ast.AnnAssign):
            value_node = node.value
            if isinstance(node.target, ast.Name):
                target_names.add(node.target.id)

        if value_node is not None and target_names.intersection(CATALOG_VARIABLE_NAMES):
            definitions.extend(definitions_from_literal(literal_value(value_node), source))

        if isinstance(node, ast.Call) and call_name(node) in CATALOG_CALL_NAMES:
            definition = normalize_definition(
                extract_mapping_from_call(node), f"{source}:{node.lineno}"
            )
            if definition:
                definitions.append(definition)
    return definitions


def parse_route_meta(router_path: Path, root: Path, api_dir: Path) -> list[ApiMeta]:
    domain = api_dir.parent.name
    api = api_dir.name
    module = read_python_ast(router_path)
    if module is None:
        return [ApiMeta(domain, api, api, "", "", repo_relative(router_path, root))]

    metas: list[ApiMeta] = []
    for node in ast.walk(module):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for decorator in node.decorator_list:
            if not isinstance(decorator, ast.Call):
                continue
            func = decorator.func
            if not isinstance(func, ast.Attribute) or func.attr not in ROUTE_METHODS:
                continue
            path_value = literal_value(decorator.args[0]) if decorator.args else ""
            operation_id_node = get_keyword(decorator, ("operation_id", "operationId"))
            operation_id = (
                as_display(literal_value(operation_id_node)) if operation_id_node else node.name
            )
            metas.append(
                ApiMeta(
                    domain=domain,
                    api=api,
                    operation_id=operation_id or node.name,
                    method=func.attr.upper(),
                    path=as_display(path_value),
                    router_source=f"{repo_relative(router_path, root)}:{node.lineno}",
                )
            )
    if not metas:
        metas.append(ApiMeta(domain, api, api, "", "", repo_relative(router_path, root)))
    return metas


def message_id_from_call(call: ast.Call) -> str | None:
    kw_node = get_keyword(call, MESSAGE_ID_KW_NAMES)
    if kw_node is not None:
        value = literal_value(kw_node)
        if isinstance(value, str) and value.strip():
            return normalize_message_id(value)
    for arg in call.args[:2]:
        if (
            isinstance(arg, ast.Call)
            and dotted_name(arg.func) == "router_error_message_id"
            and arg.args
        ):
            operation_id = literal_value(arg.args[0])
            if isinstance(operation_id, str) and operation_id.strip():
                return normalize_message_id(f"{operation_id}.router_api_function_error")
        value = literal_value(arg)
        if (
            isinstance(value, str)
            and value.strip()
            and re.match(r"^[A-Za-z][A-Za-z0-9_.:-]*$", value)
        ):
            return normalize_message_id(value)
    return None


def catalog_id_from_call(call: ast.Call) -> str | None:
    kw_node = get_keyword(call, CATALOG_ID_FIELD_NAMES)
    if kw_node is None:
        return None
    value = literal_value(kw_node)
    if isinstance(value, str) and value.strip():
        return normalize_catalog_id(value)
    return None


def level_hint_from_wrapper_method(method_name: str, call: ast.Call) -> str | None:
    direct = WRAPPER_METHOD_LEVELS.get(method_name)
    if direct:
        return direct
    level_node = get_keyword(call, LEVEL_KW_NAMES)
    if level_node is not None:
        return normalize_level(literal_value(level_node))
    if method_name == "exception":
        return "ERROR"
    return None


def literal_context_keys(call: ast.Call) -> tuple[str, ...]:
    context_node = get_keyword(call, ("context", "extra", "payload"))
    if (
        isinstance(context_node, ast.Call)
        and dotted_name(context_node.func) == "router_log_context"
    ):
        return router_log_context_keys(context_node)
    value = literal_value(context_node)
    if isinstance(value, Mapping):
        mapping = cast("Mapping[Any, Any]", value)  # type: ignore[redundant-cast]
        return tuple(sorted(str(key) for key in mapping))
    return ()


def router_log_context_keys(call: ast.Call) -> tuple[str, ...]:
    keys = {"api.statusCode", "error.code", "error.message"}
    if get_keyword(call, ("caller",)) is not None:
        keys.add("actorPrincipalId")
    if get_keyword(call, ("request_context",)) is not None:
        keys.update(("traceId", "request.sourceIp", "request.userAgent", "request.actorType"))
    if get_keyword(call, ("error",)) is not None:
        keys.add("error.exceptionType")

    resource_node = get_keyword(call, ("resource",))
    if isinstance(resource_node, ast.Dict):
        for key_node in resource_node.keys:
            key_value = literal_value(key_node)
            if isinstance(key_value, str) and key_value:
                keys.add(f"resource.{key_value}")
    return tuple(sorted(keys))


def catalog_fields_from_call(call: ast.Call) -> dict[str, Any]:
    fields: dict[str, Any] = {}
    for keyword in call.keywords:
        if keyword.arg is None:
            continue
        if keyword.arg in {"context", "extra", "payload"}:
            continue
        key = FIELD_ALIASES.get(keyword.arg, keyword.arg)
        if key in {
            "catalog_id",
            "message_id",
            "level",
            "summary",
            "status_code",
            "detail",
            "when",
            "why_production",
            "check_procedure",
            "remediation_procedure",
            "context_model",
            "operator_action",
            "runbook",
            "escalation",
            "tags",
        }:
            if key == "summary" and isinstance(keyword.value, ast.Call):
                fields[key] = router_error_api_function_summary(keyword.value)
            else:
                fields[key] = literal_value(keyword.value)
    return fields


def router_error_api_function_summary(call: ast.Call) -> str | None:
    if dotted_name(call.func) != "router_error_summary" or not call.args:
        return None
    summary = literal_value(call.args[0])
    if not isinstance(summary, str):
        return None
    return summary.replace(
        "Routerで捕捉した例外により",
        "Routerで捕捉したApiFunctionErrorにより",
    )


def is_dotted_call(node: ast.Call, modules: set[str], names: set[str]) -> bool:
    dotted = dotted_name(node.func)
    if not dotted:
        return False
    for module_name in modules:
        for name in names:
            if dotted == f"{module_name}.{name}":
                return True
    return False


class WrapperCallVisitor(ast.NodeVisitor):
    def __init__(self, path: Path, root: Path) -> None:
        self.path = path
        self.root = root
        self.current_function: str | None = None
        self.factory_names: set[str] = set(WRAPPER_FACTORY_NAMES)
        self.helper_names: set[str] = set(WRAPPER_HELPER_NAMES)
        self.module_names: set[str] = set()
        self.wrapper_variables: set[str] = set(WRAPPER_VARIABLE_HINTS)
        self.calls: list[WrapperCall] = []

    def visit_Import(self, node: ast.Import) -> None:
        for alias in node.names:
            if alias.name in WRAPPER_MODULES:
                self.module_names.add(alias.asname or alias.name.split(".")[-1])
        self.generic_visit(node)

    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:
        module = node.module or ""
        if module in WRAPPER_MODULES:
            for alias in node.names:
                imported_name = alias.name
                local_name = alias.asname or alias.name
                if imported_name in WRAPPER_FACTORY_NAMES:
                    self.factory_names.add(local_name)
                if imported_name in WRAPPER_HELPER_NAMES:
                    self.helper_names.add(local_name)
                if imported_name == "OperationalLogger":
                    self.wrapper_variables.add(local_name)
        if module == "app.core":
            for alias in node.names:
                if alias.name == "logging":
                    self.module_names.add(alias.asname or alias.name)
        self.generic_visit(node)

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        previous = self.current_function
        self.current_function = node.name
        self.generic_visit(node)
        self.current_function = previous

    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None:
        previous = self.current_function
        self.current_function = node.name
        self.generic_visit(node)
        self.current_function = previous

    def visit_Assign(self, node: ast.Assign) -> None:
        if isinstance(node.value, ast.Call) and self._is_wrapper_factory_call(node.value):
            for target in node.targets:
                for name in assigned_names(target):
                    self.wrapper_variables.add(name)
        self.generic_visit(node)

    def visit_AnnAssign(self, node: ast.AnnAssign) -> None:
        if isinstance(node.value, ast.Call) and self._is_wrapper_factory_call(node.value):
            for name in assigned_names(node.target):
                self.wrapper_variables.add(name)
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        wrapper_name: str | None = None
        level_hint: str | None = None
        if isinstance(node.func, ast.Name) and node.func.id in self.helper_names:
            wrapper_name = node.func.id
            level_hint = level_hint_from_wrapper_method(node.func.id, node)
        elif isinstance(node.func, ast.Attribute):
            receiver = dotted_name(node.func.value)
            if (
                isinstance(node.func.value, ast.Name)
                and node.func.value.id in self.wrapper_variables
            ):
                if node.func.attr in WRAPPER_METHOD_LEVELS:
                    wrapper_name = f"{node.func.value.id}.{node.func.attr}"
                    level_hint = level_hint_from_wrapper_method(node.func.attr, node)
            elif receiver in self.module_names and node.func.attr in WRAPPER_HELPER_NAMES:
                wrapper_name = f"{receiver}.{node.func.attr}"
                level_hint = level_hint_from_wrapper_method(node.func.attr, node)
        if wrapper_name:
            self.calls.append(
                WrapperCall(
                    catalog_id=catalog_id_from_call(node),
                    message_id=message_id_from_call(node),
                    level_hint=level_hint,
                    source=f"{repo_relative(self.path, self.root)}:{node.lineno}",
                    function_name=self.current_function,
                    wrapper=wrapper_name,
                    context_keys=literal_context_keys(node),
                    catalog_fields=catalog_fields_from_call(node),
                )
            )
        self.generic_visit(node)

    def _is_wrapper_factory_call(self, call: ast.Call) -> bool:
        if isinstance(call.func, ast.Name) and call.func.id in self.factory_names:
            return True
        if isinstance(call.func, ast.Attribute):
            receiver = dotted_name(call.func.value)
            if receiver in self.module_names and call.func.attr in WRAPPER_FACTORY_NAMES:
                return True
        return is_dotted_call(call, WRAPPER_MODULES, WRAPPER_FACTORY_NAMES)


def assigned_names(node: ast.AST) -> set[str]:
    if isinstance(node, ast.Name):
        return {node.id}
    if isinstance(node, (ast.Tuple, ast.List)):
        names: set[str] = set()
        for element in node.elts:
            names.update(assigned_names(element))
        return names
    return set()


def api_python_files(api_dir: Path) -> list[Path]:
    paths: list[Path] = []
    for path in sorted(api_dir.rglob("*.py")):
        parts = set(path.parts)
        if "generated" in parts or "__pycache__" in parts:
            continue
        if path.name in {"schemas.py", "samples.py", "contract.py", "__init__.py"}:
            continue
        paths.append(path)
    return paths


def parse_wrapper_calls(api_dir: Path, root: Path) -> list[WrapperCall]:
    calls: list[WrapperCall] = []
    for path in api_python_files(api_dir):
        if path.name in CATALOG_FILENAMES:
            continue
        module = read_python_ast(path)
        if module is None:
            continue
        visitor = WrapperCallVisitor(path, root)
        visitor.visit(module)
        calls.extend(visitor.calls)
    return calls


class DirectLoggerVisitor(ast.NodeVisitor):
    def __init__(self, path: Path, root: Path) -> None:
        self.path = path
        self.root = root
        self.logging_module_aliases: set[str] = set()
        self.logging_factory_aliases: set[str] = set()
        self.logging_function_aliases: set[str] = set()
        self.logger_variables: set[str] = set(LOGGER_VARIABLE_NAMES)
        self.wrapper_factory_names: set[str] = set(WRAPPER_FACTORY_NAMES)
        self.wrapper_helper_names: set[str] = set(WRAPPER_HELPER_NAMES)
        self.wrapper_module_names: set[str] = set()
        self.wrapper_variables: set[str] = set(WRAPPER_VARIABLE_HINTS)
        self.violations: list[DirectLoggerViolation] = []

    def visit_Import(self, node: ast.Import) -> None:
        for alias in node.names:
            top = alias.name.split(".")[0]
            local = alias.asname or top
            if alias.name in WRAPPER_MODULES:
                self.wrapper_module_names.add(alias.asname or alias.name.split(".")[-1])
                continue
            if top in FORBIDDEN_LOG_MODULES:
                self.logging_module_aliases.add(local)
                self._add(node, "forbidden-import", f"direct import of {alias.name!r}")
        self.generic_visit(node)

    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:
        module = node.module or ""
        if module in WRAPPER_MODULES:
            for alias in node.names:
                local_name = alias.asname or alias.name
                if alias.name in WRAPPER_FACTORY_NAMES:
                    self.wrapper_factory_names.add(local_name)
                if alias.name in WRAPPER_HELPER_NAMES:
                    self.wrapper_helper_names.add(local_name)
            self.generic_visit(node)
            return
        if module == "app.core":
            for alias in node.names:
                if alias.name == "logging":
                    self.wrapper_module_names.add(alias.asname or alias.name)
            self.generic_visit(node)
            return
        if module.split(".")[0] in FORBIDDEN_LOG_MODULES:
            for alias in node.names:
                local = alias.asname or alias.name
                if alias.name in LOGGER_FACTORY_METHODS:
                    self.logging_factory_aliases.add(local)
                if alias.name in LOGGER_METHODS:
                    self.logging_function_aliases.add(local)
                self._add(node, "forbidden-import", f"direct import from {module!r}: {alias.name}")
        self.generic_visit(node)

    def visit_Assign(self, node: ast.Assign) -> None:
        if isinstance(node.value, ast.Call):
            if self._is_wrapper_factory_call(node.value):
                for target in node.targets:
                    self.wrapper_variables.update(assigned_names(target))
            if self._is_logging_factory_call(node.value):
                for target in node.targets:
                    names = assigned_names(target)
                    self.logger_variables.update(names)
                    for name in names:
                        self._add(node, "direct-logger-factory", f"{name} = logging.getLogger(...)")
        self.generic_visit(node)

    def visit_AnnAssign(self, node: ast.AnnAssign) -> None:
        if isinstance(node.value, ast.Call):
            if self._is_wrapper_factory_call(node.value):
                self.wrapper_variables.update(assigned_names(node.target))
            if self._is_logging_factory_call(node.value):
                names = assigned_names(node.target)
                self.logger_variables.update(names)
                for name in names:
                    self._add(node, "direct-logger-factory", f"{name} = logging.getLogger(...)")
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        if self._is_logging_factory_call(node):
            self._add(node, "direct-logger-factory", "logging.getLogger(...) is not allowed")
        if isinstance(node.func, ast.Name):
            if node.func.id in self.logging_function_aliases:
                self._add(node, "direct-logger-call", f"{node.func.id}(...) is not allowed")
        elif isinstance(node.func, ast.Attribute):
            receiver = dotted_name(node.func.value)
            if (
                receiver in self.logging_module_aliases
                and node.func.attr in LOGGER_METHODS | LOGGER_FACTORY_METHODS
            ):
                self._add(
                    node, "direct-logger-call", f"{receiver}.{node.func.attr}(...) is not allowed"
                )
            if isinstance(node.func.value, ast.Name):
                base_name = node.func.value.id
                if base_name in self.wrapper_variables:
                    self.generic_visit(node)
                    return
                if base_name in self.logger_variables and node.func.attr in LOGGER_METHODS:
                    self._add(
                        node,
                        "direct-logger-call",
                        f"{base_name}.{node.func.attr}(...) is not allowed",
                    )
        self.generic_visit(node)

    def _is_logging_factory_call(self, call: ast.Call) -> bool:
        if isinstance(call.func, ast.Name) and call.func.id in self.logging_factory_aliases:
            return True
        if isinstance(call.func, ast.Attribute):
            receiver = dotted_name(call.func.value)
            if receiver in self.logging_module_aliases and call.func.attr in LOGGER_FACTORY_METHODS:
                return True
        return False

    def _is_wrapper_factory_call(self, call: ast.Call) -> bool:
        if isinstance(call.func, ast.Name) and call.func.id in self.wrapper_factory_names:
            return True
        if isinstance(call.func, ast.Attribute):
            receiver = dotted_name(call.func.value)
            if receiver in self.wrapper_module_names and call.func.attr in WRAPPER_FACTORY_NAMES:
                return True
        return False

    def _add(self, node: ast.AST, kind: str, detail: str) -> None:
        self.violations.append(
            DirectLoggerViolation(
                path=self.path,
                line=getattr(node, "lineno", 0),
                kind=kind,
                detail=detail,
            )
        )


def iter_python_files(scan_root: Path) -> Iterable[Path]:
    if not scan_root.exists():
        return []
    skip_parts = {".venv", "venv", "__pycache__", "generated", ".mypy_cache", ".ruff_cache"}
    paths: list[Path] = []
    for path in sorted(scan_root.rglob("*.py")):
        if set(path.parts).intersection(skip_parts):
            continue
        paths.append(path)
    return paths


def find_direct_logger_violations(
    *,
    root: Path,
    scan_root: Path,
    allowed_files: Sequence[str],
) -> list[DirectLoggerViolation]:
    allowed = {
        ((root / item).resolve() if not Path(item).is_absolute() else Path(item).resolve())
        for item in allowed_files
    }
    violations: list[DirectLoggerViolation] = []
    for path in iter_python_files(scan_root):
        if path.resolve() in allowed:
            continue
        module = read_python_ast(path)
        if module is None:
            continue
        visitor = DirectLoggerVisitor(path, root)
        visitor.visit(module)
        violations.extend(visitor.violations)
    return violations


def output_path_for_api(meta: ApiMeta, docs_root: Path, output_name: str) -> Path:
    return docs_root / meta.domain / meta.api / output_name


def default_http_messages(meta: ApiMeta) -> list[MessageDefinition]:
    return router_error_messages_from_returns(meta, ())


def router_error_messages_from_returns(
    meta: ApiMeta,
    error_returns: Iterable[ErrorReturnStep],
) -> list[MessageDefinition]:
    prefix = meta.operation_id
    route = f"{meta.method} {meta.path}".strip() or f"{meta.domain}/{meta.api}"
    common_source = f"router:{route}"
    messages: dict[tuple[int, str], MessageDefinition] = {}
    for error_return in error_returns:
        level = "ERROR" if error_return.status_code >= 500 else "WARNING"
        suffix = message_suffix_for_error_return(error_return)
        message_id = f"{prefix}.{suffix}"
        context_model = CONTEXT_BY_LEVEL[level]
        summary = summary_for_error_return(error_return)
        action = action_for_error_return(error_return)
        messages.setdefault(
            (error_return.status_code, message_id),
            MessageDefinition(
                catalog_id="",
                message_id=message_id,
                level=level,
                summary=summary,
                when=error_return.condition,
                why_production=why_production_for_error_return(error_return),
                check_procedure=check_procedure_for_error_return(error_return),
                remediation_procedure=remediation_for_error_return(error_return),
                operator_action=action,
                context_model=context_model,
                runbook=runbook_for_error_return(error_return),
                source=common_source,
                inferred=True,
            ),
        )
    return list(messages.values())


def message_suffix_for_error_return(error_return: ErrorReturnStep) -> str:
    if error_return.status_code >= 500:
        return "router_api_function_error"
    slug = re.sub(r"[^A-Za-z0-9]+", "_", error_return.detail).strip("_").lower()
    if not slug:
        slug = HTTP_STATUS_REASON_PHRASES.get(error_return.status_code, "client_error").lower()
    return slug


def summary_for_error_return(error_return: ErrorReturnStep) -> str:
    if error_return.status_code >= 500:
        return "Routerで捕捉した例外によりAPI処理が失敗した。"
    condition = error_return.condition.removesuffix("。")
    condition = condition.removesuffix("場合")
    return f"{condition}ため、リクエストを拒否した。"


def why_production_for_error_return(error_return: ErrorReturnStep) -> str:
    if error_return.status_code >= 500:
        return ""
    return "利用者操作、権限、リソース状態、冪等性衝突などの拒否理由を運用で追跡するため。"


def check_procedure_for_error_return(error_return: ErrorReturnStep) -> str:
    if error_return.status_code >= 500:
        return "traceId/requestIdでログを検索し、routerで捕捉された例外種別と直前のmessage_idを確認する。"
    return ""


def remediation_for_error_return(error_return: ErrorReturnStep) -> str:
    if error_return.status_code >= 500:
        return "原因を特定し、再試行可能な処理は同一operationとして再実行する。必要に応じてrollbackまたはhotfixを行う。"
    return ""


def action_for_error_return(error_return: ErrorReturnStep) -> str:
    if error_return.status_code >= 500:
        return "同一routeの5xx率、直近deploy、DB migration、外部依存の状態を確認する。"
    return "traceId、actorPrincipalId、対象resource、request条件を確認し、利用者操作または状態不整合の原因を切り分ける。"


def runbook_for_error_return(error_return: ErrorReturnStep) -> str:
    if error_return.status_code >= 500:
        return "RUNBOOK-unexpected-api-failure"
    if error_return.status_code in {400, 422}:
        return "RUNBOOK-api-client-error"
    if error_return.status_code == 403:
        return "RUNBOOK-authorization-forbidden"
    if error_return.status_code == 409:
        return "RUNBOOK-state-conflict-idempotency"
    return "RUNBOOK-api-client-error"


def legacy_default_http_messages(meta: ApiMeta) -> list[MessageDefinition]:
    prefix = meta.operation_id
    route = f"{meta.method} {meta.path}".strip() or f"{meta.domain}/{meta.api}"
    common_source = f"default:{route}"
    return [
        MessageDefinition(
            catalog_id="",
            message_id=f"{prefix}.request_succeeded",
            level="INFO",
            summary="API処理が正常終了した。",
            when="2xx responseを返す直前。",
            operator_action="通常対応不要。latencyや件数の傾向監視のみ行う。",
            context_model=CONTEXT_BY_LEVEL["INFO"],
            source=common_source,
            inferred=True,
        ),
        MessageDefinition(
            catalog_id="",
            message_id=f"{prefix}.validation_failed",
            level="WARNING",
            summary="入力値またはヘッダのvalidationでリクエストを拒否した。",
            when="400または422 responseを返す直前。",
            why_production="クライアント実装不備、仕様不一致、または不正入力の増加を検知するため。",
            operator_action="同一callerや同一routeで急増している場合、request例とIF仕様を突合し利用者へ修正依頼する。",
            context_model=CONTEXT_BY_LEVEL["WARNING"],
            runbook="RUNBOOK-api-client-error",
            source=common_source,
            inferred=True,
        ),
        MessageDefinition(
            catalog_id="",
            message_id=f"{prefix}.authentication_failed",
            level="WARNING",
            summary="Bearer tokenがない、無効、期限切れ、または認証検証に失敗した。",
            when="401 responseを返す直前。",
            why_production="Cognito設定、token発行、利用者実装、時刻ずれの問題を早期検知するため。",
            operator_action="traceId、client_id、token issuer、Cognito authorizer設定、直近のUser Pool変更を確認する。",
            context_model=CONTEXT_BY_LEVEL["WARNING"],
            runbook="RUNBOOK-authentication-failure",
            source=common_source,
            inferred=True,
        ),
        MessageDefinition(
            catalog_id="",
            message_id=f"{prefix}.authorization_forbidden",
            level="WARNING",
            summary="認可条件を満たさないためアクセスを拒否した。",
            when="403 responseを返す直前。",
            why_production="project権限、reviewer権限、custom scope、Usage Planの不整合を検知するため。",
            operator_action="actorPrincipalId、projectId、apiId、scopeFullName、reviewer登録、Usage Plan stage紐づけを確認する。",
            context_model=CONTEXT_BY_LEVEL["WARNING"],
            runbook="RUNBOOK-authorization-forbidden",
            source=common_source,
            inferred=True,
        ),
        MessageDefinition(
            catalog_id="",
            message_id=f"{prefix}.state_conflict",
            level="WARNING",
            summary="重複、状態不整合、または冪等性衝突によりリクエストを拒否した。",
            when="409 responseを返す直前。",
            why_production="二重実行、同時更新、途中失敗後の再送、既存subscription/requestとの競合を追跡するため。",
            operator_action="Idempotency-Key、request_hash、operationId、既存request/subscription、row_versionを確認する。",
            context_model=CONTEXT_BY_LEVEL["WARNING"],
            runbook="RUNBOOK-state-conflict-idempotency",
            source=common_source,
            inferred=True,
        ),
        MessageDefinition(
            catalog_id="",
            message_id=f"{prefix}.dependency_failed",
            level="ERROR",
            summary="外部依存またはAWS API連携に失敗した。",
            when="502または503 responseを返す直前、またはprovisioning step失敗時。",
            check_procedure="traceIdからLambdaログを検索し、operationIdでprovisioning_operations/provisioning_steps、CloudTrail、AWS API error_codeを確認する。",
            remediation_procedure="一時障害は再試行する。部分成功がある場合は成功済みstepをskipして同一operationとして再実行する。",
            operator_action="Cognito/API Gateway/Secrets Manager/DSQLの障害範囲を切り分け、必要に応じて運用リトライまたは補償処理を実行する。",
            context_model=CONTEXT_BY_LEVEL["ERROR"],
            runbook="RUNBOOK-dependency-provisioning-failure",
            source=common_source,
            inferred=True,
        ),
        MessageDefinition(
            catalog_id="",
            message_id=f"{prefix}.unexpected_failed",
            level="ERROR",
            summary="想定外例外によりAPI処理が失敗した。",
            when="500 responseを返す直前。",
            check_procedure="traceId/requestIdでCloudWatch Logsを検索し、例外種別、直前のmessage_id、resource IDs、release versionを確認する。",
            remediation_procedure="再現条件を特定し、影響範囲を確認する。必要に応じてrollbackまたはhotfixを行う。",
            operator_action="同一routeの5xx率、直近deploy、DB migration、外部依存の状態を確認する。",
            context_model=CONTEXT_BY_LEVEL["ERROR"],
            runbook="RUNBOOK-unexpected-api-failure",
            source=common_source,
            inferred=True,
        ),
    ]


def inferred_from_wrapper_call(meta: ApiMeta, call: WrapperCall) -> MessageDefinition:
    level = normalize_level(call.level_hint, fallback="INFO")
    data = dict(call.catalog_fields)
    data.setdefault("catalog_id", call.catalog_id or "")
    data.setdefault("message_id", call.message_id or f"{meta.operation_id}.undocumented_message")
    data.setdefault("level", level)
    if call.context_keys:
        data.setdefault("context_model", ", ".join(call.context_keys))
    definition = normalize_definition(data, call.source, inferred=not bool(call.catalog_fields))
    if definition is None:
        return MessageDefinition(
            catalog_id=call.catalog_id or "",
            message_id=call.message_id or f"{meta.operation_id}.undocumented_message",
            level=level,
            source=call.source,
            inferred=True,
        )
    return definition


def merge_context_model(context_model: str, calls: Sequence[WrapperCall]) -> str:
    items = list(context_model_items(context_model))
    seen = set(items)
    for call in calls:
        for key in call.context_keys:
            if key not in seen:
                items.append(key)
                seen.add(key)
    return ", ".join(items)


def collect_api_dirs(api_root: Path) -> list[Path]:
    if not api_root.exists():
        return []
    return sorted(router.parent for router in api_root.glob("*/*/router.py"))


def build_api_catalogs(
    *,
    root: Path,
    api_root: Path,
    include_http_defaults: bool,
) -> list[ApiCatalog]:
    catalogs: list[ApiCatalog] = []
    for api_dir in collect_api_dirs(api_root):
        metas = parse_route_meta(api_dir / "router.py", root, api_dir)
        catalog_defs: list[MessageDefinition] = []
        for filename in CATALOG_FILENAMES:
            path = api_dir / filename
            if path.exists():
                catalog_defs.extend(parse_catalog_file(path, root))
        wrapper_calls = parse_wrapper_calls(api_dir, root)
        explicit_ids = frozenset(
            [
                *(definition.message_id for definition in catalog_defs),
                *(call.message_id for call in wrapper_calls if call.message_id),
            ]
        )
        calls_by_id: dict[str, list[WrapperCall]] = {}
        for call in wrapper_calls:
            if call.message_id:
                calls_by_id.setdefault(call.message_id, []).append(call)

        meta = metas[0]
        definitions_by_id: dict[str, MessageDefinition] = {}
        for definition in catalog_defs:
            definitions_by_id[definition.message_id] = definition
        for message_id, calls in calls_by_id.items():
            if message_id not in definitions_by_id:
                definitions_by_id[message_id] = inferred_from_wrapper_call(meta, calls[0])
            definitions_by_id[message_id] = replace(
                definitions_by_id[message_id],
                context_model=merge_context_model(
                    definitions_by_id[message_id].context_model,
                    calls,
                ),
            )
            definitions_by_id[message_id] = definitions_by_id[message_id].with_emitted_from(
                f"{call.source} ({call.wrapper})" for call in calls
            )

        router_error_returns = (
            router_error_returns_for_api(api_dir, api_root) if include_http_defaults else ()
        )
        messages = assign_catalog_ids(
            tuple(sorted(definitions_by_id.values(), key=lambda message: message.sort_key))
        )
        catalogs.append(
            ApiCatalog(
                meta=meta,
                messages=messages,
                wrapper_calls=tuple(wrapper_calls),
                explicit_message_ids=explicit_ids,
                router_error_returns=tuple(router_error_returns),
                has_router_error_handler_return=has_router_error_handler_return(
                    api_dir / "router.py"
                ),
            )
        )
    return catalogs


def router_error_returns_for_api(api_dir: Path, api_root: Path) -> tuple[ErrorReturnStep, ...]:
    del api_root
    try:
        router_tree = ast.parse((api_dir / "router.py").read_text(encoding="utf-8"))
        function = endpoint_function(router_tree)
        metadata = function_metadata(api_dir / "functions.py")
    except OSError, SyntaxError, ValueError:
        return ()
    return tuple(endpoint_error_returns(function, metadata))


def has_router_error_handler_return(router_path: Path) -> bool:
    module = read_python_ast(router_path)
    if module is None:
        return False
    for node in ast.walk(module):
        if not isinstance(node, ast.Return):
            continue
        call = node.value
        if not isinstance(call, ast.Call):
            continue
        if isinstance(call.func, ast.Name) and call.func.id == "error_response_for_router_error":
            return True
    return False


def router_error_messages(
    api_dir: Path,
    root: Path,
    api_root: Path,
    meta: ApiMeta,
) -> list[MessageDefinition]:
    try:
        sequence = api_sequence_from_dir(api_dir, api_root)
    except OSError, SyntaxError, ValueError:
        return default_http_messages(meta)
    return router_error_messages_from_returns(meta, sequence.error_returns)


def assign_catalog_ids(messages: tuple[MessageDefinition, ...]) -> tuple[MessageDefinition, ...]:
    used_ids = {message.catalog_id for message in messages if message.catalog_id}
    next_number = 1
    assigned: list[MessageDefinition] = []
    for message in messages:
        if message.catalog_id:
            assigned.append(message)
            continue
        while f"M{next_number:03d}" in used_ids:
            next_number += 1
        catalog_id = f"M{next_number:03d}"
        used_ids.add(catalog_id)
        next_number += 1
        assigned.append(replace(message, catalog_id=catalog_id))
    return tuple(assigned)


def api_routes_summary(api_dir: Path, root: Path) -> str:
    metas = parse_route_meta(api_dir / "router.py", root, api_dir)
    return ", ".join(f"{meta.method} {meta.path} ({meta.operation_id})" for meta in metas)


def render_catalog(catalog: ApiCatalog, root: Path) -> str:
    meta = catalog.meta
    api_dir = root / DEFAULT_API_ROOT / meta.domain / meta.api
    log_context_schema = load_log_context_schema(root)
    log_context_schema.update(api_error_resource_schema(api_dir))
    route_summary = (
        api_routes_summary(api_dir, root)
        if api_dir.exists()
        else f"{meta.method} {meta.path} ({meta.operation_id})"
    )
    counter = Counter(message.level for message in catalog.messages)
    wrapper_calls_by_id = Counter(
        call.message_id for call in catalog.wrapper_calls if call.message_id
    )
    lines: list[str] = [
        GENERATED_COMMENT,
        "",
        f"# Message catalog: `{meta.domain}/{meta.api}`",
        "",
        "## API",
        "",
        "| 項目 | 値 |",
        "| :--- | :--- |",
        f"| domain | `{escape_markdown(meta.domain)}` |",
        f"| api | `{escape_markdown(meta.api)}` |",
        f"| routes | {escape_markdown(route_summary)} |",
        f"| router | `{escape_markdown(meta.router_source)}` |",
        f"| messages | {len(catalog.messages)} |",
        f"| logger wrapper calls | {len(catalog.wrapper_calls)} |",
        f"| levels | {escape_markdown(', '.join(f'{level}:{counter[level]}' for level in sorted(counter, key=lambda item: LEVEL_ORDER.get(item, 999))))} |",
        "",
        "## 生成・検証方針",
        "",
        "- WARNING以上のMessage catalogは `router.py` の `ops_logger.warning/error(...)` kwargsを一次情報にする。",
        "- `api_error_response(...)` のstatus/detailとlogger呼び出しのstatus/detailを照合する。",
        "- 実装中の `app.core.logging` ラッパー呼び出しを検出し、WARN以上はrouter内のemitとcatalog定義の一致を検証する。",
        "- `logging.getLogger(...)`、`logger.info(...)` などの直接呼び出しは許可しない。",
        "- WARNING以上は運用上の意味を持つ前提で、必要な確認手順・runbook・contextを検証対象にする。",
        "",
        "## メッセージ一覧",
        "",
        "| id | message_id | ログ概要 |",
        "| :--- | :--- | :--- |",
    ]

    for message in catalog.messages:
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{escape_markdown(message.catalog_id)}`",
                    f"`{escape_markdown(message.message_id)}`",
                    escape_markdown(message.summary),
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## ログ詳細",
            "",
        ]
    )

    for message in catalog.messages:
        action = (
            message.operator_action
            or message.remediation_procedure
            or message.check_procedure
            or "通常対応不要。"
        )
        source_parts: list[str] = []
        if message.source:
            source_parts.append(message.source)
        if message.emitted_from:
            source_parts.append("wrapper: " + ", ".join(message.emitted_from))
        if message.inferred:
            source_parts.append("inferred")
        detail_rows = [
            ("id", f"`{escape_markdown(message.catalog_id)}`"),
            ("message_id", f"`{escape_markdown(message.message_id)}`"),
            ("level", f"`{escape_markdown(message.level)}`"),
            ("status", str(message.status_code or "")),
            ("wrapper calls", str(wrapper_calls_by_id[message.message_id])),
            ("ログ概要", escape_markdown(message.summary)),
            ("説明", escape_markdown(message.description)),
            ("対応すべきこと", escape_markdown(action)),
            ("runbook", escape_markdown(message.runbook)),
            ("実装参照", escape_markdown("<br>".join(source_parts))),
        ]
        lines.extend(
            [
                f"### `{escape_markdown(message.catalog_id)}` `{escape_markdown(message.message_id)}`",
                "",
                "| 項目 | 内容 |",
                "| :--- | :--- |",
                *(f"| {label} | {value} |" for label, value in detail_rows),
                "",
                *render_context_model_table(message.context_model, log_context_schema),
            ]
        )

    lines.extend(
        [
            "## loggerラッパー呼び出し一覧",
            "",
            "| source | function | wrapper | catalog_id | message_id | level_hint | context keys |",
            "| :--- | :--- | :--- | :--- | :--- | :--- | :--- |",
        ]
    )
    if catalog.wrapper_calls:
        for call in catalog.wrapper_calls:
            lines.append(
                "| "
                + " | ".join(
                    [
                        f"`{escape_markdown(call.source)}`",
                        escape_markdown(call.function_name or ""),
                        f"`{escape_markdown(call.wrapper)}`",
                        f"`{escape_markdown(call.catalog_id or '')}`",
                        f"`{escape_markdown(call.message_id or '<missing>')}`",
                        f"`{escape_markdown(call.level_hint or '')}`",
                        escape_markdown(", ".join(call.context_keys)),
                    ]
                )
                + " |"
            )
    else:
        lines.append("| - | - | - | - | - | - | - |")

    lines.extend(
        [
            "",
            "## strict検証で要求する項目",
            "",
            "| Level | 必須項目 |",
            "| :--- | :--- |",
        ]
    )
    for level in ("WARNING", "ERROR", "CRITICAL"):
        required = ", ".join(REQUIRED_FIELDS_BY_LEVEL[level]) or "なし"
        lines.append(f"| `{level}` | {required} |")
    lines.append("")
    return "\n".join(lines)


def render_index(
    catalogs: Sequence[ApiCatalog], docs_root: Path, output_name: str, root: Path
) -> str:
    lines: list[str] = [
        GENERATED_COMMENT,
        "",
        "# API message catalog index",
        "",
        "| domain | api | route | id | message_id | level | status | ログ概要 | 出力項目 | 対応すべきこと | runbook | output |",
        "| :--- | :--- | :--- | :--- | :--- | :--- | ---: | :--- | :--- | :--- | :--- | :--- |",
    ]
    for catalog in sorted(catalogs, key=lambda item: (item.meta.domain, item.meta.api)):
        meta = catalog.meta
        output_path = output_path_for_api(meta, docs_root, output_name)
        for message in catalog.messages:
            action = (
                message.operator_action
                or message.remediation_procedure
                or message.check_procedure
                or "通常対応不要。"
            )
            lines.append(
                "| "
                + " | ".join(
                    [
                        f"`{escape_markdown(meta.domain)}`",
                        f"`{escape_markdown(meta.api)}`",
                        escape_markdown(f"{meta.method} {meta.path}".strip()),
                        f"`{escape_markdown(message.catalog_id)}`",
                        f"`{escape_markdown(message.message_id)}`",
                        f"`{escape_markdown(message.level)}`",
                        str(message.status_code or ""),
                        escape_markdown(message.summary),
                        escape_markdown(message.context_model),
                        escape_markdown(action),
                        escape_markdown(message.runbook),
                        f"`{escape_markdown(repo_relative(output_path, root))}`",
                    ]
                )
                + " |"
            )
    lines.append("")
    return "\n".join(lines)


def write_or_check(path: Path, content: str, *, check: bool) -> WriteResult:
    previous = path.read_text(encoding="utf-8") if path.exists() else None
    if previous == content:
        return WriteResult(path=path, changed=False)
    if check:
        old_lines = [] if previous is None else previous.splitlines(keepends=True)
        new_lines = content.splitlines(keepends=True)
        diff = difflib.unified_diff(
            old_lines,
            new_lines,
            fromfile=str(path),
            tofile=f"{path} (generated)",
        )
        sys.stdout.writelines(diff)
        return WriteResult(path=path, changed=True)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return WriteResult(path=path, changed=True)


def validate_catalogs(
    catalogs: Sequence[ApiCatalog],
    *,
    strict: bool,
    fail_on_undocumented_emits: bool,
    fail_on_missing_message_id: bool,
    fail_on_missing_catalog_id: bool,
    fail_on_level_mismatch: bool,
    require_api_wrapper_calls: bool,
) -> list[str]:
    errors: list[str] = []
    for catalog in catalogs:
        api_ref = f"{catalog.meta.domain}/{catalog.meta.api}"
        seen: set[str] = set()
        seen_catalog_ids: set[str] = set()
        definitions_by_id = {message.message_id: message for message in catalog.messages}
        definitions_by_catalog_id = {message.catalog_id: message for message in catalog.messages}
        wrapper_calls_by_message_id = {
            wrapper_call.message_id
            for wrapper_call in catalog.wrapper_calls
            if wrapper_call.message_id
        }
        router_return_refs = {
            (error_return.status_code, error_return.detail)
            for error_return in catalog.router_error_returns
        }
        for message in catalog.messages:
            if message.message_id in seen:
                errors.append(f"{api_ref}: duplicate message_id {message.message_id}")
            seen.add(message.message_id)
            if message.catalog_id in seen_catalog_ids:
                errors.append(f"{api_ref}: duplicate catalog id {message.catalog_id}")
            seen_catalog_ids.add(message.catalog_id)
            if message.level not in LEVEL_ORDER:
                errors.append(f"{api_ref}: {message.message_id}: unknown level {message.level}")
            if LEVEL_ORDER.get(message.level, 0) >= LEVEL_ORDER["WARNING"]:
                if "router.py" not in message.source:
                    errors.append(
                        f"{api_ref}: {message.message_id}: WARN以上のMessage catalogはrouter.pyで定義してください"
                    )
                if (
                    fail_on_undocumented_emits
                    and message.message_id not in wrapper_calls_by_message_id
                ):
                    errors.append(
                        f"{api_ref}: {message.message_id}: WARN以上のMessage catalogに対応するrouter logger emitがありません"
                    )
            if message.status_code is not None and message.detail:
                ref = (message.status_code, message.detail)
                if ref not in router_return_refs:
                    errors.append(
                        f"{api_ref}: {message.message_id}: router returnと一致しないstatus/detail "
                        f"({message.status_code}, {message.detail})"
                    )
            if strict:
                missing = message.missing_required_fields()
                if missing:
                    errors.append(
                        f"{api_ref}: {message.message_id}: level {message.level} missing required fields: "
                        + ", ".join(missing)
                    )
        if require_api_wrapper_calls and not catalog.wrapper_calls:
            errors.append(f"{api_ref}: no app.core.logging wrapper call found")
        for error_return in catalog.router_error_returns:
            matching_messages = [
                message
                for message in catalog.messages
                if message.status_code == error_return.status_code
                and message.detail == error_return.detail
            ]
            if not matching_messages:
                errors.append(
                    f"{api_ref}: router return ({error_return.status_code}, {error_return.detail}) "
                    "に対応するrouter logger emit metadataがありません"
                )
        if catalog.has_router_error_handler_return:
            expected_router_error_id = f"{catalog.meta.operation_id}.router_api_function_error"
            router_error_message = definitions_by_id.get(expected_router_error_id)
            if router_error_message is None:
                errors.append(
                    f"{api_ref}: error_response_for_router_error returnに対応する "
                    f"{expected_router_error_id} がrouter logger emit metadataにありません"
                )
            elif router_error_message.level != "ERROR":
                errors.append(
                    f"{api_ref}: {expected_router_error_id}: router error message level must be ERROR"
                )
        for wrapper_call in catalog.wrapper_calls:
            if (
                wrapper_call.level_hint in {"WARNING", "ERROR", "CRITICAL"}
                and "/router.py:" not in wrapper_call.source
            ):
                errors.append(
                    f"{api_ref}: WARN以上のlogger wrapper callはrouter.pyに限定してください "
                    f"({wrapper_call.source})"
                )
            if fail_on_missing_catalog_id and not wrapper_call.catalog_id:
                errors.append(
                    f"{api_ref}: wrapper call has no literal catalog_id ({wrapper_call.source})"
                )
            if wrapper_call.catalog_id:
                definition_by_catalog_id = definitions_by_catalog_id.get(wrapper_call.catalog_id)
                if definition_by_catalog_id is None:
                    errors.append(
                        f"{api_ref}: wrapper catalog_id {wrapper_call.catalog_id} is not documented "
                        f"({wrapper_call.source})"
                    )
                elif (
                    wrapper_call.message_id
                    and definition_by_catalog_id.message_id != wrapper_call.message_id
                ):
                    errors.append(
                        f"{api_ref}: wrapper catalog_id {wrapper_call.catalog_id} points to "
                        f"{definition_by_catalog_id.message_id}, not {wrapper_call.message_id} "
                        f"({wrapper_call.source})"
                    )
            if not wrapper_call.message_id:
                if fail_on_missing_message_id:
                    errors.append(
                        f"{api_ref}: wrapper call has no literal message_id ({wrapper_call.source})"
                    )
                continue
            if (
                fail_on_undocumented_emits
                and wrapper_call.message_id not in catalog.explicit_message_ids
            ):
                errors.append(
                    f"{api_ref}: wrapper message_id {wrapper_call.message_id} is not documented in router/catalog definitions "
                    f"({wrapper_call.source})"
                )
            definition = definitions_by_id.get(wrapper_call.message_id)
            if (
                fail_on_level_mismatch
                and definition is not None
                and wrapper_call.level_hint is not None
                and definition.level != wrapper_call.level_hint
            ):
                errors.append(
                    f"{api_ref}: {wrapper_call.message_id}: wrapper level {wrapper_call.level_hint} "
                    f"does not match catalog level {definition.level} ({wrapper_call.source})"
                )
    return errors


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate API-level operational message catalog Markdown."
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path("."),
        help="Repository root. Defaults to current directory.",
    )
    parser.add_argument(
        "--api-root", type=Path, default=DEFAULT_API_ROOT, help="API root relative to --root."
    )
    parser.add_argument(
        "--scan-root",
        type=Path,
        default=DEFAULT_SCAN_ROOT,
        help="Python source root for direct logger checks.",
    )
    parser.add_argument(
        "--docs-root", type=Path, default=DEFAULT_DOCS_ROOT, help="Docs root relative to --root."
    )
    parser.add_argument(
        "--output-name", default=DEFAULT_OUTPUT_NAME, help="Generated file name per API."
    )
    parser.add_argument(
        "--check", action="store_true", help="Do not write files; fail if generated output differs."
    )
    parser.add_argument(
        "--strict", action="store_true", help="Validate required operational fields by log level."
    )
    parser.add_argument(
        "--enforce-logger-wrapper",
        action="store_true",
        help="Fail on direct logger calls and undocumented/malformed wrapper calls.",
    )
    parser.add_argument(
        "--fail-on-direct-logger",
        action="store_true",
        help="Fail if application code imports/calls logging directly outside allowed wrapper files.",
    )
    parser.add_argument(
        "--fail-on-undocumented-emits",
        action="store_true",
        help="Fail if wrapper message_id is not explicitly declared in API message_catalog.py.",
    )
    parser.add_argument(
        "--fail-on-missing-message-id",
        action="store_true",
        help="Fail if a wrapper call does not contain a literal message_id.",
    )
    parser.add_argument(
        "--fail-on-missing-catalog-id",
        action="store_true",
        help="Fail if a wrapper call does not contain a literal catalog_id.",
    )
    parser.add_argument(
        "--fail-on-level-mismatch",
        action="store_true",
        help="Fail if wrapper method level differs from message_catalog.py level.",
    )
    parser.add_argument(
        "--require-api-wrapper-calls",
        action="store_true",
        help="Fail if an API directory has no app.core.logging wrapper calls.",
    )
    parser.add_argument(
        "--allowed-direct-logger-file",
        action="append",
        default=list(DEFAULT_ALLOWED_DIRECT_LOGGER_FILES),
        help="Repo-relative file allowed to call stdlib logging directly. Can be repeated.",
    )
    parser.add_argument(
        "--no-http-defaults",
        action="store_true",
        help="Do not include inferred common HTTP lifecycle messages.",
    )
    parser.add_argument(
        "--no-index", action="store_true", help="Do not generate the cross-API message index."
    )
    parser.add_argument(
        "--list-direct-logger",
        action="store_true",
        help="Print direct logger violations even without failing.",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    root = args.root.resolve()
    api_root = args.api_root if args.api_root.is_absolute() else root / args.api_root
    scan_root = args.scan_root if args.scan_root.is_absolute() else root / args.scan_root
    docs_root = args.docs_root if args.docs_root.is_absolute() else root / args.docs_root

    enforce_logger_wrapper = args.enforce_logger_wrapper
    fail_on_direct_logger = args.fail_on_direct_logger or enforce_logger_wrapper
    fail_on_undocumented_emits = args.fail_on_undocumented_emits or enforce_logger_wrapper
    fail_on_missing_message_id = args.fail_on_missing_message_id or enforce_logger_wrapper
    fail_on_missing_catalog_id = args.fail_on_missing_catalog_id or enforce_logger_wrapper
    fail_on_level_mismatch = args.fail_on_level_mismatch or enforce_logger_wrapper

    catalogs = build_api_catalogs(
        root=root, api_root=api_root, include_http_defaults=not args.no_http_defaults
    )
    if not catalogs:
        print(f"[ERROR] no API router.py found under {api_root}", file=sys.stderr)
        return 2

    errors: list[str] = []
    direct_logger_violations = find_direct_logger_violations(
        root=root,
        scan_root=scan_root,
        allowed_files=args.allowed_direct_logger_file,
    )
    if args.list_direct_logger:
        for violation in direct_logger_violations:
            print(f"[DIRECT_LOGGER] {violation.display(root)}")
    if fail_on_direct_logger:
        errors.extend(violation.display(root) for violation in direct_logger_violations)

    errors.extend(
        validate_catalogs(
            catalogs,
            strict=args.strict,
            fail_on_undocumented_emits=fail_on_undocumented_emits,
            fail_on_missing_message_id=fail_on_missing_message_id,
            fail_on_missing_catalog_id=fail_on_missing_catalog_id,
            fail_on_level_mismatch=fail_on_level_mismatch,
            require_api_wrapper_calls=args.require_api_wrapper_calls,
        )
    )
    if errors:
        for error in errors:
            print(f"[ERROR] {error}", file=sys.stderr)
        return 1

    results: list[WriteResult] = []
    for catalog in catalogs:
        path = output_path_for_api(catalog.meta, docs_root, args.output_name)
        results.append(write_or_check(path, render_catalog(catalog, root), check=args.check))

    if not args.no_index:
        index_path = docs_root / "messages_index_gen.md"
        results.append(
            write_or_check(
                index_path,
                render_index(catalogs, docs_root, args.output_name, root),
                check=args.check,
            )
        )

    changed = [result.path for result in results if result.changed]
    if args.check and changed:
        print(
            f"[ERROR] {len(changed)} generated message catalog file(s) are out of date.",
            file=sys.stderr,
        )
        return 1

    if changed:
        for path in changed:
            print(f"[WRITE] {repo_relative(path, root)}")
    else:
        print("[OK] message catalog outputs are up to date")
    if fail_on_direct_logger:
        print("[OK] direct logger calls are not present outside allowed wrapper files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
