from __future__ import annotations

import argparse
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import cast

import yaml

from tools.e2e_models import (
    FLOW_ID,
    TARGET_CASES,
    E2eTargetCase,
    markdown_escape,
)
from tools.generation_io import check_outputs, write_outputs

GENERATED_COMMENT = (
    "<!-- This file is generated by uv run python -m tools.generate_e2e_scenarios. "
    "Do not edit manually. -->"
)


def as_mapping(value: object) -> Mapping[str, object]:
    return cast(Mapping[str, object], value) if isinstance(value, dict) else {}


def as_sequence(value: object) -> Sequence[object]:
    return cast(Sequence[object], value) if isinstance(value, list | tuple) else ()


def load_yaml(path: Path) -> Mapping[str, object]:
    loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
    return as_mapping(loaded)


def scalar_text(value: object, default: str = "-") -> str:
    return value if isinstance(value, str) else default


def parse_component_variant(variant_id: str) -> tuple[str, str, str, str, str, str]:
    raw, data_id = variant_id.split("@", maxsplit=1) if "@" in variant_id else (variant_id, "-")
    parts = raw.split(".")
    component = parts[0] if len(parts) > 0 else "-"
    action = parts[1] if len(parts) > 1 else "-"
    project = "-"
    api = "-"
    state = parts[-1] if parts else "-"
    middle = parts[2:-1]
    for value in middle:
        if value.startswith("project_"):
            project = value
        elif value.startswith("API_"):
            api = value
    return component, action, project, api, state, data_id


def render_target_variant_rows(target_case: E2eTargetCase) -> list[str]:
    lines = [
        "| No | Component | Action | Project | API | State | Data | Variant |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for index, variant_id in enumerate(target_case.selected_variants, start=1):
        component, action, project, api, state, data_id = parse_component_variant(variant_id)
        lines.append(
            f"| V{index} | `{component}` | `{action}` | `{project}` | `{api}` | "
            f"`{state}` | `{data_id}` | `{variant_id}` |"
        )
    return lines


def render_target_prerequisites(target_case: E2eTargetCase) -> list[str]:
    lines = ["| No | 前提 | 補足 |", "|---|---|---|"]
    prerequisites = [
        "Cognito管理API用tokenを取得できる。",
        "case.id suffixでProject/APIなどのテストデータを一意に扱う。",
        "secret値、API key値、client secret値の実値をMarkdownやログに出さない。",
        "`${project_api_key}` と `${runtime_access_token}` はplaceholderとして扱う。",
    ]
    for index, text in enumerate(prerequisites, start=1):
        lines.append(f"| P{index} | {text} | - |")
    return lines


def render_target_api_steps(target_case: E2eTargetCase) -> list[str]:
    lines = [
        "| Step | Component Variant | 目的 | 期待 |",
        "|---|---|---|---|",
    ]
    for index, variant_id in enumerate(target_case.selected_variants, start=1):
        component, action, project, api, state, data_id = parse_component_variant(variant_id)
        target = " / ".join(value for value in (project, api) if value != "-") or "-"
        lines.append(
            f"| Step {index} | `{variant_id}` | `{component}.{action}` を {target} で実行 | "
            f"`{state}` / `{data_id}` |"
        )
    return lines


def render_target_runtime_assertions(target_case: E2eTargetCase) -> list[str]:
    lines = [
        "| Project | API | 期待 |",
        "|---|---|---|",
    ]
    if not target_case.runtime_assertions:
        lines.append("| - | - | - |")
        return lines
    for assertion in target_case.runtime_assertions:
        lines.append(
            f"| `{assertion.project_id}` | `{assertion.api_id}` | "
            f"`{assertion.expected}` |"
        )
    return lines


def component_yaml(component_id: str, filename: str) -> Mapping[str, object]:
    return load_yaml(Path("docs/spec/50.e2e") / FLOW_ID / "components" / component_id / filename)


def component_data_tags(component_id: str, data_id: str) -> set[str]:
    content = component_yaml(component_id, "data.manual.yaml")
    for item in as_sequence(content.get("data_profiles")):
        data = as_mapping(item)
        if data.get("id") == data_id:
            return {tag for tag in as_sequence(data.get("tags")) if isinstance(tag, str)}
    return set()


def component_evidences(component_id: str) -> Mapping[str, Mapping[str, object]]:
    content = component_yaml(component_id, "evidences.manual.yaml")
    return {
        evidence_id: evidence
        for item in as_sequence(content.get("evidences"))
        for evidence in [as_mapping(item)]
        for evidence_id in [evidence.get("id")]
        if isinstance(evidence_id, str)
    }


def component_bindings(component_id: str) -> Sequence[Mapping[str, object]]:
    content = component_yaml(component_id, "bindings.manual.yaml")
    return [as_mapping(item) for item in as_sequence(content.get("bindings"))]


def target_binding_matches(
    binding: Mapping[str, object],
    *,
    action_id: str,
    state_id: str,
    tags: set[str],
) -> bool:
    when = as_mapping(binding.get("when"))
    if when.get("action") not in (None, action_id):
        return False
    if when.get("state") not in (None, state_id):
        return False
    required_tags = {
        tag
        for tag in as_sequence(as_mapping(when.get("data_tags")).get("include"))
        if isinstance(tag, str)
    }
    return required_tags <= tags


def expand_target_value(
    value: str,
    *,
    target_case: E2eTargetCase,
    project_id: str,
    api_id: str,
) -> str:
    return (
        value.replace("${case.id}", target_case.case_id)
        .replace("${project.id}", project_id)
        .replace("${api.id}", api_id)
        .replace("${foreach.api.id}", api_id)
    )


def render_target_evidences(target_case: E2eTargetCase) -> list[str]:
    lines = [
        "| No | Component | Variant | エビデンス | 取得方法 | OK条件 | 保存名 |",
        "|---|---|---|---|---|---|---|",
    ]
    rows: list[tuple[str, str, str, str, str, str]] = []
    for variant_id in target_case.selected_variants:
        component_id, action_id, project_id, api_id, state_id, data_id = parse_component_variant(
            variant_id
        )
        tags = component_data_tags(component_id, data_id)
        matched_bindings = [
            binding
            for binding in component_bindings(component_id)
            if target_binding_matches(
                binding,
                action_id=action_id,
                state_id=state_id,
                tags=tags,
            )
        ]
        evidence_map = component_evidences(component_id)
        for binding in matched_bindings:
            for evidence_ref in as_sequence(binding.get("evidences")):
                evidence_id = as_mapping(evidence_ref).get("ref")
                if not isinstance(evidence_id, str) or evidence_id not in evidence_map:
                    continue
                evidence = evidence_map[evidence_id]
                collector = as_mapping(evidence.get("collector"))
                collector_step = scalar_text(collector.get("step"))
                rows.append(
                    (
                        component_id,
                        variant_id,
                        scalar_text(evidence.get("title")),
                        collector_step,
                        expand_target_value(
                            scalar_text(evidence.get("ok_condition")),
                            target_case=target_case,
                            project_id=project_id,
                            api_id=api_id,
                        ),
                        expand_target_value(
                            scalar_text(evidence.get("save_as")),
                            target_case=target_case,
                            project_id=project_id,
                            api_id=api_id,
                        ),
                    )
                )
    for index, (component_id, variant_id, title, collector, ok_condition, save_as) in enumerate(
        rows,
        start=1,
    ):
        lines.append(
            f"| E{index} | `{component_id}` | `{variant_id}` | "
            f"{markdown_escape(title)} | `{collector}` | "
            f"{markdown_escape(ok_condition)} | `{save_as}` |"
        )
    return lines


def render_target_scenario_markdown(target_case: E2eTargetCase) -> str:
    lines = [
        GENERATED_COMMENT,
        "",
        f"# {target_case.case_id} {target_case.goal_component}",
        "",
        "## 1. 対象",
        "",
        "| 項目 | 値 |",
        "|---|---|",
        f"| Coverage Group | `{target_case.coverage_group}` |",
        f"| Goal Component | `{target_case.goal_component}` |",
        f"| Goal Variant | `{target_case.goal_variant}` |",
        "",
        "## 2. 処理概要",
        "",
        f"{target_case.title}。",
        "",
        "## 3. 処理詳細",
        "",
        "### 前提条件",
        "",
        *render_target_prerequisites(target_case),
        "",
        "### Component Variant 手順",
        "",
        *render_target_api_steps(target_case),
        "",
        "### 選択要素",
        "",
        *render_target_variant_rows(target_case),
        "",
        "## 4. エビデンス",
        "",
        "### Component Evidence",
        "",
        *render_target_evidences(target_case),
        "",
        "### Runtime期待",
        "",
        *render_target_runtime_assertions(target_case),
        "",
        "### 後続確認",
        "",
        f"- `{target_case.goal_variant}` が生成ケース一覧のGoal Variantとして表現される。",
        "- 実行時のsecret値、API key値、client secret値は記録しない。",
        "",
    ]
    return "\n".join(lines)


def rendered_outputs(
    output_root: Path = Path("docs/spec/50.e2e"),
    *,
    spec_root: Path = Path("docs/spec/50.e2e"),
) -> Mapping[Path, str]:
    cases_root = output_root / FLOW_ID / "cases"
    return {
        cases_root / target_case.filename: render_target_scenario_markdown(target_case)
        for target_case in TARGET_CASES
    }


def generate(*, check: bool = False, output_root: Path = Path("docs/spec/50.e2e")) -> int:
    rendered = rendered_outputs(output_root)
    if check:
        return check_outputs(rendered)
    write_outputs(rendered)
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    return generate(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
