from __future__ import annotations

import argparse
import ast
import re
from collections.abc import Iterable, Sequence
from dataclasses import dataclass, field
from pathlib import Path

GENERATED_COMMENT = (
    "<!-- This file is generated by uv run python -m tools.generate_api_sequences. "
    "Do not edit manually. -->"
)
SQL_TABLE_PATTERN = re.compile(
    r"\b(?:FROM|JOIN|INTO|UPDATE)\s+([A-Za-z_][A-Za-z0-9_]*)",
    re.IGNORECASE,
)
SQL_ACTIONS = {
    "select": "参照",
    "insert": "追加",
    "update": "更新",
    "delete": "削除",
}
SQL_RECORD_ACTIONS = {
    "参照": "レコードを参照する",
    "追加": "レコードを追加する",
    "更新": "レコードを更新する",
    "削除": "レコードを削除する",
}
ROUTER_METHODS = {"delete", "get", "patch", "post", "put"}
PREDICATES = {"has", "is"}


@dataclass(frozen=True)
class SequenceStep:
    function_name: str
    target: str
    description: str
    arguments: tuple[str, ...] = ()
    return_type: str | None = None
    integration_resources: tuple[str, ...] = ()
    query_functions: tuple[str, ...] = ()


@dataclass(frozen=True)
class SqlStep:
    filename: str
    action: str
    tables: tuple[str, ...]
    summary: str


@dataclass(frozen=True)
class FunctionMetadata:
    description: str
    arguments: tuple[str, ...]
    return_type: str | None
    integration_resources: tuple[str, ...] = ()
    query_functions: tuple[str, ...] = ()


@dataclass(frozen=True)
class ApiSequence:
    domain: str
    api: str
    endpoint_name: str
    operation_id: str
    steps: list[SequenceStep]
    sql_steps: list[SqlStep]
    integration_resources: frozenset[str] = field(default_factory=lambda: frozenset[str]())


def snake_to_title(value: str) -> str:
    return value.replace("_", " ")


def participant_id(prefix: str, value: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9_]", "_", value)
    return f"{prefix}_{normalized}"


def literal_string(node: ast.AST | None) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return None


def keyword_value(call: ast.Call, name: str) -> ast.AST | None:
    for keyword in call.keywords:
        if keyword.arg == name:
            return keyword.value
    return None


def is_router_decorator(node: ast.AST) -> bool:
    return (
        isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr in ROUTER_METHODS
        and isinstance(node.func.value, ast.Name)
        and node.func.value.id == "router"
    )


def endpoint_function(tree: ast.AST) -> ast.AsyncFunctionDef | ast.FunctionDef:
    for node in ast.walk(tree):
        if not isinstance(node, ast.AsyncFunctionDef | ast.FunctionDef):
            continue
        if any(is_router_decorator(decorator) for decorator in node.decorator_list):
            return node
    raise ValueError("router endpoint function is not found")


def endpoint_operation_id(function: ast.AsyncFunctionDef | ast.FunctionDef) -> str:
    for decorator in function.decorator_list:
        if not is_router_decorator(decorator):
            continue
        if isinstance(decorator, ast.Call):
            operation_id = literal_string(keyword_value(decorator, "operation_id"))
            if operation_id:
                return operation_id
    return function.name


def awaited_api_function_name(node: ast.AST) -> str | None:
    if not isinstance(node, ast.Await):
        return None
    call = node.value
    if not isinstance(call, ast.Call):
        return None
    function = call.func
    if not isinstance(function, ast.Attribute):
        return None
    if not isinstance(function.value, ast.Name):
        return None
    if function.value.id != "api_functions":
        return None
    return function.attr


def annotation_text(node: ast.AST | None) -> str | None:
    if node is None:
        return None
    return ast.unparse(node)


def imported_integration_ports(tree: ast.AST) -> dict[str, str]:
    ports: dict[str, str] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.ImportFrom):
            continue
        module = node.module or ""
        match = re.fullmatch(r"app\.integrations\.([A-Za-z_][A-Za-z0-9_]*)\.port", module)
        if match is None:
            continue
        resource = match.group(1)
        for alias in node.names:
            local_name = alias.asname or alias.name
            ports[local_name] = resource
    return ports


def annotation_name(node: ast.AST | None) -> str | None:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    if isinstance(node, ast.Subscript):
        return annotation_name(node.value)
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.BitOr):
        return annotation_name(node.left) or annotation_name(node.right)
    return None


def function_integration_arguments(
    function: ast.AsyncFunctionDef | ast.FunctionDef,
    ports: dict[str, str],
) -> dict[str, str]:
    resources: dict[str, str] = {}
    for arg in [
        *function.args.posonlyargs,
        *function.args.args,
        *function.args.kwonlyargs,
    ]:
        name = annotation_name(arg.annotation)
        if name is not None and name in ports:
            resources[arg.arg] = ports[name]
    return resources


def called_integration_resources(
    function: ast.AsyncFunctionDef | ast.FunctionDef,
    ports: dict[str, str],
) -> tuple[str, ...]:
    integration_arguments = function_integration_arguments(function, ports)
    resources: list[str] = []
    for node in ast.walk(function):
        if not isinstance(node, ast.Call):
            continue
        callee = node.func
        if not isinstance(callee, ast.Attribute):
            continue
        if not isinstance(callee.value, ast.Name):
            continue
        resource = integration_arguments.get(callee.value.id)
        if resource is not None and resource not in resources:
            resources.append(resource)
    return tuple(resources)


def called_query_functions(function: ast.AsyncFunctionDef | ast.FunctionDef) -> tuple[str, ...]:
    names: list[str] = []
    for node in ast.walk(function):
        if not isinstance(node, ast.Call):
            continue
        callee = node.func
        if not isinstance(callee, ast.Attribute):
            continue
        if not isinstance(callee.value, ast.Name) or callee.value.id != "queries":
            continue
        if callee.attr not in names:
            names.append(callee.attr)
    return tuple(names)


def function_arguments(function: ast.AsyncFunctionDef | ast.FunctionDef) -> tuple[str, ...]:
    arguments: list[str] = []
    for arg in [
        *function.args.posonlyargs,
        *function.args.args,
        *function.args.kwonlyargs,
    ]:
        annotation = annotation_text(arg.annotation)
        arguments.append(f"{arg.arg} {annotation}" if annotation else arg.arg)
    if function.args.vararg is not None:
        annotation = annotation_text(function.args.vararg.annotation)
        arguments.append(
            f"*{function.args.vararg.arg} {annotation}"
            if annotation
            else f"*{function.args.vararg.arg}"
        )
    if function.args.kwarg is not None:
        annotation = annotation_text(function.args.kwarg.annotation)
        arguments.append(
            f"**{function.args.kwarg.arg} {annotation}"
            if annotation
            else f"**{function.args.kwarg.arg}"
        )
    return tuple(arguments)


def docstring_summary(function: ast.AsyncFunctionDef | ast.FunctionDef) -> str:
    docstring = ast.get_docstring(function)
    if not docstring:
        raise ValueError(f"{function.name} docstring is not found")
    return " ".join(docstring.strip().split())


def function_metadata(functions_path: Path) -> dict[str, FunctionMetadata]:
    tree = ast.parse(functions_path.read_text(encoding="utf-8"), filename=str(functions_path))
    ports = imported_integration_ports(tree)
    metadata: dict[str, FunctionMetadata] = {}
    for node in tree.body:
        if not isinstance(node, ast.AsyncFunctionDef | ast.FunctionDef):
            continue
        if node.name.startswith("_"):
            continue
        metadata[node.name] = FunctionMetadata(
            description=docstring_summary(node),
            arguments=function_arguments(node),
            return_type=annotation_text(node.returns),
            integration_resources=called_integration_resources(node, ports),
            query_functions=called_query_functions(node),
        )
    return metadata


def sequence_label(step: SequenceStep) -> str:
    return step.description


def predicate_condition_label(step: SequenceStep) -> str:
    description = step.description
    suffix = "かを判定する。"
    if not description.endswith(suffix):
        return description
    condition = description.removesuffix(suffix)
    if condition.endswith("可能"):
        return f"{condition}な場合。"
    return f"{condition}場合。"


def function_target(function_name: str) -> str:
    head, _separator, tail = function_name.partition("_")
    if head in PREDICATES:
        return tail
    return tail


def is_predicate_function(function_name: str) -> bool:
    head, _separator, _tail = function_name.partition("_")
    return head in PREDICATES


def integration_resources(integrations_root: Path) -> frozenset[str]:
    if not integrations_root.exists():
        return frozenset()
    return frozenset(
        path.name
        for path in sorted(integrations_root.iterdir())
        if path.is_dir() and (path / "port.py").exists()
    )


def integration_resource_for_target(
    target: str,
    resources: frozenset[str],
) -> str | None:
    for resource in sorted(resources, key=len, reverse=True):
        if target == resource or target.startswith(f"{resource}_"):
            return resource
    return None


def endpoint_sequence_steps(
    function: ast.AsyncFunctionDef | ast.FunctionDef,
    metadata: dict[str, FunctionMetadata],
) -> list[SequenceStep]:
    steps: list[SequenceStep] = []
    for node in ast.walk(function):
        function_name = awaited_api_function_name(node)
        if function_name is None:
            continue
        if function_name not in metadata:
            raise ValueError(f"{function_name} metadata is not found")
        function_metadata = metadata[function_name]
        steps.append(
            SequenceStep(
                function_name=function_name,
                target=function_target(function_name),
                description=function_metadata.description,
                arguments=function_metadata.arguments,
                return_type=function_metadata.return_type,
                integration_resources=function_metadata.integration_resources,
                query_functions=function_metadata.query_functions,
            )
        )
    return steps


def sql_action(filename: str) -> str:
    lowered = filename.lower()
    for action, label in SQL_ACTIONS.items():
        if action in lowered:
            return label
    return "参照"


def sql_tables(source: str) -> list[str]:
    tables: list[str] = []
    for match in SQL_TABLE_PATTERN.finditer(source):
        table = match.group(1)
        if table not in tables:
            tables.append(table)
    return tables


def query_sql_filename(node: ast.AsyncFunctionDef | ast.FunctionDef) -> str | None:
    for call in ast.walk(node):
        if not isinstance(call, ast.BinOp):
            continue
        if not isinstance(call.op, ast.Div):
            continue
        if not isinstance(call.left, ast.Name) or call.left.id != "SQL_DIR":
            continue
        filename = literal_string(call.right)
        if filename is not None:
            return filename
    return None


def query_sql_summaries(queries_path: Path) -> dict[str, str]:
    if not queries_path.exists():
        return {}
    tree = ast.parse(queries_path.read_text(encoding="utf-8"), filename=str(queries_path))
    summaries: dict[str, str] = {}
    for node in tree.body:
        if not isinstance(node, ast.AsyncFunctionDef | ast.FunctionDef):
            continue
        filename = query_sql_filename(node)
        summary = ast.get_docstring(node)
        if filename is not None and summary:
            summaries[filename] = " ".join(summary.strip().split())
    return summaries


def query_sql_filenames(queries_path: Path) -> dict[str, str]:
    if not queries_path.exists():
        return {}
    tree = ast.parse(queries_path.read_text(encoding="utf-8"), filename=str(queries_path))
    filenames: dict[str, str] = {}
    for node in tree.body:
        if not isinstance(node, ast.AsyncFunctionDef | ast.FunctionDef):
            continue
        filename = query_sql_filename(node)
        if filename is not None:
            filenames[node.name] = filename
    return filenames


def sql_sequence_steps(
    sql_dir: Path,
    summaries: dict[str, str] | None = None,
    filenames: set[str] | None = None,
) -> list[SqlStep]:
    if not sql_dir.exists():
        return []
    steps: list[SqlStep] = []
    summaries = summaries or {}
    for path in sorted(sql_dir.glob("*.sql")):
        if filenames is not None and path.name not in filenames:
            continue
        tables = sql_tables(path.read_text(encoding="utf-8"))
        if tables:
            steps.append(
                SqlStep(
                    filename=path.name,
                    action=sql_action(path.name),
                    tables=tuple(tables),
                    summary=summaries.get(path.name, SQL_RECORD_ACTIONS[sql_action(path.name)]),
                )
            )
    return steps


def api_sequence_from_dir(
    api_dir: Path,
    api_root: Path,
    integrations_root: Path | None = None,
) -> ApiSequence:
    router_path = api_dir / "router.py"
    functions_path = api_dir / "functions.py"
    tree = ast.parse(router_path.read_text(encoding="utf-8"), filename=str(router_path))
    function = endpoint_function(tree)
    metadata = function_metadata(functions_path)
    steps = endpoint_sequence_steps(function, metadata)
    query_filenames = query_sql_filenames(api_dir / "queries.py")
    called_query_filenames = {
        query_filenames[query_function]
        for step in steps
        for query_function in step.query_functions
        if query_function in query_filenames
    }
    relative = api_dir.relative_to(api_root)
    domain, api = relative.parts
    return ApiSequence(
        domain=domain,
        api=api,
        endpoint_name=function.name,
        operation_id=endpoint_operation_id(function),
        steps=steps,
        sql_steps=sql_sequence_steps(
            api_dir / "sql",
            query_sql_summaries(api_dir / "queries.py"),
            called_query_filenames or None,
        ),
        integration_resources=(
            integration_resources(integrations_root)
            if integrations_root is not None
            else frozenset()
        ),
    )


def api_dirs(api_root: Path) -> list[Path]:
    return sorted(
        path.parent for path in api_root.glob("*/*/router.py") if "__pycache__" not in path.parts
    )


def render_sequence_markdown(sequence: ApiSequence) -> str:
    resource_targets: list[str] = []
    for step in sequence.steps:
        if is_predicate_function(step.function_name):
            continue
        for resource in step.integration_resources:
            if resource not in resource_targets:
                resource_targets.append(resource)

    def step_resource(step: SequenceStep) -> str | None:
        if step.integration_resources:
            return step.integration_resources[0]
        return None

    lines = [
        GENERATED_COMMENT,
        "",
        f"# {sequence.api} sequence",
        "",
        "```mermaid",
        "sequenceDiagram",
        "  autonumber",
        "  participant API as API",
    ]
    for target in resource_targets:
        lines.append(
            f"  participant {participant_id('R', target)} as Resource: {snake_to_title(target)}"
        )
    if sequence.sql_steps:
        lines.append("  participant DB as DB")

    alt_depth = 0
    for step in sequence.steps:
        label = sequence_label(step)
        if is_predicate_function(step.function_name):
            indent = "  " + ("  " * alt_depth)
            lines.append(f"{indent}alt {predicate_condition_label(step)}")
            alt_depth += 1
            continue
        resource = step_resource(step)
        indent = "  " + ("  " * alt_depth)
        if resource is None:
            lines.append(f"{indent}API->>API: {label}")
        else:
            resource_id = participant_id("R", resource)
            lines.append(f"{indent}API->>{resource_id}: {label}")

    for sql_step in sequence.sql_steps:
        tables = ", ".join(sql_step.tables)
        indent = "  " + ("  " * alt_depth)
        lines.append(
            f"{indent}API->>DB: {sql_step.summary}"
            f"<br/>SQL {sql_step.filename}<br/>テーブル {tables}"
        )

    for depth in range(alt_depth - 1, -1, -1):
        indent = "  " + ("  " * depth)
        lines.append(f"{indent}end")

    lines.extend(["```", ""])
    return "\n".join(lines)


def output_path(sequence: ApiSequence, docs_root: Path) -> Path:
    return docs_root / sequence.domain / sequence.api / "sequence_gen.md"


def generate_sequences(
    api_root: Path,
    docs_root: Path,
    integrations_root: Path = Path("src/app/integrations"),
) -> dict[Path, str]:
    rendered: dict[Path, str] = {}
    for directory in api_dirs(api_root):
        sequence = api_sequence_from_dir(directory, api_root, integrations_root)
        rendered[output_path(sequence, docs_root)] = render_sequence_markdown(sequence)
    return rendered


def changed_outputs(rendered: dict[Path, str]) -> list[Path]:
    changed: list[Path] = []
    for path, content in rendered.items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            changed.append(path)
    return changed


def write_outputs(rendered: dict[Path, str]) -> None:
    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def render_changed(paths: Iterable[Path]) -> str:
    return "\n".join(str(path) for path in paths)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate API sequence Mermaid specs.")
    parser.add_argument("--api-root", type=Path, default=Path("src/app/apis"))
    parser.add_argument("--docs-root", type=Path, default=Path("docs/spec/40.apis"))
    parser.add_argument(
        "--integrations-root",
        type=Path,
        default=Path("src/app/integrations"),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Only check generated sequence files are up to date.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    rendered = generate_sequences(args.api_root, args.docs_root, args.integrations_root)
    changed = changed_outputs(rendered)
    if args.check:
        if changed:
            print(render_changed(changed))
            return 1
        return 0
    write_outputs(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
