from __future__ import annotations

import argparse
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import sqlglot
from sqlglot import exp

from tools.generate_db_table_specs import Table, parse_tables
from tools.generate_queries import FieldSpec, QuerySpec, api_sql_dirs, parse_query_spec

GENERATED_COMMENT = (
    "<!-- This file is generated by uv run python -m tools.generate_query_specs. "
    "Do not edit manually. -->"
)


@dataclass(frozen=True)
class SqlDocSpec:
    query: QuerySpec
    tables: tuple[str, ...]
    conditions: tuple[str, ...]


@dataclass(frozen=True)
class ApiQueryDoc:
    domain: str
    api: str
    sql_specs: list[SqlDocSpec]


def parse_statements(sql: str) -> list[Any]:
    return [statement for statement in sqlglot.parse(sql, read="mysql") if statement is not None]


def sql_tables(statements: Iterable[Any]) -> tuple[str, ...]:
    tables: list[str] = []
    for statement in statements:
        for table in statement.find_all(exp.Table):
            if table.name and table.name not in tables:
                tables.append(table.name)
    return tuple(tables)


def expression_sql(expression: Any) -> str:
    return " ".join(expression.sql(dialect="mysql").split())


def sql_conditions(statements: Iterable[Any]) -> tuple[str, ...]:
    conditions: list[str] = []
    for statement in statements:
        for join in statement.find_all(exp.Join):
            on_expression = join.args.get("on")
            if on_expression is not None:
                conditions.append(f"JOIN ON {expression_sql(on_expression)}")

        where = statement.args.get("where")
        if isinstance(where, exp.Where):
            conditions.append(f"WHERE {expression_sql(where.this)}")

        having = statement.args.get("having")
        if isinstance(having, exp.Having):
            conditions.append(f"HAVING {expression_sql(having.this)}")
    return tuple(conditions)


def field_type(field: FieldSpec) -> str:
    if field.nullable and field.type_hint != "Any":
        return f"{field.type_hint} | None"
    return field.type_hint


def render_field_table(fields: list[FieldSpec], empty_label: str) -> list[str]:
    if not fields:
        return [empty_label]

    lines = [
        "| 項目 | 型 | nullable |",
        "| --- | --- | --- |",
    ]
    for field in fields:
        nullable = "yes" if field.nullable else "no"
        lines.append(f"| `{field.name}` | `{field_type(field)}` | {nullable} |")
    return lines


def render_list(values: tuple[str, ...], empty_label: str) -> list[str]:
    if not values:
        return [empty_label]
    return [f"- `{value}`" for value in values]


def render_sql_spec(spec: SqlDocSpec) -> list[str]:
    lines = [
        f"## {spec.query.sql_filename}",
        "",
        "### SQLの概要",
        "",
        spec.query.summary,
        "",
        "### 利用するテーブル",
        "",
        *render_list(spec.tables, "_なし_"),
        "",
        "### 引数",
        "",
        *render_field_table(spec.query.params, "_なし_"),
        "",
        "### 戻り値",
        "",
        *render_field_table(spec.query.rows, "_なし_"),
        "",
        "### 条件",
        "",
        *render_list(spec.conditions, "_なし_"),
    ]
    return lines


def render_query_markdown(doc: ApiQueryDoc) -> str:
    lines = [
        GENERATED_COMMENT,
        "",
        f"# {doc.api} query",
        "",
    ]
    for index, spec in enumerate(doc.sql_specs):
        if index > 0:
            lines.append("")
        lines.extend(render_sql_spec(spec))
        lines.append("")
    return "\n".join(lines)


def api_query_doc_from_sql_dir(
    sql_dir: Path,
    api_root: Path,
    tables: dict[str, Table],
) -> ApiQueryDoc:
    relative = sql_dir.parent.relative_to(api_root)
    domain, api = relative.parts
    sql_specs: list[SqlDocSpec] = []
    for sql_path in sorted(sql_dir.glob("*.sql")):
        sql = sql_path.read_text(encoding="utf-8")
        statements = parse_statements(sql)
        sql_specs.append(
            SqlDocSpec(
                query=parse_query_spec(sql_path, tables),
                tables=sql_tables(statements),
                conditions=sql_conditions(statements),
            )
        )
    return ApiQueryDoc(domain=domain, api=api, sql_specs=sql_specs)


def output_path(doc: ApiQueryDoc, docs_root: Path) -> Path:
    return docs_root / doc.domain / doc.api / "query_gen.md"


def generate_query_specs(
    api_root: Path,
    docs_root: Path,
    ddl_path: Path,
) -> dict[Path, str]:
    tables = parse_tables(ddl_path.read_text(encoding="utf-8"))
    rendered: dict[Path, str] = {}
    for sql_dir in api_sql_dirs(api_root):
        doc = api_query_doc_from_sql_dir(sql_dir, api_root, tables)
        rendered[output_path(doc, docs_root)] = render_query_markdown(doc)
    return rendered


def changed_outputs(rendered: dict[Path, str]) -> list[Path]:
    changed: list[Path] = []
    for path, content in rendered.items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            changed.append(path)
    return changed


def write_outputs(rendered: dict[Path, str]) -> None:
    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def render_changed(paths: Iterable[Path]) -> str:
    return "\n".join(str(path) for path in paths)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate API SQL query Markdown specs.")
    parser.add_argument("--api-root", type=Path, default=Path("src/app/apis"))
    parser.add_argument("--docs-root", type=Path, default=Path("docs/spec/40.apis"))
    parser.add_argument("--ddl", type=Path, default=Path("src/db/ddl.sql"))
    parser.add_argument(
        "--check",
        action="store_true",
        help="Only check generated query specs are up to date.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    rendered = generate_query_specs(args.api_root, args.docs_root, args.ddl)
    changed = changed_outputs(rendered)
    if args.check:
        if changed:
            print(render_changed(changed))
            return 1
        return 0
    write_outputs(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
