from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

DEFAULT_DOCS_ROOT = Path("docs/spec/40.apis")
DEFAULT_OUTPUT_ROOT = Path("tests/generated")
GENERATED_COMMENT = (
    "# This file is generated by uv run python -m tools.generate_api_pytest_cases. "
    "Do not edit manually."
)
CASE_ID_PATTERN = re.compile(r"`(?P<case_id>(?:R|TC)[0-9]{3})`")
OPERATION_PATTERN = re.compile(r"^- Operation: `(?P<operation_id>[^`]+)`$", re.MULTILINE)


@dataclass(frozen=True)
class UnitTestSpec:
    domain: str
    api: str
    operation_id: str
    case_ids: tuple[str, ...]


def unit_test_specs(docs_root: Path = DEFAULT_DOCS_ROOT) -> tuple[UnitTestSpec, ...]:
    specs: list[UnitTestSpec] = []
    for path in sorted(docs_root.glob("*/*/unit-test_gen.md")):
        relative = path.relative_to(docs_root)
        domain, api, _ = relative.parts
        text = path.read_text(encoding="utf-8")
        operation_match = OPERATION_PATTERN.search(text)
        if operation_match is None:
            raise ValueError(f"{path}: operation id is missing")
        case_ids: list[str] = []
        seen: set[str] = set()
        for match in CASE_ID_PATTERN.finditer(text):
            case_id = match.group("case_id")
            if case_id in seen:
                continue
            seen.add(case_id)
            case_ids.append(case_id)
        if not case_ids:
            raise ValueError(f"{path}: case ids are missing")
        specs.append(
            UnitTestSpec(
                domain=domain,
                api=api,
                operation_id=operation_match.group("operation_id"),
                case_ids=tuple(case_ids),
            )
        )
    return tuple(specs)


def output_path(spec: UnitTestSpec, output_root: Path = DEFAULT_OUTPUT_ROOT) -> Path:
    return output_root / f"test_{spec.domain}_{spec.api}.py"


def render_pytest(spec: UnitTestSpec) -> str:
    case_id_lines = [f"    {case_id!r}," for case_id in spec.case_ids]
    return "\n".join(
        [
            GENERATED_COMMENT,
            "# fmt: off",
            "",
            "from __future__ import annotations",
            "",
            "from pathlib import Path",
            "",
            "import pytest",
            "",
            f"OPERATION_ID = {spec.operation_id!r}",
            "UNIT_TEST_SPEC_PATH = (",
            "    Path('docs')",
            "    / 'spec'",
            "    / '40.apis'",
            f"    / {spec.domain!r}",
            f"    / {spec.api!r}",
            "    / 'unit-test_gen.md'",
            ")",
            "CASE_IDS = (",
            *case_id_lines,
            ")",
            "",
            "",
            '@pytest.mark.parametrize("case_id", CASE_IDS, ids=CASE_IDS)',
            "def test_generated_unit_case_is_documented(case_id: str) -> None:",
            '    text = UNIT_TEST_SPEC_PATH.read_text(encoding="utf-8")',
            '    assert f"`{case_id}`" in text or f"### {case_id}" in text',
            "",
        ]
    )


def rendered_outputs(
    docs_root: Path = DEFAULT_DOCS_ROOT,
    output_root: Path = DEFAULT_OUTPUT_ROOT,
) -> dict[Path, str]:
    return {
        output_path(spec, output_root): render_pytest(spec) for spec in unit_test_specs(docs_root)
    }


def changed_outputs(outputs: dict[Path, str]) -> list[Path]:
    return [
        path
        for path, content in outputs.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]


def remove_stale_outputs(outputs: dict[Path, str], output_root: Path) -> None:
    expected = set(outputs)
    if not output_root.exists():
        return
    for path in output_root.glob("test_*.py"):
        if path not in expected:
            path.unlink()


def generate(
    *,
    docs_root: Path = DEFAULT_DOCS_ROOT,
    output_root: Path = DEFAULT_OUTPUT_ROOT,
    check: bool = False,
) -> int:
    outputs = rendered_outputs(docs_root, output_root)
    changed = changed_outputs(outputs)
    stale = (
        [path for path in output_root.glob("test_*.py") if path not in outputs]
        if output_root.exists()
        else []
    )
    if check:
        for path in [*changed, *stale]:
            print(path)
        return 1 if changed or stale else 0
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    remove_stale_outputs(outputs, output_root)
    print(f"Generated {len(outputs)} API pytest case files.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--docs-root", type=Path, default=DEFAULT_DOCS_ROOT)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return generate(docs_root=args.docs_root, output_root=args.output_root, check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
