import argparse
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast

from app.main import create_app

HTTP_METHODS = {"get", "post", "put", "patch", "delete", "options", "head"}
type JsonObject = dict[str, Any]
GENERATED_COMMENT = (
    "<!-- This file is generated by uv run python -m tools.generate_openapi_if_specs. "
    "Do not edit manually. -->"
)
PARAMETER_DESCRIPTION_OVERRIDES = {
    ("header", "Idempotency-Key"): (
        "同じ更新系リクエストの重複処理を防ぐためにクライアントが指定する一意なキーです。"
        "同じキーで再送された場合、サーバーは同一リクエストとして扱います。"
    ),
}
ENUM_VALUE_DESCRIPTIONS = {
    "AccessRequestDerivedState": {
        "PENDING": "審査待ちのAPI利用申請です。",
        "APPROVED": "承認済みのAPI利用申請です。",
        "REJECTED": "否認済みのAPI利用申請です。",
    },
    "ApiDerivedState": {
        "PUBLISHED": "APIカタログへ公開済みのAPIです。",
    },
    "ApiVisibility": {
        "INTERNAL": "組織内の利用者へ公開するAPIです。",
        "RESTRICTED": "許可された利用者またはプロジェクトに限定して公開するAPIです。",
    },
    "AuthMode": {
        "PUBLIC_PKCE": "PKCEを使うpublic clientでの認証を許可します。",
        "CLIENT_CREDENTIALS": "client credentialsを使うconfidential clientでの認証を許可します。",
        "BOTH": "public clientとconfidential clientの両方の認証方式を許可します。",
    },
    "ProjectDerivedState": {
        "ACTIVE": "利用可能なプロジェクトです。",
    },
    "QuotaPeriod": {
        "DAY": "1日単位で利用量上限を集計します。",
        "WEEK": "1週間単位で利用量上限を集計します。",
        "MONTH": "1か月単位で利用量上限を集計します。",
    },
    "ReviewerRole": {
        "PRIMARY": "主担当の審査者です。",
        "BACKUP": "副担当の審査者です。",
        "ADMIN": "管理者権限を持つ審査者です。",
    },
    "ScopeAttachmentMode": {
        "VERIFY_ONLY": "API Gateway methodのscope設定を検証のみ行います。",
        "PATCH_ALL_METHODS": "API Gateway methodへscope設定を反映します。",
    },
    "ScopeConfigObserved": {
        "VERIFIED": "期待するscope設定が検出されています。",
        "NOT_CONFIGURED": "scope設定が検出されていません。",
        "UNKNOWN": "scope設定の検出状態が不明です。",
    },
    "SubscriptionDerivedState": {
        "ACTIVE": "利用可能なAPI利用権です。",
    },
    "TokenValidityUnit": {
        "minutes": "分単位の有効期間です。",
        "hours": "時間単位の有効期間です。",
        "days": "日単位の有効期間です。",
    },
    "UserStatus": {
        "active": "有効なユーザーです。",
        "deleted": "削除済みのユーザーです。",
    },
}
ENUM_VALUE_DESCRIPTION_FALLBACKS = {
    "active": "有効な状態です。",
    "deleted": "削除済みの状態です。",
}


@dataclass(frozen=True)
class FieldRow:
    name: str
    type_name: str
    required: bool
    description: str
    constraints: str


def snake_case(value: str) -> str:
    value = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", value)
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", value)
    value = re.sub(r"[^a-zA-Z0-9]+", "_", value)
    return value.strip("_").lower() or "api"


def markdown_escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def as_object(value: Any) -> JsonObject:
    return cast(JsonObject, value) if isinstance(value, dict) else {}


def as_list(value: Any) -> list[Any]:
    return cast(list[Any], value) if isinstance(value, list) else []  # type: ignore[redundant-cast]


def schema_components(openapi: JsonObject) -> JsonObject:
    components = openapi.get("components", {})
    schemas = as_object(components).get("schemas", {})
    return as_object(schemas)


def ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def resolve_schema(schema: JsonObject, components: JsonObject) -> JsonObject:
    if "$ref" in schema:
        resolved = components.get(ref_name(str(schema["$ref"])), {})
        return as_object(resolved)
    return schema


def unwrap_nullable(schema: JsonObject, components: JsonObject) -> tuple[JsonObject, bool]:
    schema = resolve_schema(schema, components)
    for key in ("anyOf", "oneOf"):
        variants = as_list(schema.get(key))
        if not variants:
            continue
        non_null = [
            resolve_schema(as_object(variant), components)
            for variant in variants
            if as_object(variant).get("type") != "null"
        ]
        if len(non_null) == 1 and len(non_null) != len(variants):
            return non_null[0], True
    return schema, False


def enum_values(schema: JsonObject) -> list[str]:
    return [str(value) for value in as_list(schema.get("enum"))]


def enum_type(schema: JsonObject) -> str:
    values = enum_values(schema)
    base_type = str(schema.get("type") or "string")
    return f"{base_type}({', '.join(values)})"


def enum_value_description(schema: JsonObject, value: str) -> str:
    schema_name = str(schema.get("title") or "")
    descriptions = ENUM_VALUE_DESCRIPTIONS.get(schema_name, {})
    return (
        descriptions.get(value)
        or ENUM_VALUE_DESCRIPTION_FALLBACKS.get(value)
        or "列挙値として指定可能な値です。"
    )


def schema_type(schema: JsonObject, components: JsonObject) -> str:
    if "$ref" in schema:
        resolved = resolve_schema(schema, components)
        if enum_values(resolved):
            return enum_type(resolved)
        return ref_name(str(schema["$ref"]))
    schema, nullable = unwrap_nullable(schema, components)
    if enum_values(schema):
        type_name = enum_type(schema)
    elif schema.get("type") == "array":
        items = as_object(schema.get("items", {}))
        item_type = schema_type(items, components)
        type_name = f"array<{item_type}>"
    elif schema.get("type") == "object" and "additionalProperties" in schema:
        additional = schema["additionalProperties"]
        if isinstance(additional, dict):
            type_name = f"object<string, {schema_type(as_object(additional), components)}>"
        else:
            type_name = "object"
    else:
        type_name = str(schema.get("type") or schema.get("title") or "object")
    return f"{type_name} | null" if nullable else type_name


def schema_constraints(schema: JsonObject, components: JsonObject) -> str:
    schema, _nullable = unwrap_nullable(schema, components)
    constraints: list[str] = []
    for key in (
        "minimum",
        "maximum",
        "exclusiveMinimum",
        "exclusiveMaximum",
        "minLength",
        "maxLength",
        "pattern",
        "minItems",
        "maxItems",
    ):
        if key in schema:
            constraints.append(f"{key}={schema[key]}")
    values = enum_values(schema)
    if values:
        constraints.append(
            "<br>".join(f"{value}={enum_value_description(schema, value)}" for value in values)
        )
    return ", ".join(constraints) if constraints else "-"


def schema_description(schema: JsonObject, fallback: str = "") -> str:
    description = schema.get("description")
    return str(description or fallback or "-")


def nested_object_schema(schema: JsonObject, components: JsonObject) -> JsonObject:
    schema = resolve_schema(schema, components)
    if schema.get("type") == "object" and as_object(schema.get("properties")):
        return schema
    if schema.get("type") == "array":
        return nested_object_schema(as_object(schema.get("items")), components)
    return {}


def object_field_rows(
    schema: JsonObject,
    components: JsonObject,
    *,
    prefix: str = "",
    seen_refs: frozenset[str] = frozenset(),
) -> list[FieldRow]:
    schema = resolve_schema(schema, components)
    required = set(str(item) for item in as_list(schema.get("required", [])))
    properties = as_object(schema.get("properties", {}))
    if not properties:
        return []

    rows: list[FieldRow] = []
    for name, property_schema in properties.items():
        if not isinstance(property_schema, dict):
            continue
        property_schema_object = cast(JsonObject, property_schema)
        resolved = resolve_schema(property_schema_object, components)
        name = str(name)
        field_name = f"{prefix}.{name}" if prefix else name
        rows.append(
            FieldRow(
                name=field_name,
                type_name=schema_type(property_schema_object, components),
                required=name in required,
                description=schema_description(resolved, f"`{name}` の値。"),
                constraints=schema_constraints(property_schema_object, components),
            )
        )
        child_schema = nested_object_schema(property_schema_object, components)
        ref = str(
            property_schema_object.get("$ref")
            or as_object(property_schema_object.get("items")).get("$ref")
        )
        if child_schema and ref not in seen_refs:
            child_prefix = (
                f"{field_name}[]" if property_schema_object.get("type") == "array" else field_name
            )
            rows.extend(
                object_field_rows(
                    child_schema,
                    components,
                    prefix=child_prefix,
                    seen_refs=seen_refs | frozenset([ref]) if ref else seen_refs,
                )
            )
    return rows


def parameter_rows(operation: JsonObject, location: str, components: JsonObject) -> list[FieldRow]:
    rows: list[FieldRow] = []
    for parameter in as_list(operation.get("parameters", [])):
        parameter_object = as_object(parameter)
        if not parameter_object or parameter_object.get("in") != location:
            continue
        schema = as_object(parameter_object.get("schema", {}))
        name = str(parameter_object.get("name", ""))
        rows.append(
            FieldRow(
                name=name,
                type_name=schema_type(schema, components),
                required=bool(parameter_object.get("required")),
                description=str(
                    parameter_object.get("description")
                    or PARAMETER_DESCRIPTION_OVERRIDES.get((location, name))
                    or schema_description(schema)
                ),
                constraints=schema_constraints(schema, components),
            )
        )
    return rows


def request_body_rows(operation: JsonObject, components: JsonObject) -> list[FieldRow]:
    request_body = operation.get("requestBody")
    if not isinstance(request_body, dict):
        return []
    request_body_object = cast(JsonObject, request_body)
    content = as_object(request_body_object.get("content", {}))
    if not content:
        return []
    media: Any = content.get("application/json") or next(
        iter(content.values()), cast(JsonObject, {})
    )
    if not isinstance(media, dict):
        return []
    media_object = cast(JsonObject, media)
    schema = as_object(media_object.get("schema", {}))
    return object_field_rows(schema, components)


def response_media(response: JsonObject) -> tuple[str, JsonObject]:
    content = as_object(response.get("content", {}))
    if not content:
        return "-", {}
    media_type, media = next(iter(content.items()))
    if not isinstance(media, dict):
        return str(media_type), {}
    media_object = cast(JsonObject, media)
    schema = as_object(media_object.get("schema", {}))
    return str(media_type), schema


def response_summary_rows(operation: JsonObject, components: JsonObject) -> list[list[str]]:
    rows: list[list[str]] = []
    responses = as_object(operation.get("responses", {}))
    if not responses:
        return rows
    for status_code, response in responses.items():
        if not isinstance(response, dict):
            continue
        response_object = cast(JsonObject, response)
        media_type, schema = response_media(response_object)
        body_rows = object_field_rows(schema, components)
        body = f"{len(body_rows)} field(s)" if body_rows else "-"
        rows.append(
            [str(status_code), str(response_object.get("description") or "-"), media_type, body]
        )
    return rows


def render_field_table(rows: list[FieldRow]) -> list[str]:
    if not rows:
        return ["_なし_"]
    lines = [
        "| 項目 | 型 | 必須 | 説明 | 制約 |",
        "| --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{markdown_escape(row.name)}`",
                    f"`{markdown_escape(row.type_name)}`",
                    "yes" if row.required else "no",
                    markdown_escape(row.description),
                    markdown_escape(row.constraints),
                ]
            )
            + " |"
        )
    return lines


def render_response_summary(rows: list[list[str]]) -> list[str]:
    if not rows:
        return ["_なし_"]
    lines = [
        "| Status | 説明 | Media type | Body |",
        "| --- | --- | --- | --- |",
    ]
    for status_code, description, media_type, body in rows:
        lines.append(
            f"| `{markdown_escape(status_code)}` | {markdown_escape(description)} | "
            f"`{markdown_escape(media_type)}` | {markdown_escape(body)} |"
        )
    return lines


def render_response_details(operation: JsonObject, components: JsonObject) -> list[str]:
    lines: list[str] = []
    responses = as_object(operation.get("responses", {}))
    if not responses:
        return lines
    for status_code, response in responses.items():
        if not isinstance(response, dict):
            continue
        response_object = cast(JsonObject, response)
        media_type, schema = response_media(response_object)
        body_rows = object_field_rows(schema, components)
        if not body_rows:
            continue
        description = str(response_object.get("description") or "-")
        lines.extend(
            [
                "",
                f"##### `{status_code}` {description}",
                "",
                f"Media type: `{media_type}`",
                "",
                *render_field_table(body_rows),
            ]
        )
    return lines


def render_operation_markdown(
    path: str,
    method: str,
    operation: JsonObject,
    components: JsonObject,
) -> str:
    summary = str(operation.get("summary") or "")
    description = str(operation.get("description") or "")
    lines = [
        f"# {method.upper()} {path}",
        "",
        GENERATED_COMMENT,
        "",
        f"Summary: {summary or '-'}",
        "",
    ]
    if description:
        lines.extend([description, ""])
    lines.extend(
        ["## Headers", "", *render_field_table(parameter_rows(operation, "header", components)), ""]
    )
    lines.extend(
        [
            "## Path Parameters",
            "",
            *render_field_table(parameter_rows(operation, "path", components)),
            "",
        ]
    )
    lines.extend(
        [
            "## Query Parameters",
            "",
            *render_field_table(parameter_rows(operation, "query", components)),
            "",
        ]
    )
    lines.extend(["## Data", "", *render_field_table(request_body_rows(operation, components)), ""])
    lines.extend(
        ["## Responses", "", *render_response_summary(response_summary_rows(operation, components))]
    )
    lines.extend(render_response_details(operation, components))
    lines.append("")
    return "\n".join(lines)


def operation_output_path(output_dir: Path, operation: JsonObject) -> Path:
    tags = as_list(operation.get("tags"))
    tag = str(tags[0]) if tags else "default"
    operation_id = str(operation.get("operationId") or operation.get("summary") or "api")
    return output_dir / snake_case(tag) / snake_case(operation_id) / "IF.md"


def iter_operations(openapi: JsonObject) -> list[tuple[str, str, JsonObject]]:
    operations: list[tuple[str, str, JsonObject]] = []
    paths = as_object(openapi.get("paths", {}))
    if not paths:
        return operations
    for path, path_item in sorted(paths.items()):
        if not isinstance(path_item, dict):
            continue
        path_item_object = cast(JsonObject, path_item)
        for method, operation in sorted(path_item_object.items()):
            if method not in HTTP_METHODS or not isinstance(operation, dict):
                continue
            operations.append((str(path), method, cast(JsonObject, operation)))
    return operations


def generate_from_openapi(openapi: JsonObject, output_dir: Path) -> list[Path]:
    components = schema_components(openapi)
    written: list[Path] = []
    for path, method, operation in iter_operations(openapi):
        output_path = operation_output_path(output_dir, operation)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(
            render_operation_markdown(path, method, operation, components),
            encoding="utf-8",
        )
        written.append(output_path)
    return written


def load_fastapi_openapi() -> JsonObject:
    return create_app().openapi()


def generate(output_dir: Path) -> list[Path]:
    return generate_from_openapi(load_fastapi_openapi(), output_dir)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate IF specs from FastAPI OpenAPI.")
    parser.add_argument("--output-dir", type=Path, default=Path("docs/spec/40.apis"))
    return parser


def main() -> None:
    args = build_arg_parser().parse_args()
    written = generate(args.output_dir)
    print(f"Generated {len(written)} IF spec files.")


if __name__ == "__main__":  # pragma: no cover
    main()
