from __future__ import annotations

import argparse
import ast
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

import sqlglot
from sqlglot import exp
from sqlglot.expressions.core import Expression

from tools.generate_api_sequences import (
    api_dirs,
    endpoint_function,
    endpoint_operation_id,
    endpoint_route_method,
    endpoint_route_path,
    keyword_value,
    literal_string,
)
from tools.generate_api_unit_test_factors import api_unit_test_factors_from_dir
from tools.generate_db_table_specs import Table, parse_tables, table_name

GENERATED_COMMENT = (
    "<!-- This file is generated by uv run python -m tools.generate_api_detail_design. "
    "Do not edit manually. -->"
)


@dataclass(frozen=True)
class FieldSpec:
    name: str
    type_name: str
    description: str


@dataclass(frozen=True)
class SchemaSpec:
    name: str
    description: str
    fields: tuple[FieldSpec, ...]


@dataclass(frozen=True)
class EndpointInput:
    location: str
    name: str
    type_name: str
    description: str


@dataclass(frozen=True)
class SqlSourceValue:
    parameter: str
    source: str
    note_sql: str | None = None


@dataclass(frozen=True)
class SqlSpec:
    filename: str
    action: str
    table: str
    column_params: tuple[tuple[str, SqlSourceValue], ...]


@dataclass(frozen=True)
class QuerySpec:
    function_name: str
    params_class: str
    row_class: str
    sql_filename: str
    summary: str
    tables: tuple[str, ...]


@dataclass(frozen=True)
class ResourceChange:
    action: str
    table: str
    summary: str
    sql_filename: str
    values: tuple[tuple[str, str, str, str], ...]
    notes: tuple[tuple[str, str], ...] = ()


@dataclass(frozen=True)
class ExternalResourceInput:
    class_name: str
    parameters: tuple[tuple[str, str], ...]


@dataclass(frozen=True)
class ApiDetailDesign:
    domain: str
    api: str
    operation_id: str
    method: str
    path: str
    request_schema: SchemaSpec | None
    response_schema: SchemaSpec | None
    endpoint_inputs: tuple[EndpointInput, ...]
    request_fields: tuple[FieldSpec, ...]
    prerequisites: tuple[str, ...]
    resource_changes: tuple[ResourceChange, ...]
    external_inputs: tuple[ExternalResourceInput, ...]
    response_values: tuple[tuple[str, str, str], ...]
    ddl_tables: dict[str, Table]


def markdown_escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def to_camel(value: str) -> str:
    parts = value.split("_")
    return parts[0] + "".join(part[:1].upper() + part[1:] for part in parts[1:])


def clean_docstring(value: str | None) -> str:
    if not value:
        return "-"
    return " ".join(value.strip().split())


def column_comment(tables: dict[str, Table], table: str, column: str) -> str:
    for ddl_column in tables.get(table, Table(name=table, columns=[])).columns:
        if ddl_column.name == column:
            return ddl_column.comment or "-"
    return "-"


def string_literal_from_joined(node: ast.AST | None) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.JoinedStr):
        return "".join(
            str(part.value)
            for part in node.values
            if isinstance(part, ast.Constant) and isinstance(part.value, str)
        )
    return None


def field_description(node: ast.AST | None) -> str:
    if not isinstance(node, ast.Call):
        return "-"
    description = string_literal_from_joined(keyword_value(node, "description"))
    return description or "-"


def schema_specs(schemas_path: Path) -> dict[str, SchemaSpec]:
    if not schemas_path.exists():
        return {}
    tree = ast.parse(schemas_path.read_text(encoding="utf-8"), filename=str(schemas_path))
    specs: dict[str, SchemaSpec] = {}
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        fields: list[FieldSpec] = []
        for statement in node.body:
            if not isinstance(statement, ast.AnnAssign) or not isinstance(
                statement.target, ast.Name
            ):
                continue
            fields.append(
                FieldSpec(
                    name=to_camel(statement.target.id),
                    type_name=ast.unparse(statement.annotation),
                    description=field_description(statement.value),
                )
            )
        if fields:
            specs[node.name] = SchemaSpec(
                name=node.name,
                description=clean_docstring(ast.get_docstring(node)),
                fields=tuple(fields),
            )
    return specs


def strip_optional_type(type_name: str) -> str:
    return type_name.replace(" | None", "").replace("None | ", "")


def schema_field_rows(
    schema: SchemaSpec,
    specs: dict[str, SchemaSpec],
    *,
    prefix: str = "",
) -> list[FieldSpec]:
    rows: list[FieldSpec] = []
    for field in schema.fields:
        name = f"{prefix}.{field.name}" if prefix else field.name
        rows.append(FieldSpec(name=name, type_name=field.type_name, description=field.description))
        nested_name = strip_optional_type(field.type_name)
        if nested_name.startswith("list[") and nested_name.endswith("]"):
            nested_name = nested_name.removeprefix("list[").removesuffix("]")
        if nested_name in specs:
            rows.extend(schema_field_rows(specs[nested_name], specs, prefix=name))
    return rows


def endpoint_response_model(function: ast.AsyncFunctionDef | ast.FunctionDef) -> str | None:
    for decorator in function.decorator_list:
        if not isinstance(decorator, ast.Call):
            continue
        value = keyword_value(decorator, "response_model")
        if isinstance(value, ast.Name):
            return value.id
    return None


def endpoint_body_schema(function: ast.AsyncFunctionDef | ast.FunctionDef) -> str | None:
    for arg in function.args.args:
        annotation = arg.annotation
        if not isinstance(annotation, ast.Subscript):
            continue
        parts = annotation.slice.elts if isinstance(annotation.slice, ast.Tuple) else ()
        if not parts:
            continue
        if any(is_fastapi_marker(part, "Body") for part in parts[1:]):
            return ast.unparse(parts[0])
    return None


def is_fastapi_marker(node: ast.AST, name: str) -> bool:
    return isinstance(node, ast.Call) and (
        (isinstance(node.func, ast.Name) and node.func.id == name)
        or (isinstance(node.func, ast.Attribute) and node.func.attr == name)
    )


def marker_alias(node: ast.AST) -> str | None:
    if not isinstance(node, ast.Call):
        return None
    return literal_string(keyword_value(node, "alias"))


def marker_description(node: ast.AST) -> str:
    if not isinstance(node, ast.Call):
        return "-"
    return literal_string(keyword_value(node, "description")) or "-"


def endpoint_inputs(function: ast.AsyncFunctionDef | ast.FunctionDef) -> tuple[EndpointInput, ...]:
    inputs: list[EndpointInput] = []
    for arg in function.args.args:
        annotation = arg.annotation
        if not isinstance(annotation, ast.Subscript):
            continue
        parts = annotation.slice.elts if isinstance(annotation.slice, ast.Tuple) else ()
        if len(parts) < 2:
            continue
        type_name = ast.unparse(parts[0])
        for marker_name, location in (("Path", "path"), ("Header", "header"), ("Body", "body")):
            marker = next(
                (part for part in parts[1:] if is_fastapi_marker(part, marker_name)),
                None,
            )
            if marker is None:
                continue
            inputs.append(
                EndpointInput(
                    location=location,
                    name=marker_alias(marker) or to_camel(arg.arg),
                    type_name=type_name,
                    description=marker_description(marker),
                )
            )
    return tuple(inputs)


def endpoint_input_origins(function: ast.AsyncFunctionDef | ast.FunctionDef) -> dict[str, str]:
    origins: dict[str, str] = {}
    for arg in function.args.args:
        annotation = arg.annotation
        if not isinstance(annotation, ast.Subscript):
            continue
        parts = annotation.slice.elts if isinstance(annotation.slice, ast.Tuple) else ()
        if len(parts) < 2:
            continue
        for marker_name, location in (
            ("Path", "path"),
            ("Header", "header"),
            ("Body", "request.body"),
        ):
            marker = next(
                (part for part in parts[1:] if is_fastapi_marker(part, marker_name)),
                None,
            )
            if marker is None:
                continue
            name = marker_alias(marker) or to_camel(arg.arg)
            origins[arg.arg] = f"{location}.{name}" if location != "request.body" else location
    return origins


DEFAULT_ARG_ORIGINS = {
    "caller": "認証主体: caller",
    "request_context": "HTTP request context",
    "session": "DB session",
    "project": "DB: projects",
    "access_request": "DB: api_access_requests",
    "api": "DB: apis",
    "row": "DB行",
}


def parameter_name(expression: object) -> str | None:
    if isinstance(expression, exp.Placeholder | exp.Parameter):
        return expression.name
    return None


def expression_parameters(expression: Expression) -> list[str]:
    names: list[str] = []
    for parameter in expression.find_all(exp.Placeholder, exp.Parameter):
        name = parameter_name(parameter)
        if name is not None and name not in names:
            names.append(name)
    return names


def expression_column_sources(
    expression: Expression,
    *,
    output_column: str | None = None,
) -> tuple[str, ...]:
    aliases: dict[str, str] = {}
    for table in expression.find_all(exp.Table):
        if table.name:
            aliases[table.alias_or_name] = table.name
            aliases[table.name] = table.name
    tables = tuple(dict.fromkeys(aliases.values()))
    sources: list[str] = []
    for column in expression.find_all(exp.Column):
        if output_column is not None and column.name == output_column:
            continue
        table = aliases.get(column.table or "")
        if table is None and len(tables) == 1:
            table = tables[0]
        source = f"{table}.{column.name}" if table is not None else column.name
        if source not in sources:
            sources.append(source)
    return tuple(sources)


def sql_expression_source(
    expression: Expression,
    *,
    output_column: str | None = None,
) -> SqlSourceValue:
    direct_parameter = parameter_name(expression)
    if direct_parameter is not None:
        return SqlSourceValue(parameter=direct_parameter, source=direct_parameter)
    parameters = expression_parameters(expression)
    if len(parameters) == 1 and not list(expression.find_all(exp.Select)):
        return SqlSourceValue(parameter=parameters[0], source=parameters[0])
    sql = " ".join(expression.sql(dialect="mysql").split())
    if len(sql) <= 60 and not list(expression.find_all(exp.Select)):
        return SqlSourceValue(parameter=sql, source=f"SQL式: {sql}")
    column_sources = expression_column_sources(expression, output_column=output_column)
    source = "SQL式"
    if column_sources:
        source = "SQL式: 取得元 " + ", ".join(
            f"DB: {column_source}" for column_source in column_sources
        )
    return SqlSourceValue(parameter=sql, source=source, note_sql=sql)


def sql_tables(path: Path) -> tuple[str, ...]:
    text = path.read_text(encoding="utf-8")
    tables: list[str] = []
    for statement in sqlglot.parse(text, read="mysql"):
        if statement is None:
            continue
        for table in statement.find_all(exp.Table):
            if table.name and table.name not in tables:
                tables.append(table.name)
    return tuple(tables)


def table_aliases(expression: Expression) -> dict[str, str]:
    aliases: dict[str, str] = {}
    for table in expression.find_all(exp.Table):
        if table.name:
            aliases[table.name] = table.name
            aliases[table.alias_or_name] = table.name
    return aliases


def select_output_sources(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    statement = next((item for item in sqlglot.parse(text, read="mysql") if item), None)
    if not isinstance(statement, exp.Select):
        return {}
    aliases = table_aliases(statement)
    sources: dict[str, str] = {}
    for expression in statement.expressions:
        output_name = expression.alias_or_name
        source = expression.this if isinstance(expression, exp.Alias) else expression
        if not output_name or not isinstance(source, exp.Column):
            continue
        table = aliases.get(source.table or "")
        if table is None:
            continue
        sources[to_camel(output_name)] = f"DB: {table}.{to_camel(source.name)}"
    return sources


def sql_action_spec(path: Path) -> SqlSpec | None:
    text = path.read_text(encoding="utf-8")
    statement = next((item for item in sqlglot.parse(text, read="mysql") if item), None)
    if isinstance(statement, exp.Insert) and isinstance(statement.this, exp.Schema):
        columns = [column.name for column in statement.this.expressions]
        values_expression = statement.args.get("expression")
        values: list[Expression] = []
        if isinstance(values_expression, exp.Values) and values_expression.expressions:
            first_tuple = values_expression.expressions[0]
            if isinstance(first_tuple, exp.Tuple):
                values = list(first_tuple.expressions)
        column_params: list[tuple[str, SqlSourceValue]] = []
        for column, value in zip(columns, values, strict=False):
            column_params.append((column, sql_expression_source(value, output_column=column)))
        return SqlSpec(path.name, "作成", table_name(statement.this), tuple(column_params))
    if isinstance(statement, exp.Update):
        column_params: list[tuple[str, SqlSourceValue]] = []
        for assignment in statement.expressions:
            if not isinstance(assignment, exp.EQ) or not isinstance(assignment.this, exp.Column):
                continue
            column_params.append(
                (
                    assignment.this.name,
                    sql_expression_source(
                        assignment.expression,
                        output_column=assignment.this.name,
                    ),
                )
            )
        target = table_name(statement.this) if statement.this is not None else "-"
        return SqlSpec(path.name, "更新", target, tuple(column_params))
    if isinstance(statement, exp.Delete):
        params = tuple(
            (name, SqlSourceValue(parameter=name, source=name))
            for name in expression_parameters(statement)
        )
        target = table_name(statement.this) if statement.this is not None else "-"
        return SqlSpec(path.name, "削除", target, params)
    return None


def query_specs(queries_path: Path) -> dict[str, QuerySpec]:
    tree = ast.parse(queries_path.read_text(encoding="utf-8"), filename=str(queries_path))
    specs: dict[str, QuerySpec] = {}
    for node in tree.body:
        if not isinstance(node, ast.AsyncFunctionDef):
            continue
        sql_file = None
        for child in ast.walk(node):
            if (
                isinstance(child, ast.Constant)
                and isinstance(child.value, str)
                and child.value.endswith(".sql")
            ):
                sql_file = child.value
                break
        if sql_file is None:
            continue
        params_class = ""
        row_class = ""
        returns = node.returns
        _ = returns
        for arg in node.args.args:
            if arg.arg == "params" and arg.annotation is not None:
                params_class = ast.unparse(arg.annotation)
        for child in ast.walk(node):
            if not isinstance(child, ast.Call):
                continue
            if call_name(child.func) != "fetch_all" or len(child.args) < 4:
                continue
            row_class = ast.unparse(child.args[3])
        specs[node.name] = QuerySpec(
            function_name=node.name,
            params_class=params_class,
            row_class=row_class,
            sql_filename=sql_file,
            summary=clean_docstring(ast.get_docstring(node)),
            tables=sql_tables(queries_path.with_name("sql") / sql_file),
        )
    return specs


def query_row_source_maps(
    api_dir: Path,
    queries: dict[str, QuerySpec],
) -> dict[str, dict[str, str]]:
    maps: dict[str, dict[str, str]] = {}
    for query in queries.values():
        if not query.row_class:
            continue
        maps[query.row_class] = select_output_sources(api_dir / "sql" / query.sql_filename)
    return maps


def model_fields_by_class(path: Path) -> dict[str, tuple[str, ...]]:
    if not path.exists():
        return {}
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    fields: dict[str, tuple[str, ...]] = {}
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        names = [
            statement.target.id
            for statement in node.body
            if isinstance(statement, ast.AnnAssign) and isinstance(statement.target, ast.Name)
        ]
        if names:
            fields[node.name] = tuple(names)
    return fields


def call_name(node: ast.AST) -> str | None:
    if isinstance(node, ast.Name):
        if node.id == "now":
            return "処理時刻 _now()"
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    return None


def snake_source_path(value: str) -> str:
    return ".".join(to_camel(part) for part in value.split("."))


def format_origin_expression(value: str, origins: dict[str, str]) -> str:
    if value == "-":
        return value
    if value.startswith("SQL式:"):
        return value
    prefixed_sources = (
        "固定値:",
        "自動生成:",
        "処理時刻",
        "DB:",
        "request.body",
        "path.",
        "header.",
    )
    if value.startswith(prefixed_sources):
        return value
    if value.startswith("'") or value in {"True", "False", "None"}:
        return f"固定値: {value}"
    if value.startswith("{"):
        return f"生成JSON: {value}"
    if value.endswith(" のJSON表現"):
        target = value.removesuffix(" のJSON表現")
        return f"{format_origin_expression(target, origins)} のJSON表現"
    if " を str 化" in value:
        target = value.removesuffix(" を str 化")
        return f"{format_origin_expression(target, origins)} を str 化"
    if "." in value:
        root, rest = value.split(".", 1)
        origin = origins.get(root)
        if origin is not None:
            if origin.startswith("DB: "):
                return f"{origin}.{snake_source_path(rest)}"
            if origin == "request.body":
                return f"request.body.{snake_source_path(rest)}"
            return f"{origin}.{snake_source_path(rest)}"
        if "[" in root and root.split("[", 1)[0] in origins:
            origin = origins[root.split("[", 1)[0]]
            if origin.startswith("DB: "):
                return f"{origin}.{snake_source_path(rest)}"
            return f"{origin}.{snake_source_path(rest)}"
    if value in origins:
        return origins[value]
    return value


def dotted_name(node: ast.AST) -> str:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return f"{dotted_name(node.value)}.{node.attr}"
    if isinstance(node, ast.Call):
        return f"{dotted_name(node.func)}(...)"
    if isinstance(node, ast.Constant):
        return repr(node.value)
    return ast.unparse(node)


def source_expression(node: ast.AST | None, origins: dict[str, str] | None = None) -> str:
    origins = origins or {}
    if node is None:
        return "-"
    if isinstance(node, ast.Call):
        name = call_name(node.func) or ast.unparse(node.func)
        if name == "uuid4":
            return "自動生成: uuid4()"
        if name == "_now":
            return "処理時刻 _now()"
        if name == "_request_hash":
            return "入力/生成値から _request_hash(...) で算出"
        if name.endswith("model_dump") and isinstance(node.func, ast.Attribute):
            return f"{format_origin_expression(dotted_name(node.func.value), origins)} のJSON表現"
        if name in {"str", "list", "tuple", "dict"} and node.args:
            return f"{source_expression(node.args[0], origins)} を {name} 化"
    if isinstance(node, ast.Attribute):
        return format_origin_expression(dotted_name(node), origins)
    if isinstance(node, ast.Subscript):
        return format_origin_expression(ast.unparse(node), origins)
    if isinstance(node, ast.BoolOp):
        operator = " or " if isinstance(node.op, ast.Or) else " and "
        return operator.join(source_expression(value, origins) for value in node.values)
    if isinstance(node, ast.IfExp):
        return (
            f"{source_expression(node.body, origins)} if {source_expression(node.test, origins)} "
            f"else {source_expression(node.orelse, origins)}"
        )
    if isinstance(node, ast.BinOp):
        return format_origin_expression(ast.unparse(node), origins)
    if isinstance(node, ast.Name):
        if node.id == "now":
            return "処理時刻 _now()"
        return format_origin_expression(node.id, origins)
    if isinstance(node, ast.Constant):
        return repr(node.value)
    if isinstance(node, ast.Dict):
        return "{" + ", ".join(
            f"{source_expression(key, origins)}: {source_expression(value, origins)}"
            for key, value in zip(node.keys, node.values, strict=True)
            if key is not None
        ) + "}"
    return format_origin_expression(ast.unparse(node), origins)


def source_expression_with_row_maps(
    node: ast.AST | None,
    origins: dict[str, str],
    row_sources_by_arg: dict[str, dict[str, str]],
) -> str:
    if node is None:
        return "-"
    if isinstance(node, ast.Attribute) and isinstance(node.value, ast.Name):
        row_sources = row_sources_by_arg.get(node.value.id)
        if row_sources is not None:
            return row_sources.get(to_camel(node.attr), f"DB row.{to_camel(node.attr)}")
    if isinstance(node, ast.Call):
        name = call_name(node.func) or ast.unparse(node.func)
        if node.args:
            inner = source_expression_with_row_maps(node.args[0], origins, row_sources_by_arg)
            if inner.startswith("DB:"):
                return f"{inner} から導出"
        if name.endswith("Response"):
            child_sources = [
                source_expression_with_row_maps(keyword.value, origins, row_sources_by_arg)
                for keyword in node.keywords
                if keyword.arg
            ]
            db_sources = tuple(
                dict.fromkeys(source for source in child_sources if source.startswith("DB:"))
            )
            if db_sources:
                return f"{name}: " + ", ".join(db_sources)
            return f"{name}(...)"
    if isinstance(node, ast.BoolOp):
        operator = " or " if isinstance(node.op, ast.Or) else " and "
        return operator.join(
            source_expression_with_row_maps(value, origins, row_sources_by_arg)
            for value in node.values
        )
    return source_expression(node, origins)


def target_names(node: ast.AST) -> list[str]:
    if isinstance(node, ast.Name):
        return [node.id]
    if isinstance(node, ast.Tuple):
        return [name for element in node.elts for name in target_names(element)]
    return []


def tuple_element_sources(node: ast.AST, origins: dict[str, str]) -> list[str]:
    if not isinstance(node, ast.Tuple):
        return [source_expression(node, origins)]
    return [source_expression(element, origins) for element in node.elts]


def awaited_query_name(node: ast.AST) -> str | None:
    call = node.value if isinstance(node, ast.Await) else node
    if not isinstance(call, ast.Call):
        return None
    if not isinstance(call.func, ast.Attribute) or not isinstance(call.func.value, ast.Name):
        return None
    if call.func.value.id != "queries":
        return None
    return call.func.attr


def assignment_targets(node: ast.Assign) -> list[str]:
    return [target.id for target in node.targets if isinstance(target, ast.Name)]


def collect_function_origins(
    function: ast.AsyncFunctionDef | ast.FunctionDef,
    query_by_name: dict[str, QuerySpec],
    endpoint_origins: dict[str, str],
) -> dict[str, str]:
    origins = dict(endpoint_origins)
    for arg in function.args.args:
        if arg.arg in DEFAULT_ARG_ORIGINS:
            origins.setdefault(arg.arg, DEFAULT_ARG_ORIGINS[arg.arg])
    for statement in ast.walk(function):
        if isinstance(statement, ast.For):
            targets = target_names(statement.target)
            if not targets:
                continue
            if isinstance(statement.iter, ast.Tuple):
                position_sources: list[list[str]] = [[] for _target in targets]
                for item in statement.iter.elts:
                    sources = tuple_element_sources(item, origins)
                    for index, source in enumerate(sources[: len(position_sources)]):
                        if source not in position_sources[index]:
                            position_sources[index].append(source)
                for target, sources in zip(targets, position_sources, strict=False):
                    origins[target] = " / ".join(sources) if sources else f"関数内変数: {target}"
            else:
                source = source_expression(statement.iter, origins)
                for target in targets:
                    origins[target] = f"{source} の各要素"
            continue
        if isinstance(statement, ast.Assign):
            targets = assignment_targets(statement)
            if not targets:
                continue
            query_name = awaited_query_name(statement.value)
            if query_name is not None and query_name in query_by_name:
                query_tables = query_by_name[query_name].tables
                table = query_tables[0] if query_tables else "-"
                for target in targets:
                    origins[target] = f"DB: {table}"
                continue
            if isinstance(statement.value, ast.Subscript) and isinstance(
                statement.value.value, ast.Name
            ):
                parent = statement.value.value.id
                if parent in origins:
                    for target in targets:
                        origins[target] = origins[parent]
                continue
            source = source_expression(statement.value, origins)
            for target in targets:
                origins[target] = format_origin_expression(source, origins)
    return origins


def query_param_calls(
    functions_path: Path,
    query_by_name: dict[str, QuerySpec],
    endpoint_origins: dict[str, str],
) -> dict[str, list[dict[str, str]]]:
    tree = ast.parse(functions_path.read_text(encoding="utf-8"), filename=str(functions_path))
    calls: dict[str, list[dict[str, str]]] = {}
    for function in tree.body:
        if not isinstance(function, ast.AsyncFunctionDef | ast.FunctionDef):
            continue
        origins = collect_function_origins(function, query_by_name, endpoint_origins)
        for node in ast.walk(function):
            if not isinstance(node, ast.Call):
                continue
            if not isinstance(node.func, ast.Attribute) or not isinstance(
                node.func.value, ast.Name
            ):
                continue
            if node.func.value.id != "queries":
                continue
            if len(node.args) < 2 or not isinstance(node.args[1], ast.Call):
                continue
            params_call = node.args[1]
            values = {
                keyword.arg: source_expression(keyword.value, origins)
                for keyword in params_call.keywords
                if keyword.arg
            }
            calls.setdefault(node.func.attr, []).append(values)
    return calls


def external_resource_inputs(
    functions_path: Path,
    query_by_name: dict[str, QuerySpec],
    endpoint_origins: dict[str, str],
) -> tuple[ExternalResourceInput, ...]:
    tree = ast.parse(functions_path.read_text(encoding="utf-8"), filename=str(functions_path))
    inputs: list[ExternalResourceInput] = []
    seen: set[tuple[str, tuple[tuple[str, str], ...]]] = set()
    for function in tree.body:
        if not isinstance(function, ast.AsyncFunctionDef | ast.FunctionDef):
            continue
        origins = collect_function_origins(function, query_by_name, endpoint_origins)
        for node in ast.walk(function):
            if not isinstance(node, ast.Call):
                continue
            name = call_name(node.func)
            if name is None or not name.endswith("Input"):
                continue
            if name.endswith("Params"):
                continue
            params = tuple(
                (to_camel(keyword.arg), source_expression(keyword.value, origins))
                for keyword in node.keywords
                if keyword.arg
            )
            key = (name, params)
            if key in seen:
                continue
            seen.add(key)
            inputs.append(ExternalResourceInput(class_name=name, parameters=params))
    return tuple(inputs)


def resource_changes_from_dir(
    api_dir: Path,
    endpoint_origins: dict[str, str],
) -> tuple[ResourceChange, ...]:
    queries = query_specs(api_dir / "queries.py")
    model_fields = model_fields_by_class(api_dir / "queries.py")
    param_calls = query_param_calls(api_dir / "functions.py", queries, endpoint_origins)
    changes: list[ResourceChange] = []
    for function_name, query in queries.items():
        sql = sql_action_spec(api_dir / "sql" / query.sql_filename)
        if sql is None or sql.action == "参照":
            continue
        field_values = param_calls.get(function_name, [{}])
        fields = model_fields.get(query.params_class, ())
        for values_by_param in field_values:
            value_rows: list[tuple[str, str, str, str]] = []
            notes: list[tuple[str, str]] = []
            for column, sql_value in sql.column_params:
                param = sql_value.parameter
                source = values_by_param.get(param, "-")
                if source == "-" and sql_value.note_sql is not None:
                    note_label = f"※{len(notes) + 1}"
                    notes.append((note_label, sql_value.note_sql))
                    param = note_label
                    source = f"{note_label} {sql_value.source}"
                elif source == "-" and param in fields:
                    source = f"{query.params_class}.{param}"
                elif source == "-":
                    source = f"SQL式: {param}"
                source = format_origin_expression(source, endpoint_origins)
                value_rows.append((column, "-", param, source))
            changes.append(
                ResourceChange(
                    action=sql.action,
                    table=sql.table,
                    summary=query.summary,
                    sql_filename=sql.filename,
                    values=tuple(value_rows),
                    notes=tuple(notes),
                )
            )
    return tuple(changes)


def response_constructor_values(
    functions_path: Path,
    response_model: str | None,
    query_by_name: dict[str, QuerySpec],
    endpoint_origins: dict[str, str],
) -> dict[str, str]:
    if response_model is None or not functions_path.exists():
        return {}
    tree = ast.parse(functions_path.read_text(encoding="utf-8"), filename=str(functions_path))
    values: dict[str, str] = {}
    for function in tree.body:
        if not isinstance(function, ast.AsyncFunctionDef | ast.FunctionDef):
            continue
        origins = collect_function_origins(function, query_by_name, endpoint_origins)
        for node in ast.walk(function):
            if not isinstance(node, ast.Call):
                continue
            if call_name(node.func) != response_model:
                continue
            for keyword in node.keywords:
                if keyword.arg:
                    values[to_camel(keyword.arg)] = source_expression(keyword.value, origins)
    return values


def row_sources_by_function_arg(
    function: ast.AsyncFunctionDef | ast.FunctionDef,
    row_source_maps: dict[str, dict[str, str]],
) -> dict[str, dict[str, str]]:
    sources: dict[str, dict[str, str]] = {}
    for arg in function.args.args:
        if arg.annotation is None:
            continue
        annotation = ast.unparse(arg.annotation)
        row_class = annotation.split(".")[-1]
        if row_class in row_source_maps:
            sources[arg.arg] = row_source_maps[row_class]
    return sources


def response_constructor_source_maps(
    functions_path: Path,
    query_by_name: dict[str, QuerySpec],
    endpoint_origins: dict[str, str],
    row_source_maps: dict[str, dict[str, str]],
) -> dict[str, dict[str, str]]:
    tree = ast.parse(functions_path.read_text(encoding="utf-8"), filename=str(functions_path))
    maps: dict[str, dict[str, str]] = {}
    for function in tree.body:
        if not isinstance(function, ast.AsyncFunctionDef | ast.FunctionDef):
            continue
        origins = collect_function_origins(function, query_by_name, endpoint_origins)
        row_sources = row_sources_by_function_arg(function, row_source_maps)
        for node in ast.walk(function):
            if not isinstance(node, ast.Call):
                continue
            class_name = call_name(node.func)
            if class_name is None or not class_name.endswith("Response"):
                continue
            fields = maps.setdefault(class_name, {})
            for keyword in node.keywords:
                if keyword.arg:
                    fields[to_camel(keyword.arg)] = source_expression_with_row_maps(
                        keyword.value,
                        origins,
                        row_sources,
                    )
    return maps


def list_item_schema_name(response_schema: SchemaSpec | None) -> str | None:
    if response_schema is None:
        return None
    for field in response_schema.fields:
        if field.name == "items" and field.type_name.startswith("list["):
            return field.type_name.removeprefix("list[").removesuffix("]")
    return None


def nested_schema_name(schema: SchemaSpec | None, field_name: str) -> str | None:
    if schema is None:
        return None
    for field in schema.fields:
        if field.name != field_name:
            continue
        return strip_optional_type(field.type_name)
    return None


def response_value_rows(
    response_schema: SchemaSpec | None,
    specs: dict[str, SchemaSpec],
    values: dict[str, str],
    constructor_sources: dict[str, dict[str, str]] | None = None,
) -> tuple[tuple[str, str, str], ...]:
    constructor_sources = constructor_sources or {}
    if response_schema is None:
        return ()
    item_schema_name = list_item_schema_name(response_schema)
    item_schema = specs.get(item_schema_name or "")
    item_sources = constructor_sources.get(item_schema_name or "", {})
    rows: list[tuple[str, str, str]] = []
    for field in schema_field_rows(response_schema, specs):
        top = field.name.split(".", 1)[0]
        source = values.get(field.name) or values.get(top, "-")
        if field.name == "items" and item_schema_name:
            source = ""
        elif field.name.startswith("items.") and item_schema_name:
            tail = field.name.removeprefix("items.")
            if "." in tail:
                nested_field, nested_tail = tail.split(".", 1)
                nested_name = nested_schema_name(item_schema, nested_field)
                source = constructor_sources.get(nested_name or "", {}).get(nested_tail, source)
            else:
                nested_name = nested_schema_name(item_schema, tail)
                source = "" if nested_name in specs else item_sources.get(tail, source)
        rows.append((field.name, field.description, source))
    return tuple(rows)


def normal_prerequisites(api_dir: Path, api_root: Path) -> tuple[str, ...]:
    doc = api_unit_test_factors_from_dir(api_dir, api_root)
    items: list[str] = []
    for factor in doc.factors:
        if factor.kind == "条件分岐":
            items.append(f"{factor.title}: 不成立")
        if factor.kind == "例外処理":
            items.append(f"{factor.title}: 発生しない")
    return tuple(items)


def api_detail_design_from_dir(
    api_dir: Path,
    api_root: Path,
    ddl_tables: dict[str, Table] | None = None,
) -> ApiDetailDesign:
    router_tree = ast.parse((api_dir / "router.py").read_text(encoding="utf-8"))
    endpoint = endpoint_function(router_tree)
    specs = schema_specs(api_dir / "schemas.py")
    queries = query_specs(api_dir / "queries.py")
    row_source_maps = query_row_source_maps(api_dir, queries)
    endpoint_origins = endpoint_input_origins(endpoint)
    request_schema_name = endpoint_body_schema(endpoint)
    response_schema_name = endpoint_response_model(endpoint)
    relative = api_dir.relative_to(api_root)
    domain, api = relative.parts
    request_schema = specs.get(request_schema_name or "")
    response_schema = specs.get(response_schema_name or "")
    return ApiDetailDesign(
        domain=domain,
        api=api,
        operation_id=endpoint_operation_id(endpoint),
        method=endpoint_route_method(endpoint),
        path=endpoint_route_path(endpoint),
        request_schema=request_schema,
        response_schema=response_schema,
        endpoint_inputs=endpoint_inputs(endpoint),
        request_fields=(
            tuple(schema_field_rows(request_schema, specs)) if request_schema is not None else ()
        ),
        prerequisites=normal_prerequisites(api_dir, api_root),
        resource_changes=resource_changes_from_dir(api_dir, endpoint_origins),
        external_inputs=external_resource_inputs(
            api_dir / "functions.py",
            queries,
            endpoint_origins,
        ),
        response_values=response_value_rows(
            response_schema,
            specs,
            response_constructor_values(
                api_dir / "functions.py",
                response_schema_name,
                queries,
                endpoint_origins,
            ),
            response_constructor_source_maps(
                api_dir / "functions.py",
                queries,
                endpoint_origins,
                row_source_maps,
            ),
        ),
        ddl_tables=ddl_tables or {},
    )


def render_field_table(fields: Iterable[FieldSpec]) -> list[str]:
    lines = ["| 項目 | 型 | 説明 |", "| --- | --- | --- |"]
    for field in fields:
        lines.append(
            f"| `{markdown_escape(field.name)}` | `{markdown_escape(field.type_name)}` | "
            f"{markdown_escape(field.description)} |"
        )
    return lines


def render_detail_design_markdown(doc: ApiDetailDesign) -> str:
    lines = [
        GENERATED_COMMENT,
        "",
        f"# {doc.api} detail design",
        "",
        f"- Operation: `{doc.operation_id}`",
        f"- Endpoint: `{doc.method} {doc.path}`",
        "",
        "## 1. 正常系入力",
        "",
        "| Location | Name | Type | 説明 |",
        "| --- | --- | --- | --- |",
    ]
    for item in doc.endpoint_inputs:
        lines.append(
            f"| `{item.location}` | `{markdown_escape(item.name)}` | "
            f"`{markdown_escape(item.type_name)}` | {markdown_escape(item.description)} |"
        )
    if doc.request_schema is not None:
        lines.extend(["", f"### Request body `{doc.request_schema.name}`", ""])
        lines.extend(render_field_table(doc.request_fields))
    else:
        lines.extend(["", "_Request body はありません。_"])

    lines.extend(["", "## 2. 正常系前提", ""])
    if doc.prerequisites:
        lines.extend(f"- {markdown_escape(item)}" for item in doc.prerequisites)
    else:
        lines.append("- 条件分岐または例外処理の正常系前提はありません。")

    lines.extend(["", "## 3. 正常系リソース変更", ""])
    if not doc.resource_changes and not doc.external_inputs:
        lines.append("_正常系で作成/更新/削除するリソースはありません。_")
    for change in doc.resource_changes:
        lines.extend(
            [
                f"### DB `{change.table}` {change.action}",
                "",
                f"- SQL: `{change.sql_filename}`",
                f"- 目的: {markdown_escape(change.summary)}",
                "",
                "| カラム | カラム説明 | パラメータ/SQL式 | 値の取得元 |",
                "| --- | --- | --- | --- |",
            ]
        )
        for column, _description, param, source in change.values:
            lines.append(
                f"| `{markdown_escape(column)}` | "
                f"{markdown_escape(column_comment(doc.ddl_tables, change.table, column))} | "
                f"`{markdown_escape(param)}` | "
                f"{markdown_escape(source)} |"
            )
        if change.notes:
            lines.extend(["", "#### SQL式"])
            for label, sql in change.notes:
                lines.extend(["", f"- {label}", "", f"```sql\n{sql}\n```"])
        lines.append("")
    for external in doc.external_inputs:
        lines.extend(
            [
                f"### 外部リソース `{external.class_name}`",
                "",
                "| パラメータ | 値の取得元 |",
                "| --- | --- |",
            ]
        )
        for name, source in external.parameters:
            lines.append(f"| `{markdown_escape(name)}` | {markdown_escape(source)} |")
        lines.append("")

    lines.extend(["", "## 4. 正常系レスポンス", ""])
    if doc.response_schema is None:
        lines.append("_Response model はありません。_")
    else:
        lines.extend(
            [
                f"- Response model: `{doc.response_schema.name}`",
                "",
                "| 項目 | 説明 | 値の取得元 |",
                "| --- | --- | --- |",
            ]
        )
        for name, description, source in doc.response_values:
            lines.append(
                f"| `{markdown_escape(name)}` | {markdown_escape(description)} | "
                f"{markdown_escape(source)} |"
            )
    return "\n".join(lines).rstrip() + "\n"


def output_path(doc: ApiDetailDesign, docs_root: Path) -> Path:
    return docs_root / doc.domain / doc.api / "detail-design_gen.md"


def generate_detail_designs(api_root: Path, docs_root: Path, ddl_path: Path) -> dict[Path, str]:
    ddl_tables = parse_tables(ddl_path.read_text(encoding="utf-8"))
    rendered: dict[Path, str] = {}
    for directory in api_dirs(api_root):
        doc = api_detail_design_from_dir(directory, api_root, ddl_tables)
        rendered[output_path(doc, docs_root)] = render_detail_design_markdown(doc)
    return rendered


def changed_outputs(rendered: dict[Path, str]) -> list[Path]:
    changed: list[Path] = []
    for path, content in rendered.items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            changed.append(path)
    return changed


def write_outputs(rendered: dict[Path, str]) -> None:
    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate API detail design specs.")
    parser.add_argument("--api-root", type=Path, default=Path("src/app/apis"))
    parser.add_argument("--docs-root", type=Path, default=Path("docs/spec/40.apis"))
    parser.add_argument("--ddl", type=Path, default=Path("src/db/ddl.sql"))
    parser.add_argument("--check", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> None:
    args = build_arg_parser().parse_args(argv)
    rendered = generate_detail_designs(args.api_root, args.docs_root, args.ddl)
    if args.check:
        changed = changed_outputs(rendered)
        if changed:
            raise SystemExit("\n".join(path.as_posix() for path in changed))
        return
    write_outputs(rendered)


if __name__ == "__main__":  # pragma: no cover
    main()
