from __future__ import annotations

import argparse
from collections.abc import Mapping, Sequence
from pathlib import Path

from tools.e2e_models import FACTORS, FLOW_ID, E2eFactor
from tools.generation_io import check_outputs, write_outputs

GENERATED_COMMENT = (
    "# This file is generated by uv run python -m tools.generate_e2e_factor_yaml. "
    "Do not edit manually."
)


def yaml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_factor_yaml(factor: E2eFactor) -> str:
    lines: list[str] = [
        GENERATED_COMMENT,
        "schema_version: 1",
        "",
        "factor:",
        f"  id: {factor.factor_id}",
        f"  slug: {factor.slug}",
        f"  title: {yaml_quote(factor.title)}",
        f"  category: {factor.category}",
        f"  order: {factor.order}",
        f"  owner_step: {factor.owner_step}",
        "  generated_from:",
        "    - type: e2e_flow",
        f"      path: docs/spec/50.e2e/{FLOW_ID}/flow.manual.yaml",
        "",
        "elements:",
    ]
    for element in factor.elements:
        lines.extend(
            [
                f"  - id: {element.element_id}",
                f"    label: {yaml_quote(element.label)}",
                f"    default: {str(element.default).lower()}",
                f"    terminal: {str(element.terminal).lower()}",
                "    expected:",
                f"      summary: {yaml_quote(element.expected)}",
            ]
        )
    lines.append("")
    lines.append("constraints:")
    if factor.requires:
        lines.append("  requires:")
        lines.extend(f"    - {requirement}" for requirement in factor.requires)
    else:
        lines.append("  requires: []")
    lines.extend(
        [
            "",
            "pruning:",
            "  after_terminal: true",
            "  equivalent_if_same_terminal_step: true",
            "",
        ]
    )
    return "\n".join(lines)


def render_effective_factors_yaml(factors: Sequence[E2eFactor]) -> str:
    lines: list[str] = [
        GENERATED_COMMENT,
        "schema_version: 1",
        f"flow: {FLOW_ID}",
        "factors:",
    ]
    for factor in factors:
        lines.append(f"  - id: {factor.factor_id}")
        lines.append(f"    slug: {factor.slug}")
        lines.append(f"    title: {yaml_quote(factor.title)}")
        lines.append(f"    owner_step: {factor.owner_step}")
        lines.append("    elements:")
        for element in factor.elements:
            flags: list[str] = []
            if element.default:
                flags.append("default")
            if element.terminal:
                flags.append("terminal")
            suffix = f" # {', '.join(flags)}" if flags else ""
            lines.append(f"      - {element.element_id}{suffix}")
    lines.append("")
    return "\n".join(lines)


def rendered_outputs(output_root: Path = Path("docs/spec/50.e2e")) -> Mapping[Path, str]:
    flow_root = output_root / FLOW_ID
    rendered: dict[Path, str] = {}
    for factor in FACTORS:
        rendered[
            flow_root / "factors" / f"{factor.factor_id}_{factor.slug}.gen.yaml"
        ] = render_factor_yaml(factor)
    rendered[flow_root / "factors" / "effective_factors.gen.yaml"] = (
        render_effective_factors_yaml(FACTORS)
    )
    return rendered


def generate(*, check: bool = False, output_root: Path = Path("docs/spec/50.e2e")) -> int:
    rendered = rendered_outputs(output_root)
    if check:
        return check_outputs(rendered)
    write_outputs(rendered)
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    return generate(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
